Create a chat application using solidity and react on Avalanche
figment-networks/datahub-learn pull request #106
Opened 2021-05-16 15:43 UTC by realnimish

# Description*

I have added a tutorial to build a chat application using solidity and react on Avalanche's Fuji testnet

## Type of change*

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## This PR created for* - 

- [ ] DataHub Official Docs (Network Documentation, API docs etc.) changes/updates/fixes
- [ ] Figment Learn Docs (Pathway, Existing Tutorials, New Tutorial etc.) changes/updates/fixes

# Checklist*:

- [ ] I updated the `SUMMARY.md` file (FYI, It's needed only when you're creating a new file like submitting a new tutorial, pathway section)
- [ ] I created one tutorial for this PR (one PR <=> one tutorial)
- [ ] I checked and accept that my PR for new tutorial following the [**Tutorial Guidelines**](https://learn.figment.io/other/tutorial-guidelines) of this project
- [ ] I checked and read the contribution guide before making this PR [**HERE**](https://learn.figment.io/figment-learn/contribute)  
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2021-05-20 10:30 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +
Instead of putting the code in `<summary>contract</summary>` tags put it just in a nomral code block to avoid the drop down function.

2021-05-20 10:35 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +We will have three types of user-defined data types, namely - `user`, `friend` & `message`.
Instead of directly explaining the data types, please explain why you're writing this smart contract and what it will do? and then comes How? after that you can explain the data types and their functioning.

2021-05-20 10:56 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +
Please take a error driven approach here where you can mention basic errors a developers/learner can face during the contract deployment process and some steps to troubleshoot the that problem. For reference you should [HERE](https://learn.figment.io/other/tutorial-guidelines/sample-tutorial-structure)

2021-05-20 11:00 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +<summary>index.html</summary>
Instead of putting the code in `summary` tags put all code part just in a nomral code block to avoid the drop down function (at all the steps)

2021-05-20 11:05 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +
Here as an additional knoeledge point plz explain what is ABI?

2021-05-20 11:09 UTC, yash-sharma1 commented
@guillaumegaluz can you please this as well, I added my thoughts to it and request some changes.

2021-05-20 11:10 UTC, yash-sharma1 requested changes
Please consider the above comments as requested changes.

2021-05-21 13:36 UTC, guillaumegaluz commented
Was this app developed from scratch or was it inspired by another existing tutorial or app?

2021-05-21 16:10 UTC, realnimish commented
> Was this app developed from scratch or was it inspired by another existing tutorial or app?

We have developed the application from scratch

2021-05-21 16:23 UTC, realnimish commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +<summary>index.html</summary>
Fixed here f59dd2fa0fe95dcea48de2e15ff1804267438b50

2021-05-21 16:24 UTC, realnimish commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +
Fixed f59dd2fa0fe95dcea48de2e15ff1804267438b50

2021-05-21 17:09 UTC, realnimish commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +
Added troubleshoot section 26b1b7f73793840964124826c9813a7c5c4fd6e7

2021-05-21 17:11 UTC, realnimish commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +
Resolved here 8b61042fdf9c753a3e3deff945807b79f6fed4cb

2021-05-21 18:25 UTC, realnimish commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +We will have three types of user-defined data types, namely - `user`, `friend` & `message`.
Added the explanation here 6a4c0a575e04f40b14cb684b4ab8b536ecdd6016

2021-05-24 12:42 UTC, yash-sharma1 commented
@guillaumegaluz can you please review it once again and add your thoughts? Thanks

2021-05-26 10:41 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +                        <div className="SendMessage"  style={{ borderTop:"2px solid black",position:"relative"bottom:"0px",padding:"10px 45px 0 45px",margin:"0 95px 0 0",
` <div className="SendMessage"  style={{ borderTop:"2px solid black",position:"relative"bottom:"0px",padding:"10px 45px 0 45px",margin:"0 95px 0 0",` is throwing error due because of missing `,`

It Should be 
` <div className="SendMessage"  style={{ borderTop:"2px solid black",position:"relative",bottom:"0px",padding:"10px 45px 0 45px",margin:"0 95px 0 0",`

2021-05-26 10:47 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +Make a new file named `abi.js` in the `src` folder. Export const variable named abi which stores the ABI you had generated earlier. Your abi.js file should look like this!
You can write it as - 
Export const variable named abi which stores the ABI you had generated earlier. Add your abi const variable after `export const abi =` Your abi.js file should look like this!

2021-05-26 10:51 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +The tutorial was created by [Nimish Agrawal](https://github.com/realnimish) & [Sayan Kar](https://github.com/SayanKar). They are currently undergraduate students pursuing B.Tech in CSE [2018-2022] fr
It should be short and informative so please write it as  -  
The tutorial was created by [Nimish Agrawal](https://github.com/realnimish) & [Sayan Kar](https://github.com/SayanKar). You can reach out to the authors on Figment Forum
- [Nimish Agrawal](https://community.figment.io/u/nimishagrawal100.in/)
- [Sayan Kar](Link to Sayan Kar's Figment Forum Profile)

2021-05-27 06:44 UTC, yash-sharma1 commented
In the end, while connecting to metamask I'm getting this error - 
![unknown](https://user-images.githubusercontent.com/44340561/119778345-05dba100-bee5-11eb-85b9-c9bd18ea4082.png)

2021-05-27 17:28 UTC, realnimish commented
> In the end, while connecting to metamask I'm getting this error -
> ![unknown](https://user-images.githubusercontent.com/44340561/119778345-05dba100-bee5-11eb-85b9-c9bd18ea4082.png)

You have most likely not added the contract address in the `index.js` file. Troubleshoot section already covers this issue under `Application crash` and to make the debugging more developer friendly we have added an alert message in the application itself in the following commit 18462e730023ba1f5817132ecf2523f946cb3697.

2021-05-27 17:41 UTC, yash-sharma1 commented
> > In the end, while connecting to metamask I'm getting this error -
> > ![unknown](https://user-images.githubusercontent.com/44340561/119778345-05dba100-bee5-11eb-85b9-c9bd18ea4082.png)
> 
> You have most likely not added the contract address in the `index.js` file. Troubleshoot section already covers this issue under `Application crash` and to make the debugging more developer friendly we have added an alert message in the application itself in the following commit [18462e7](https://github.com/figment-networks/datahub-learn/commit/18462e730023ba1f5817132ecf2523f946cb3697).

Nopes, I added the contract address in the `indes.js` file but still got the error - 
![Screenshot 2021-05-27 231001](https://user-images.githubusercontent.com/44340561/119872221-d9ee0900-bf40-11eb-8187-71484b34da54.png)

2021-05-27 19:02 UTC, realnimish commented
> > > In the end, while connecting to metamask I'm getting this error -
> > > ![unknown](https://user-images.githubusercontent.com/44340561/119778345-05dba100-bee5-11eb-85b9-c9bd18ea4082.png)
> > 
> > 
> > You have most likely not added the contract address in the `index.js` file. Troubleshoot section already covers this issue under `Application crash` and to make the debugging more developer friendly we have added an alert message in the application itself in the following commit [18462e7](https://github.com/figment-networks/datahub-learn/commit/18462e730023ba1f5817132ecf2523f946cb3697).
> 
> Nopes, I added the contract address in the `index.js` file but still got the error -
> ![Screenshot 2021-05-27 231001](https://user-images.githubusercontent.com/44340561/119872221-d9ee0900-bf40-11eb-8187-71484b34da54.png)

I think you have not deployed the contract on fuji testnet. There is no create transaction visible on [block explorer](https://testnet.avascan.info/blockchain/c/address/0xd8b934580fce35a11b58c6d73adee468a2833fa8/operations) for the given contract address.

Please make sure that you have selected `Injected Web3` while deploying from remix and have setup the fuji network configuration on Metamask as shown in the given [Tutorial - Deploy a Smart Contract on Avalanche using Remix and MetaMask](https://learn.figment.io/network-documentation/avalanche/tutorials/deploy-a-smart-contract-on-avalanche-using-remix-and-metamask) { Mentioned in the prerequisite of our tutorial }

2021-05-28 05:59 UTC, yash-sharma1 commented
> I think you have not deployed the contract on fuji testnet. There is no create transaction visible on [block explorer](https://testnet.avascan.info/blockchain/c/address/0xd8b934580fce35a11b58c6d73adee468a2833fa8/operations) for the given contract address.
> 
> Please make sure that you have selected `Injected Web3` while deploying from remix and have setup the fuji network configuration on Metamask as shown in the given [Tutorial - Deploy a Smart Contract on Avalanche using Remix and MetaMask](https://learn.figment.io/network-documentation/avalanche/tutorials/deploy-a-smart-contract-on-avalanche-using-remix-and-metamask) { Mentioned in the prerequisite of our tutorial }

Thanks, Let me check it once again

2021-05-28 19:42 UTC, guillaumegaluz requested changes

2021-05-28 19:42 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +<br>
remove <br> here and everywhere else in the tutorial.

2021-05-28 19:42 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +* The second method registers _new user_ on the platform and finally the last method will return the username of the user if it exists.
I like how you explain those functions at a higher level by grouping them by theme but I would format it this way:

-------------------
We will define 3 functions:
- `checkUserExists(pubkey)` is used to check if a user is registered with our application or not. It will help make sure duplicate users are not created and it will also be called from other functions to check their existence.
- `createAccount(name)` registers a new user on the platform
- `getUsername(pubkey)` will return the username of the user if it exists.

2021-05-28 20:21 UTC, guillaumegaluz requested changes

2021-05-28 20:21 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +Move out of the public folder and make a file named `Components.js` inside `src` folder and put the following code inside.
Instead of putting all the fucntional components into one file called `Components.jsx`, it's better to create a folder src/components` which will have one file per component: `AddNewChat.jsx`, `ChatCards.jsx`, etc

2021-05-28 20:21 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +Move out of the public folder and make a file named `Components.js` inside `src` folder and put the following code inside.
Use `.jsx` instead of `.js` if the file is exporting a component written with JSX

2021-05-28 20:21 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +export function ChatCards(props){
Should this be `ChatCard` instead? I see only one card

2021-05-28 20:21 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +                    <div style={{display:props.showButton==="none"?"block":"none"}}>
add spaces after `:`

2021-05-29 00:37 UTC, pyr0gan requested changes
Please review my feedback and revise your tutorial 👍🏻 
We will go over your revisions next week. Enjoy the weekend!

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +        /* Call connectToMetaMask */
This comment can be deleted.

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +        if(res===true){
Proper spacing, please 😄 
> if( res === true ){

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +import { NavBar, ChatCards, Message, AddNewChat } from './Components';
The path you are requiring the components from would need to change, in accordance with @guillaumegaluz 's comment regarding a `components` subdirectory within the `src` directory..

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +    const contractAddress = ""; // Add the contract address inside the quotes
You can place the comment on the line above 😄

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +            try{
> try {

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +				const mycontract = new ethers.Contract(contractAddress, contractABI, signer);
Javascript variable names should be camelCase, so 'myContract'. This would require fixing it wherever it is referenced in the code.

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +				alert("You might not have set the contractAddress properly! Please check...")
> alert("contractAddress not set!")

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +        else{
> else {

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +    // Checks if the metamask connects
> // Check if Metamask is available

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +        /* Open Metamask window*/
This comment can be removed.

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +        try{
> try {

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +    //Sends messsage to a User
`// ` Space after comment slashes.

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +        await myContract.sendMessage(recieverAddress,data);
Spaces after commas :smile:

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +        /* Get message*/
Change to single line comment syntax.

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +            /* Get Friends*/
Change to single line comment syntax.

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +            try{
> try {

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +            }catch(err){
Spacing is an important aspect of readability.

> } catch(err) {

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +    },[myPublicKey,myContract]);
> }, [myPublicKey, myContract]);

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +    //Makes Cards for each Message
Space after `//`

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +Make a new file named `abi.js` in the `src` folder. Export const variable named abi which stores the ABI you had generated earlier. Add your ABI after `export const abi = `. Your abi.js file should l
Keep this section consistent with previous ones.

> Create a new file called `abi.js` in the `src` folder, and paste the following code :

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +Make a new file named `abi.js` in the `src` folder. Export const variable named abi which stores the ABI you had generated earlier. Add your ABI after `export const abi = `. Your abi.js file should l
Please explain what an ABI is.

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +* Don't forget to setup Metamask with `Fuji testnet` and also fund the account with Fuji c-chain test tokens for tx fees. Please refer to this tutorial on [Connecting Datahub to Metamask](https://lea
Please expand on how to set up Metamask with the Fuji testnet. Linking to a separate tutorial is not sufficient.

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +Congratulatons!! You've successfully developed a distributed chatting application deployed on Avalanche's Fuji network and have also created a UI via which you can interact with the DApp.
> "Congratulations! We have successfully developed a decentralized chat application which can be deployed on Avalanche or other EVM-compatible blockchain. We also created a boilerplate React application to use as the frontend for our dApp."

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +* Make sure that you have selected the correct account on metamask if you have more than one account connected to the site.
It may be preferable to have an image to explain this.

2021-05-29 00:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +The current DApp has very limited functionalities and we can improve it by adding features like deleting messages, blocking users, creating group(s) and optimising the DApp interaction cost with poss
> This dApp has very limited functionality. We can improve it by adding functions to delete messages, block users, or create groups of friends. We could also optimize the dApp interaction cost with functions to limit the maximum number of messages, or possibly using event log for short messages.

2021-05-31 15:44 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
>  Now remove the contents of src and public folder
To clarify, I mean that you need to remove these instructions regarding the contents of /src and /public. It is not germane to the tutorial to remove the scaffolded files.

2021-05-31 15:59 UTC, pyr0gan reviewed
Many of the issues are resolved & thank you for that, however there are still a few things outstanding. I have looked over the latest commit, and the formatting of some of the code blocks is still using a mix of tabs and spaces, which leads to some overly-indented code. We ask that you use 4 spaces per indent level.

We are approaching a final draft, just remember to get to the issues I pointed out regarding the information from other tutorials, as well as the 'Implementing' sections, moving the function descriptions to a bulleted list. See this comment by Guillaume : https://github.com/figment-networks/datahub-learn/pull/106/files/18462e730023ba1f5817132ecf2523f946cb3697..c432f1a75cc45d758a7041ebd31f567b5d9735fe#r641780098

2021-05-31 16:14 UTC, realnimish commented
Firstly I would like to thank all the reviewers for such a precise review (I think this PR is already way ahead of others in terms of number of interactions XD). The suggestions were to the point and it would surely have taken a lot of effort and maybe some strain on the eyes to identify the typos which we obviously missed in our inspection, sincere apologies for that. We are still working on the changes suggested and would request for the review as soon as those are finished. Thanks again!

2021-06-01 19:05 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +* Should've completed [Deploy a Smart Contract on Avalanche using Remix and MetaMask](https://learn.figment.io/network-documentation/avalanche/tutorials/deploy-a-smart-contract-on-avalanche-using-rem
@realnimish +1 on this. Deploying this is not trivial, and certainly nto something where we can assume that the learner will be able to easily use the other tutorial in the context of this one.

Although it sounds like we're duplicating some instructions, i think here it is the right thing to do - again - from the learner's perspective.

I would just copy and paste the deployement instructions in a new section here. Thanks!

2021-06-01 19:07 UTC, guillaumegaluz commented
> Firstly I would like to thank all the reviewers for such a precise review (I think this PR is already way ahead of others in terms of number of interactions XD). The suggestions were to the point and it would surely have taken a lot of effort and maybe some strain on the eyes to identify the typos which we obviously missed in our inspection, sincere apologies for that. We are still working on the changes suggested and would request for the review as soon as those are finished. Thanks again!

Thanks for your patience and thorough revisions @realnimish. We're trying to be more precise on reviews, not to be annoying, but to guarantee that the tutorials we are delivering to users will be of the highest quality. And please, no need to apologize!! 

There are only a few changes left here. As soon as they are done we will merge this and let the community know about this new tutorial!

2021-06-03 04:01 UTC, SayanKar commented
@pyr0gan @guillaumegaluz @yash-sharma1 Can you please review the PR, we have made all the requested changes.

2021-06-03 17:48 UTC, pyr0gan requested changes

2021-06-03 17:48 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
>  ### Account creation
I notice that the section headings are a little off. We should start with 1st level headings, so a single \# instead of \### . See the attached image: I made Introduction a 1st level heading, Prerequisites a 2nd level heading and Requirements a 3rd level heading, to illustrate the difference and how it renders on GitBook 😄 
![Screen Shot 2021-06-03](https://user-images.githubusercontent.com/2707197/120689455-5ca32680-c461-11eb-80ee-5fa6c85af995.png)

2021-06-04 06:18 UTC, SayanKar commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
>  ### Account creation
@pyr0gan We have made a few changes and  have used the following format for heading levels.
# :- Tutorial Heading
## :- Section Heading
### :- Subsection heading 
It's not clear to me what changes you are requesting, can you please confirm ? If you are asking to make section headings 
1st level heading then the level will be the same as the tutorial heading.

2021-06-07 16:23 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
>  ### Account creation
Headings need to be H1, sub-headings are H2. Don't use H3 for anything that needs to show up on the table of contents is what I was getting at 😄 Perhaps the way I said it was confusing, apologies if it was unclear.

Introduction should be H1, it is a section heading. An example of a subheading would be in the Troubleshooting section, "Transaction Failure" this would be H2.
![Screen Shot 2021-06-07 at 10 21 41 AM](https://user-images.githubusercontent.com/2707197/121055212-4d321f00-c77a-11eb-80e2-1b482d47ed3f.png)

2021-06-07 16:29 UTC, pyr0gan reviewed
Sorry, these changes are incorrect. Please refer to the sample tutorial structure document : [https://learn.figment.io/other/tutorial-guidelines/sample-tutorial-structure](https://learn.figment.io/other/tutorial-guidelines/sample-tutorial-structure)

2021-06-07 16:39 UTC, SayanKar commented
@pyr0gan I have made the changes you asked for, can you please check.

2021-06-07 16:58 UTC, pyr0gan reviewed
Thank you for fixing the headings! Only a few more fixes to take care of and we should be able to launch today! 😄

2021-06-07 17:03 UTC, realnimish commented
> Thank you for fixing the headings! Only a few more fixes to take care of and we should be able to launch today! 😄

Cool! What all issues are remaining?

2021-06-07 17:47 UTC, pyr0gan reviewed
Last little polish pass 👍🏻 Apply these and once another member of the team agrees with the changes, we should be able to merge and announce!

🚀

2021-06-07 17:47 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
>  Today we will build a decentralized chat application on Avalanche's Fuji test-network from scratch. The dApp will allow users to connect with other users and chat with them. We will develop our smart
Just a bit of polish needed here:

> Today we will build a decentralized chat application on Avalanche's Fuji test-network from scratch.
The dApp will allow users to connect with other people and chat with them. We will develop our smart contract using Solidity which will be deployed on Avalanche's C-chain. We will have a basic, easy-to-use UI developed using ReactJS. So, let us begin!

2021-06-07 17:47 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +## Data Collections
> User Data

2021-06-07 17:47 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +## Adding new friend
> Adding friends

2021-06-07 17:47 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
>  An Application Binary Interface (ABI) is a JSON object which stores the metadata about the methods of a contract like data type of input parameters, return data type & property of the method like pay
GitHub won't let me select line 207 directly, but please make the following change :

> Navigate to the Solidity compiler Tab on the left side navigation bar and click the blue button to compile the `Database.sol` contract. Note down the `ABI` as it will be required in the next section.

2021-06-07 17:47 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
> +# Creating frontend using React
> Creating a frontend in React

2021-06-07 17:47 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
>  Now, we are going to create a react app and setup the frontend of the application.
> Now, we are going to create a React app scaffold and set up the frontend of the application.

2021-06-07 17:47 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
It looks like the Solidity highlighting on GitBook isn't specified, so I think we can actually make the Solidity codeblock Javascript instead and it will look nicer with the syntax highlighting 😄

2021-06-07 18:01 UTC, realnimish commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
I previously used the Javascript code snippet for the very same reason :)
https://github.com/figment-networks/datahub-learn/pull/106#discussion_r641765520

2021-06-07 18:05 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
Small detail, and Markdown rendering isn't universal :) Looks fine either way, some people prefer plain code and some people prefer the highlighting.

2021-06-07 18:21 UTC, realnimish commented on network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react.md
:raised_hands:

2021-06-07 18:45 UTC, pyr0gan approved these changes
Thanks for all your hard work on making this tutorial shine, @realnimish 😄 I think as long as my colleagues look it over once more and agree with the changes, we can merge.

2021-06-08 04:10 UTC, realnimish commented
> Thanks for all your hard work on making this tutorial shine, @realnimish smile I think as long as my colleagues look it over once more and agree with the changes, we can merge.

A big thanks to you guys too for all the support! I didn't imagined that I will get to learn this much in preparing a tutorial. Cheers!

cc: @yash-sharma1 @guillaumegaluz

2021-06-08 04:59 UTC, yash-sharma1 commented
Appreciate your work @realnimish & @SayanKar and your efforts in making small to small correction as per our feedback. Our main aim was to make this tutorial outstanding and improve as much as we all can and you guys did a great job in improving it. Looks good and approving the changes. 💯

2021-06-08 04:59 UTC, yash-sharma1 approved these changes

2021-06-09 04:38 UTC, merged

2021-06-09 04:44 UTC, pyr0gan commented
@realnimish We've merged the tutorial and it is live! [View it here](https://learn.figment.io/network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react) 😄 

What's next? 🚀

2021-06-09 04:55 UTC, realnimish commented
I think the formatting near the "Application crash" needs to be updated!

2021-06-09 05:23 UTC, realnimish commented
> @realnimish We've merged the tutorial and it is live! [View it here](https://learn.figment.io/network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react) smile

Cool!

> What's next? rocket

We are looking into new ideas. Do you have any in mind that you would like us to work on?

2021-06-09 06:37 UTC, yash-sharma1 commented
> > @realnimish We've merged the tutorial and it is live! [View it here](https://learn.figment.io/network-documentation/avalanche/tutorials/create-a-chat-application-using-solidity-and-react) smile
> 
> Cool!
> 
> > What's next? rocket
> 
> We are looking into new ideas. Do you have any in mind that you would like us to work on?

That's great, you can check the available list of topics **[HERE](https://www.notion.so/Tutorial-Contribution-Ideas-d8ff9cdc32ca4b58838d81d07eab49bd)** also we would like to see some tutorial around DApp building and integration with DataHub so feel free to propose new ideas from your side as well.