Avalanche -  Using Hardhat with the Avalanche C-Chain
figment-networks/datahub-learn pull request #107
Opened 2021-05-17 06:25 UTC by kevin-madhu

# Description*

This PR is supposed to bring create a new tutorial which will show the learners how to use hardhat with the Avalanche C-Chain.

Fixes # (issue)

## Type of change*

Important - Please delete options that are not relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Typo fix

## This PR created for* - 

Important - Please delete option that's not relevant to your PR.

- [ ] DataHub Official Docs (Network Documentation, API docs etc.) changes/updates/fixes
- [ x] Figment Learn Docs (Pathway, Existing Tutorials, New Tutorial etc.) changes/updates/fixes

# How Has This Been Tested? (If Applicable)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration*** (If Applicable):
* Firmware version:
* OS:
* Network/Protocol:
* SDK:

# Checklist*:

- [ x] I updated the `SUMMARY.md` file (FYI, It's needed only when you're creating a new file like submitting a new tutorial, pathway section)
- [x ] I created one tutorial for this PR (one PR <=> one tutorial)
- [ x] I checked and accept that my PR for new tutorial follwoing the [**Tutorial Guidelines**](https://learn.figment.io/other/tutorial-guidelines) of this project
- [ x] I checked and read the contribution guide before making this PR [**HERE**](https://learn.figment.io/figment-learn/contribute)  
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Other Information (Optional)
*Please add any other information/details you would like to let us know related to your proposed changes and PR*

Note - Above ponits marked with * are mandatory to fill :)

2021-05-18 13:59 UTC, yash-sharma1 requested changes

2021-05-18 13:59 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +## Prerequisites
**Prerequisites:** any prior knowledge needed or existing tutorials that need to be completed first, any tokens needed
Include 

**Requirements:** any technology that needs to be installed prior to starting the tutorial and that the tutorial will not cover (Metamask, node, truffle, etc). Do not list packages that will be installed in the tutorial (dotenv).

Here what you mentioned should go into the Requirements and add relevant knowledge required before going through this tutorial in Pre-requisite.

Check latest updates guidelines and sample tutorial structure for reference [HERE](https://learn.figment.io/other/tutorial-guidelines)

2021-05-18 13:59 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +
Here please explain the setup and installation of Avash, it can be new to some learners and jumping from here to GitHub and then from GitHub to Ava Docs can be confusing for them so it would be great if you can explain those steps here as additional for new learners.

2021-05-18 13:59 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +If you managed to get this far without any errors, you've successfully compiled the smart-contract using hardhat!
Here please mention some common errors which can arise during the whole process till now, and add some common troubleshooting points take reference from **[HERE](https://learn.figment.io/other/tutorial-guidelines/sample-tutorial-structure)**

2021-05-18 13:59 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +If the nodes started successfully, the console should look similar to what you see below:
If nodes are not started successfully then what's next to troubleshoot that part? I just mean you should take an error-driven approach and mention the common errors and steps to troubleshoot them.

2021-05-18 13:59 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +## Summary
- Change it to the "Conclusion" section that summarizes what was learned, reinforces key points and also congratulates the learner. 
- (Optional) Include a What's Next section pointing to good follow up tutorials or other resources (projects, articles, etc)
- (Optional) Include an "About The Author" section at the end. Your bio should include your Github handle (which will have your name, website, etc) and a link to your Figment Forum profile (so users can contact/tag you on Forum for help and questions).
- References section must be present if you have taken any help in writing this tutorial from other documents, GitHub repos and other tutorials. Credit sources by adding their name and a link to the document when possible (if it is not a digital document, include an ISBN or other means of reference).

2021-05-18 14:00 UTC, yash-sharma1 requested changes

2021-05-18 14:00 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +<sub>Contributed By [BREATHE BINARY OÜ](https://github.com/breathebinary)</sub>
What does this mean here Contributed By?

2021-05-18 15:27 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +
I think the setup of Avash will have enough content to stand on its own and it could be useful for multiple tutorials. I had this in mind. What do you say about making it a completely new tutorial and we mention it as a prerequisite here?

2021-05-18 15:29 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +<sub>Contributed By [BREATHE BINARY OÜ](https://github.com/breathebinary)</sub>
It's more like what goes into the "About the author" section as mentioned in the guidelines. I just made my organization stand out rather than me.

2021-05-18 15:32 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +If the nodes started successfully, the console should look similar to what you see below:
Again, considering this makes the tutorial a little too bulky and takes the concentration of the learner away from the primary objective in my opinion. As I mentioned above, this could be a part of another tutorial about the proper installation of avash. If that is not advisable I'll try to put in more information here.

2021-05-18 15:33 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +If you managed to get this far without any errors, you've successfully compiled the smart-contract using hardhat!
https://github.com/figment-networks/datahub-learn/pull/107#discussion_r634500634

2021-05-18 17:28 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +
We can have Avash setup here, as we are trying to keep learners focused on one tutorial at a time whereas at the end of the tutorial you can mention Avash Tutorial link for reference. Also sometimes tutorials get updated and some removed might be link can be broken if the tutorial moved to some other category and at that time it can affect this tutorial as well so having a separate section for this would be great. We can remove it from the pre-requisite section in that case.

2021-05-18 17:29 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +If the nodes started successfully, the console should look similar to what you see below:
Yeah, more/extra information would be a plus.

2021-05-18 17:32 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +<sub>Contributed By [BREATHE BINARY OÜ](https://github.com/breathebinary)</sub>
Yes, it should be in "About The Author" If you're writing this tutorial on your behalf so, we prefer to have only you as an author and you can mention your organization in your bio as you work there if you want.

2021-05-18 17:55 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +
Ummm, I didn't really get you. So, you want the installation of avash to be separate or you want it here? If it's part of this tutorial, again we've to have a repetition of the same for truffle, here, and for waffle. And for your info, the usage of avash (configuration of the nodes rather) has changed a bit and this has already broken https://learn.figment.io/network-documentation/avalanche/tutorials/using-truffle-with-the-avalanche-c-chain. Fixing this was on my list after this PR gets accepted.

2021-05-18 18:00 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +
I'd prefer to remove the section "Setup a local Avalanche network using Avash"  completely from here and to write it as a new tutorial and mentioning it as a prerequisite for this tutorial.

2021-05-20 10:49 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +
I mean to have an explanation of the installation of avash here in the tutorial.
Also if you can create it as separate and link to it will also work. 
As you mentioned existing one is already broken that's my concern to have a separate installation for the same.

2021-05-20 19:50 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +
Yeah, if we make it at least, when it's broken, we only have to fix it in one place.  Also, breaking changes happen only in one place and the rest of the things stay intact. I'll try to make sure that I keep my contributions up-to-date and to respond quickly when something's broken.

2021-05-21 11:35 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +
Sure, sounds good

2021-05-23 10:50 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +<sub>Contributed By [BREATHE BINARY OÜ](https://github.com/breathebinary)</sub>
I've removed contributed by and added "About the Author section".

2021-05-23 10:54 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +[Hardhat](https://hardhat.org) is a development environment to compile, deploy, test, and debug your Ethereum software. It helps developers manage and automate the recurring tasks that are inherent t
It has been updated with a new introduction written by me.

2021-05-23 10:56 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +## Prerequisites
I've added a new Prerequisites section mentioning avash installation and moved the relevant content to the requirements section.

2021-05-23 10:58 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +
Creating a new PR for Avash Installation.

2021-05-23 10:59 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +If the nodes started successfully, the console should look similar to what you see below:
A lot of information has been added to "Avash Installation" regarding things that could go wrong.

2021-05-23 11:02 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +If you managed to get this far without any errors, you've successfully compiled the smart-contract using hardhat!
I don't see any issues that could come up in this regard because it's a simple smart-contract for which code is being provided. So, the compilation should succeed. If I come across some issues that could come up, later down the road or if someone reports anything, I'll make sure to update the information here.

2021-05-23 11:26 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +
https://github.com/figment-networks/datahub-learn/pull/114

2021-05-26 13:50 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +888 888 888 888 888
It wasn't supposed to be change "Hardhat"

2021-05-26 13:57 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +888 888 888 888 888
It has been restored to previous state

2021-05-26 16:39 UTC, pyr0gan reviewed
Thank you for adding the explicit reference to the other tutorial, however I would like to suggest a slightly different approach to the explanation: 

"Ensure that the local Avalanche test blockchain outlined in the `Setup a local Avalanche network using Avash` tutorial is running properly. Follow that other tutorial to completion, however do not exit the Avash console after running the Lua script. Leave it running & in a separate terminal window, follow these instructions."

Alternatively, in the Avash tutorial, re-word the portion about exiting the Avash console (because this will shut down the running nodes).

Where we declare the constant Storage using the HardHat Runtime Environment, and it returns an undefined value in the HardHat console: it would also be a good idea to specify that this behaviour does not mean that the command was a failure. The resulting object held in the Storage constant can be shown with console.log. It may be a good idea to demonstrate this with a couple of concise screenshots. We do not wish to overwhelm readers with terminal output.

Your other changes are good. As an aside, it may be beneficial to state at the beginning of the tutorial that this is much more difficult to accomplish on a WSL installation as compared to Linux or macOS, however this is not a necessity.

Please review and adjust, and I will take another look at approval 👍🏻

2021-05-26 17:37 UTC, kevin-madhu commented
> Thank you for adding the explicit reference to the other tutorial, however I would like to suggest a slightly different approach to the explanation:
> 
> "Ensure that the local Avalanche test blockchain outlined in the `Setup a local Avalanche network using Avash` tutorial is running properly. Follow that other tutorial to completion, however do not exit the Avash console after running the Lua script. Leave it running & in a separate terminal window, follow these instructions."
> 
> Alternatively, in the Avash tutorial, re-word the portion about exiting the Avash console (because this will shut down the running nodes).
> 
> Where we declare the constant Storage using the HardHat Runtime Environment, and it returns an undefined value in the HardHat console: it would also be a good idea to specify that this behaviour does not mean that the command was a failure. The resulting object held in the Storage constant can be shown with console.log. It may be a good idea to demonstrate this with a couple of concise screenshots. We do not wish to overwhelm readers with terminal output.
> 
> Your other changes are good. As an aside, it may be beneficial to state at the beginning of the tutorial that this is much more difficult to accomplish on a WSL installation as compared to Linux or macOS, however this is not a necessity.
> 
> Please review and adjust, and I will take another look at approval 👍🏻

It's been done. Please check.

2021-05-26 22:34 UTC, pyr0gan approved these changes

2021-05-27 00:22 UTC, pyr0gan approved these changes

2021-05-28 21:17 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +[Hardhat](https://hardhat.org) is a suite of tools that together provides us with a development environment that helps developers to easily manage and automate the tasks around building smart contrac
> In this tutorial, we learn how Hardhat can be used with Avalanche C-Chain, which is an instance of the EVM (Ethereum Virtual Machine).

I would also explain why this is important (i guess because it allows for compatibility between Solidity smart contracts and the C Chain?)

2021-05-28 21:19 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +As a result, you must see a newly created directory named `avalanche-hardhat-tutorial` with a file `package.json` inside it:
"You should see a newly created directory named..."

2021-05-28 21:19 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +```text
`json` instead of `text`?

2021-05-28 21:24 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +```
can you fix the indentation? this is what it's rendered as:

<img width="620" alt="Screen Shot 2021-05-28 at 5 24 19 PM" src="https://user-images.githubusercontent.com/206753/120043209-8a0f5080-bfd9-11eb-86a0-1134de9a3261.png">

2021-05-28 21:25 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +## Adding avash network configuration to hardhat
Capitalize Avash? can you check the rest of the tutorial for this?

2021-05-28 21:25 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +Now, inorder for our hardhat project to communicate with our local Avalanche network bootstrapped by avash, we need to provide hardhat with appropriate network configuration. For that, add the follow
"inorder" => "in order"

can you run a grammar and spelling check before resubmitting please?

2021-05-28 21:25 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +Now, inorder for our hardhat project to communicate with our local Avalanche network bootstrapped by avash, we need to provide hardhat with appropriate network configuration. For that, add the follow
capitalize hardhat here and everywhere else

2021-05-28 21:30 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +```
We don't need to show only the object inside `module.exports` and then the whole thing again, it's repetitive. Can you rewrite this with only code block?

Also can you explain the fields:

- What are those account addresses?
- What is the `chainId`?
- What is the `url`?
- Why this `gasPrice` exactly?

2021-05-28 21:30 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +## Adding and compiling a smart-contract
There's no hyphen at "smart-contract"

Please proofread the PR!

2021-05-28 21:32 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +`Storage` is a solidity smart contract that lets us write a number to the blockchain via the `store` function and then read the number back from the blockchain via the `retrieve` function.
So this smart contract doesn't really do anything interesting right? It's just to test with basic functionnalities?

If so please explain this? So far there's a lot of copy and pasting but we need to explain more why we are doing what we're doing

2021-05-28 21:32 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +For the rest of the tutorial, we're going to use the hardhat console to deploy and interact with our smart-contract. To successfully use the hardhat console for our purposes, we need to install a cou
"smart contract" here and everywhere else

2021-05-28 21:33 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +npm install --save-dev @nomiclabs/hardhat-waffle 'ethereum-waffle@^3.0.0' @nomiclabs/hardhat-ethers 'ethers@^5.0.0'
the second command includes the first one

also why are some in quotes and not others?

2021-05-28 21:34 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +To deploy our smart-contract and to interact with it, we're gonna be using an interactive JavaScript console provided by hardhat, which is called hardhat console. Hardhat console is geared more towar
"more" than what?

2021-05-28 21:35 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +Here, `undefined` being printed does not mean that the instruction we executed has failed. Instead, it's `undefined` because we stored the return value into the Storage constant and there's nothing t
love this explanation 👍🏼

2021-05-28 21:35 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +const Storage = await hre.ethers.getContractFactory("Storage");
we don't usually capitalize variables in Javascript

=> `storage`

2021-05-28 21:36 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +![](../../../.gitbook/assets/storage-console-log.png)
this image is broken

2021-05-28 21:36 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +const storage = await Storage.deploy();
this should be a different variable name than above.

2021-05-28 21:37 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +```text
why `text`?

2021-05-28 21:37 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +```
what language? "json"?

2021-05-28 21:38 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +## Conclusion
What's missing here is a section where you take the user to a block explorer on the C Chain, find the contract and show them that the value they have set is stored on the blockchain, not only locally

2021-05-28 21:38 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +So, keep learning and keep building and I'm sure you're on your way to building something great! Good luck!
❤️

2021-05-28 21:38 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +If you had any difficulties following this tutorial or simply want to discuss Avalanche tech with us you can join [**our community**](https://discord.gg/fszyM7K) today!
Feel free to add a short "About The Author" section.

2021-05-29 04:43 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +`Storage` is a solidity smart contract that lets us write a number to the blockchain via the `store` function and then read the number back from the blockchain via the `retrieve` function.
What you don't realize is that I did not start writing these to be a one-time thing, they get merged and I abandon them - I had enhancement plans as well as plans to keep maintaining the ones I write. For example, I submitted a proposal for writing an ERC20 token contract yesterday and I intended to list it as a prerequisite here so that I could remove this useless smart contract being used here and then use something the learner has learned about and then capitalize on that in this tutorial + the ones I mentioned in the proposal. So, the more time I spend here explaining this contract which has no real value, the more time I'm wasting explaining something I've already planned to remove in the near future - is something I don't intend to do.
 
But the way this is progressing, I'm stuck here in an endless loop of improvements rather than being able to execute my plans and to make actual progress (IMHO). Every time I make improvements as per instructions here and request for a review, I'm being thrown a new set of issues.

This is not me becoming rude, I've so far responded to all the proposed changes very quickly.

2021-05-29 04:53 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +`Storage` is a solidity smart contract that lets us write a number to the blockchain via the `store` function and then read the number back from the blockchain via the `retrieve` function.
I understand and appreciate all the effort that has gone into this. After all these changes are made, it'll be "near-perfect". I know my opinions don't hold value against the policies of the organization, but with the plans, I had in mind, my intended approach was to get the whole pathway I had in mind published while maintaining a list of improvements to be checked off one by one once the whole thing is live with an acceptable level of quality,

2021-05-29 05:12 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +Please make sure that you have completed the tutorials:
This is something that's usually done in tutorials or documents, using plural when there's a list of items, even if there's only one item in the list.

If you still want me to remove plural, I'll remove it.

2021-05-30 05:55 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +As a result, you must see a newly created directory named `avalanche-hardhat-tutorial` with a file `package.json` inside it:
Changed

2021-05-30 05:56 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +```text
Changed

2021-05-30 05:56 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +```
Fixed

2021-05-30 06:02 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +## Adding avash network configuration to hardhat
Done

2021-05-30 06:02 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +Now, inorder for our hardhat project to communicate with our local Avalanche network bootstrapped by avash, we need to provide hardhat with appropriate network configuration. For that, add the follow
Done

2021-05-30 06:05 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +## Adding and compiling a smart-contract
Okay. Changed.

2021-05-30 06:05 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +For the rest of the tutorial, we're going to use the hardhat console to deploy and interact with our smart-contract. To successfully use the hardhat console for our purposes, we need to install a cou
Changed

2021-05-30 06:08 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +Here, `undefined` being printed does not mean that the instruction we executed has failed. Instead, it's `undefined` because we stored the return value into the Storage constant and there's nothing t
Thanks. Providing an explanation here was @pyr0gan's suggestion.

2021-05-30 06:10 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +const Storage = await hre.ethers.getContractFactory("Storage");
// We require the Hardhat Runtime Environment explicitly here. This is optional 
// but useful for running the script in a standalone fashion through `node <script>`.
//
// When running the script with `hardhat run <script>` you'll find the Hardhat
// Runtime Environment's members available in the global scope.
const hre = require("hardhat");

async function main() {
  // Hardhat always runs the compile task when running scripts with its command
  // line interface.
  //
  // If this script is run directly using `node` you may want to call compile 
  // manually to make sure everything is compiled
  // await hre.run('compile');

  // We get the contract to deploy
  const Greeter = await hre.ethers.getContractFactory("Greeter");
  const greeter = await Greeter.deploy("Hello, Hardhat!");

  await greeter.deployed();

  console.log("Greeter deployed to:", greeter.address);
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main()
  .then(() => process.exit(0))
  .catch(error => {
    console.error(error);
    process.exit(1);
  });

2021-05-30 06:16 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +const Storage = await hre.ethers.getContractFactory("Storage");
You can see above the example provided by Hardhat in their official quickstart guide (https://hardhat.org/getting-started/#deploying-your-contracts).

```javascript
  const Greeter = await hre.ethers.getContractFactory("Greeter");
```
As you can see in the line above, they've capitalized the variable Greeter because they treat it just like a "class" from which "objects" (deployed instances) are being created.

2021-05-30 06:18 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +const storage = await Storage.deploy();
Please refer - https://hardhat.org/getting-started/#deploying-your-contracts as I've mentioned above. I prefer to keep code in sync with this official doc because learners who're familiar with the official doc will immediately recognize this pattern.

2021-05-30 06:23 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +![](../../../.gitbook/assets/storage-console-log.png)
No, it's not. Please check again. 

![Screenshot from 2021-05-30 11-51-00](https://user-images.githubusercontent.com/349987/120094384-a3c9a880-c13d-11eb-8084-90596f3632db.png)

2021-05-30 06:26 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +## Conclusion
Won't be going forward with this right now. I've got more plans. Firstly, I wanna swap out the Storage contract for another useful smart contract.

2021-05-30 06:32 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +## Conclusion
And for that, please refer to the creation of a new tutorial for the ERC-20 token smart-contract creation proposal I've sent the team already. I'm not ready to put in a significant amount of time into this tutorial before it gets merged with the content which I've written so far.

2021-05-30 06:33 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +So, keep learning and keep building and I'm sure you're on your way to building something great! Good luck!
Thanks

2021-05-30 06:39 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +If you had any difficulties following this tutorial or simply want to discuss Avalanche tech with us you can join [**our community**](https://discord.gg/fszyM7K) today!
It's okay. Currently, as per figment.io guidelines, I don't find the "About the Author" section useful (IMHO). Maybe it makes more sense when I have a  README.md in my Github profile which I currently do not have.

And if you check the initial commits I made, I started out with: "- Contributed by Breathe Binary". What I actually wanted was to give some kind of visibility to my newly founded organization. It's from the organization's fork that I'm making this PR.

So, it just doesn't serve my objective.

2021-05-30 07:23 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +npm install --save-dev @nomiclabs/hardhat-waffle 'ethereum-waffle@^3.0.0' @nomiclabs/hardhat-ethers 'ethers@^5.0.0'
https://www.npmjs.com/package/@nomiclabs/hardhat-ethers
https://www.npmjs.com/package/@nomiclabs/hardhat-waffle

Please see the installation section in both of them. As you can notice quotes were used in places where they used special characters "^", "@", "." and 'ethers@^5.0.0' is a dependency for both. I did not remove 'ethers@^5.0.0' from the second command simply because I wanted the learner to realize that hardhat-waffle also depends on "ethers".

I prefer to keep them this way, if you want me to change it, please share these 2 commands the way you see fit and I'll modify them.

2021-05-30 07:32 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +`Storage` is a solidity smart contract that lets us write a number to the blockchain via the `store` function and then read the number back from the blockchain via the `retrieve` function.
This is from the official documentation/figment clone of the same doc - https://learn.figment.io/network-documentation/avalanche/tutorials/using-truffle-with-the-avalanche-c-chain. I don't intend to add more information here because it'll be a waste of time considering that I've got plans to swap out this Storage contract for an ERC-20 token smart contract (which will have detailed and clear explanations in a tutorial of its own) in the near future and will also be useful rather than using this contract which doesn't have any value. I've sent a proposal for the same a couple of days ago to the team.

2021-05-30 07:35 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +To deploy our smart-contract and to interact with it, we're gonna be using an interactive JavaScript console provided by hardhat, which is called hardhat console. Hardhat console is geared more towar
Updated.

2021-05-30 07:47 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +```text
Because it's like a console.log - doesn't necessarily have a return type. Also, I don't want the user to be able to copy it (if text doesn't permit that).

2021-05-30 08:00 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +```
It's not properly formatted as JSON and so, I'm using text. These are like console.log outputs that do not necessarily need a specific format.

2021-05-30 08:09 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +Now, inorder for our hardhat project to communicate with our local Avalanche network bootstrapped by avash, we need to provide hardhat with appropriate network configuration. For that, add the follow
Done. I used Grammarly.

2021-05-30 11:10 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +[Hardhat](https://hardhat.org) is a suite of tools that together provides us with a development environment that helps developers to easily manage and automate the tasks around building smart contrac
Done. Please check. @pyr0gan Any suggestion to rephrase anything like how you helped me earlier would be welcome :)

2021-05-31 05:54 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +```
Added explanations

2021-05-31 05:55 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +Please make sure that you have completed the tutorials:
It could also be "tutorial(s):"

2021-05-31 07:38 UTC, kevin-madhu commented
> Great tutorial @kevin-madhu !
> 
> Some changes but this is really awesome, thanks

Thanks :)

2021-06-14 17:27 UTC, pyr0gan reviewed
Very nearly there! Just a few small fixes and we should be able to merge this tutorial! 🚀

2021-06-14 17:27 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +## Introduction
Please make all top level headings H1. Introduction, Prerequisites, etc.. 😄

2021-06-14 17:27 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +* 43112 is the id for the chain created by Avash in it's local Avalanche network. This is hardcoded in Avash.
> 43112 is the id for the chain created by Avash in its local Avalanche network. This value is hardcoded in Avash.

2021-06-14 17:27 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +* The list of accounts we provided above are some randonly generated addresses on the network. When it comes to Avash, unlike mainnet and fuji testnet, these addresses come loaded with lots AVAX and
> The list of accounts we provided above are some randomly generated addresses on the network. When it comes to Avash, unlike mainnet and Fuji testnet, these developer addresses come loaded with lots AVAX and so we don't need to fund them from a faucet.

2021-06-15 03:49 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +## Introduction
Changed

2021-06-15 03:54 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +* 43112 is the id for the chain created by Avash in it's local Avalanche network. This is hardcoded in Avash.
Changed

2021-06-15 03:54 UTC, kevin-madhu commented on network-documentation/avalanche/tutorials/using-hardhat-with-the-avalanche-c-chain.md
> +* The list of accounts we provided above are some randonly generated addresses on the network. When it comes to Avash, unlike mainnet and fuji testnet, these addresses come loaded with lots AVAX and
Changed

2021-06-15 03:57 UTC, kevin-madhu commented
> Very nearly there, @kevin-madhu ! Just a few small fixes and we should be able to merge this tutorial

Cool! +1 @pyr0gan I've incorporated all the proposed changes by you.

2021-06-15 22:00 UTC, merged