Advanced evoting on avalanche using ReactJS
figment-networks/datahub-learn pull request #115
Opened 2021-05-26 13:46 UTC by rajranjan0608

# Description*

This is an advanced version of the e-voting tutorial on the Avalanche network. In this version, we will be using ReactJS as its client-side instead of jQuery.

Fixes # (issue)

## Type of change*

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## This PR created for* - 

- [x] Figment Learn Docs (Pathway, Existing Tutorials, New Tutorial etc.) changes/updates/fixes

# Checklist*:

- [x] I updated the `SUMMARY.md` file (FYI, It's needed only when you're creating a new file like submitting a new tutorial, pathway section)
- [x] I created one tutorial for this PR (one PR <=> one tutorial)
- [x] I checked and accept that my PR for a new tutorial follows the [**Tutorial Guidelines**](https://learn.figment.io/other/tutorial-guidelines) of this project
- [x] I checked and read the contribution guide before making this PR [**HERE**](https://learn.figment.io/figment-learn/contribute)  
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Note - Above points marked with * are mandatory to fill :)

2021-05-27 14:11 UTC, yash-sharma1 requested changes

2021-05-27 14:11 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +### **Add .env file**
Indicate learners that in which directory they have to save `.env` file when I saved in the root folder of the project it was throwing error and when moved it to the src folder it worked fine

2021-05-27 14:11 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +## Prerequisites
Prerequisties can be bullet points, for Eg. - 
- You should have an account on DataHub (link)
- Having a familiarity with Avalanche's architecture is a plus
- You have followed the tutorial on Making a basic e-voting DApp on Avalanche's Fuji C-Chain, though for the sake of completeness, we will be covering everything from start.

2021-05-27 14:21 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +Fund your account using the the faucet link [https://faucet.avax-test.network/](https://faucet.avax-test.network/) and pasting your Fuji's C-Chain address in the input field. You'll need to send at l
"You'll need to send at least `135422040` nAVAX to the account to cover the cost of contract deployments." Please add a point that what is nAVAX and how much nAVAX equals to 1 AVAX

2021-05-27 22:11 UTC, guillaumegaluz requested changes
@rajranjan0608, I reviewed up until the contract deployment. Have a look at the feedback. I will review the React part a bit later sorry.

2021-05-27 22:11 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +const APIKEY = process.env.APIKEY;
Let's rename this to `DATAHUB_API_KEY`

2021-05-27 22:11 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +const APIKEY = process.env.APIKEY;
i know the first one is lowercase so that it allows you to do `{mnemonic}` instead of `{mnemonic: mnemonic}` below. But it's better to be explicit. I would do:

```javascript
const MNEMONIC = process.env.MNEMONIC;
...
return new HDWalletProvider({mnemonic: MNEMONIC, ... })
```

2021-05-27 22:11 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +Fund your account using the faucet link [https://faucet.avax-test.network/](https://faucet.avax-test.network/) and pasting your Fuji's C-Chain address in the input field. You'll need to send at least
> pasting your Fuji's C-Chain address in the input field.

Can you explain how a learner can find this address?

2021-05-27 22:11 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +Fund your account using the faucet link [https://faucet.avax-test.network/](https://faucet.avax-test.network/) and pasting your Fuji's C-Chain address in the input field. You'll need to send at least
> Here `nAVAX` refers nano-AVAX i.e. billionth of an `AVAX` or simply 1 `nAVAX` = (1/1000,000,000) `AVAX`. Though funding through faucet would give you enough `AVAX` to run multiple deployments and transactions on the network.

This is a good candidate for a [Gitbook hint](https://docs.gitbook.com/editing-content/markdown#hints-and-callouts
)

2021-05-28 05:29 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +
I was considering basic e-voting as its previous tutorial.

2021-05-28 05:34 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +Now remove the contents of `src` and `public` folder, in order to make our own.
There are lots of files, that come with `create-react-app` which are not required, and could confuse beginners. Initiating with `create-react-app`, would help in basic installation of required modules. Learners would then only need to put code inside `src` and `public` directory.

2021-05-28 05:35 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +
Ok. That would be better.

2021-05-28 05:45 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +`MainContract.sol` is the main entry point of our e-voting DApp. It will maintain the number of election contracts deployed, their address on the network and will also help in deploying them. We have
Yes, for creating election, one has to call createElection( ) function of the MainContract.sol

2021-05-28 05:46 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +2. We have made a `createElection()` function which will be used to deploy our `Election` smart contract. This function takes `name` and `description` as a single array named `_nda` in the first argu
I have explained, that name and description are taken as a single array named _nda[ ]

2021-05-28 05:47 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +const Election = artifacts.require("Election");
I have to remove that.

2021-05-28 19:48 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +```
Mnemonic would need quotes because it is more than one word.

2021-05-28 19:54 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +class  App  extends  React.Component {
Actually, this would not be possible because this entire tutorial is using class components and changing them to functional components is not a good idea. Though we may make future tutorials with functional components, let's leave this one with class components.

2021-05-28 21:51 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +* Truffle, which you can install with `npm install -g truffle`
You resolved this but did not add a link to Truffle

2021-05-28 21:51 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +export  default  App;
I don't think the indentation has been fixed. Reopening this comment.

2021-05-28 21:51 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +> Never share or commit your `.env` file. It contains your credentials like `mnemonics` and `API` key. Therefore, it is advised to add `.env` to your `.gitignore` file.
Can you use a Gitbook tip for this?

2021-05-28 21:51 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +```text
still shows text. reopening

2021-05-28 21:51 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +var Election = props => (
This is a functional component! so you are ok writing them ;)

2021-05-28 21:51 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +function VoteModal(props) {
another functional component!!

2021-05-28 21:51 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +In the above component, i.e. `Active.js` we have used a component called `VoteModal` which will be used to open up a modal containing candidate details and a button to cast the vote to the selected c
files that have JSX should be `.jsx`

2021-05-28 21:51 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +```
Can you fix all the comments to be:

```jsx
{/* Comment */}
```

(Look at the spaces)

2021-05-28 21:51 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +* Now go to the `root` directory of the project, i.e. `advanced-evoting` directory, and run the command `npm start`. The ReactJS server would start automatically.
I don't think this is not necessary actually. Takes a lot of space and doesn't provide a lot of value

2021-05-28 21:51 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +The dapp which we built just now is a somehow advanced e-voting application, as now we can make new elections, give the title and description, vote them separately. But I would recommend you add few
Can you look all over the tutorial and change "dapp" to "dApp"?

2021-05-28 21:51 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +You have successfully built a full-fledged e-voting `dApp` with advanced features like creating custom elections, voting in them and deployed the smart contract on the `Fuji` test network using `Truf
no need to make "dApp" into a code snippet

2021-05-28 21:54 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +class  App  extends  React.Component {
Ok @rajranjan0608! We have a deal. Class component ok for this one, but next one => 100% functional (which is the state of the art)

🤝

2021-05-29 03:40 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +class  App  extends  React.Component {
Ok 😅

2021-05-29 07:47 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +export  default  App;
Already fixed the indentations but couldn't understand why isn't it visible in yours. 

![ ](https://imgur.com/At91yau.png)

2021-05-29 07:47 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +### **Let's understand this smart contract**
I do not understand here, what to change.

2021-05-29 07:51 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +var Election = props => (
Yes, I could write functional components :smile: Here `Election` is a functional component, but if you go down in the same file you could the class component i.e. `Active`, which the main component in this file.

2021-05-29 07:52 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +function VoteModal(props) {
This was required because I have to use Modal from Rimble UI, which works smoothly with the functional component.

2021-05-29 07:55 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +In the above component, i.e. `Active.js` we have used a component called `VoteModal` which will be used to open up a modal containing candidate details and a button to cast the vote to the selected c
Yeah, but these extensions could be used interchangeably for **ReactJS**. For simplicity, I kept `.js` extension and let the transpiler/bundler decide the type of file contents are inside.

2021-05-31 13:54 UTC, yash-sharma1 requested changes

2021-05-31 13:54 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +* You've created an [Avalanche DataHub](https://datahub.figment.io/sign_up?service=avalanche) account.
Here in first point it should be only - 
- You've created an account on DataHub
OR
- You should have an account on DataHub

2021-05-31 14:06 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +* You've created an [Avalanche DataHub](https://datahub.figment.io/sign_up?service=avalanche) account.
Shouldn't we provide a link to sign up?

2021-05-31 14:14 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +* You've created an [Avalanche DataHub](https://datahub.figment.io/sign_up?service=avalanche) account.
@yash-sharma1 I have updated the prerequisites section.

2021-05-31 23:28 UTC, pyr0gan requested changes
Please go over my suggestions and make the appropriate edits. We are definitely getting closer to a final draft.

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +The information and ABI of the deployed contract are present in the `src//build/contract` directory as `Election.json`. Information like contract address, network info etc. could be found here.
Remove the extra / in the path.

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +### **Building user interface for interacting with the blockchain**
Should be a 2nd level Heading. Also consider renaming it to "Building the UI" or similar.

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +* So go to the `src` directory using the command `cd src`
Depending on which directory a user is in when running this command, it may not work. Please be more specific on this point, or simply say "Navigate to the project `src` directory".

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +And put the following block of code inside the `init()` function of `App.js`.
> Paste the following code inside the `init()` function of `App.js`.

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +* Now let's make a component that will create new elections using our deployed smart contract. So, make a file named `CreateElection.js` in the `src` directory and put the following code inside it. T
Better to say "The code is commented to draw attention to the important parts."

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +```javascript
Please fix the formatting and indentation of this code block.

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +Make a file named `Active.js` in the `src` directory which will display the list of all deployed (active) elections on the website. In the file, put the following code inside the file. Please refer t
See previous comments on file creation.

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +```javascript
Please fix the formatting and indentation of this code block.

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +            // account address of the voter
Please continue to use proper capitalization on comments 😄 

> // Account address of the voter

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +In the above component, i.e. `Active.js` we have used a component called `VoteModal` which will be used to open up a modal containing candidate details and a button to cast the vote to the selected c
> In the above component `Active.js`, we have used a component called `VoteModal` which contains the candidate details and a button to cast a vote. Now we will make this component available by creating a file named `VoteModal.js` inside the `src` directory. Once created, put the following code inside it:

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +```javascript
Please fix the formatting and indentation of this code block.

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +import { Box, Flex, Modal, Button, Text, Card, Radio, Field, Loader} from "rimble-ui";
> import { Box, Flex, Modal, Button, Text, Card, Radio, Field, Loader } from "rimble-ui";

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +* **Load components** - Inside the `<div>` tag of `return()` function, replace the sample text with the the code of the following components.
Please make it clearer where the `<div>` tag you are referring to is located.

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +* Visit [http://localhost:3000](http://localhost:3000) to interact with built dApp.
> Visit [http://localhost:3000](http://localhost:3000) in a browser to interact with the dApp frontend.

Also, it is not necessary to use bullet points for the text between code blocks.

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +* Don't forget to set up Metamask with `Fuji` testnet and also fund the account with Fuji c-chain test tokens to vote. Please refer to this tutorial on [Connecting Datahub to Metamask](https://learn.
The backticks around Fuji are not necessary. Also, C-Chain should be capitalized.

Generally, it would be best to rewrite this to actually include the instructions you want readers to perform. We want the tutorial to be as standalone as possible 😄

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +You have successfully built a full-fledged e-voting dApp with advanced features like creating custom elections, voting in them and deployed the smart contract on the `Fuji` test network using `Truffl
Truffle, Trufflesuite, Truffle Suite .. Please be consistent with naming throughout the document. The backticks are unnecessary for formatting.

2021-05-31 23:28 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +The dApp which we built just now is a somehow advanced e-voting application, as now we can make new elections, give the title and description, vote them separately. But I would recommend you add few
Please rewrite this section. Be clear about what additions could be made to the code, or provide links to more resources to help learners understand the concepts in the tutorial. How will they proceed once they have performed this tutorial?

2021-06-01 09:30 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +Have a look at the project structure. As you can see, there are lots of files in our project. To clear the clutter, let us first remove the unwanted files from `src` and `public` directory.
There are lots of files like logos, stylesheets etc. that are not required, that is why removing them would make it easier to keep track of the project.

2021-06-01 09:31 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +    <title>Advanced Elections</title>
No :sweat_smile:

2021-06-01 09:34 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +**Storing candidate details** - Candidate details would be stored in mapping between an unsigned integer to the `Candidate` structure. `Candidate` structure would consist of fields like `id`, `name`
These are explanations of the code snippets and should be in a point wise structure.

2021-06-01 14:25 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +Have a look at the project structure. As you can see, there are lots of files in our project. To clear the clutter, let us first remove the unwanted files from `src` and `public` directory.
> There are lots of files like logos, stylesheets etc. that are not required, that is why removing them would make it easier to keep track of the project.

This is not negotiable, I am asking you specifically to leave the generated project scaffolding intact. I'm not approving the tutorial with these instructions in it, is what I'm saying. 

As a personal preference, if you find the default CRA scaffolding to be too much and you really want a squeaky clean file and directory structure, you can make a [custom template](https://create-react-app.dev/docs/custom-templates/) and host it on GitHub 😄

2021-06-01 17:11 UTC, pyr0gan reviewed
A few more issues to look at 😄

2021-06-01 17:11 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +You have successfully built a full-fledged e-voting dApp with advanced features like creating custom elections, voting in them and deployed the smart contract on the Fuji test network using Truffle S
Mixing up "you" and "we" is making this look a little strange. I was hoping you'd catch my drift with all the suggested edits - we're aiming for more inclusive language. You/we may want to go over the entire document again to keep the language consistent. 

Whether "learnt" is acceptable to a majority of the English speaking world is not for me to say. However, since we are also aiming to make our text as translatable as possible, please prefer the "learned" form. 

![Screen Shot 2021-06-01 at 11 06 47 AM](https://user-images.githubusercontent.com/2707197/120363607-92ada280-c2c9-11eb-9559-c408fba684f1.png)

2021-06-01 19:14 UTC, pyr0gan reviewed
Updated a few comments.

2021-06-02 19:08 UTC, rajranjan0608 commented
@pyr0gan The code looks indented now. Please have a look. 
1. Removed the instructions to clear the clutter
2. Using the newer version of Solidity, and hence no experimental features (ABIEncoder).

2021-06-02 20:30 UTC, pyr0gan reviewed
The section headings still need to be fixed to make sense for the Table of Contents. Thank you for your work on the changes so far. Almost there!

2021-06-02 20:30 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
>  cd /path/to/directory
After thinking about it, I believe it might be best to say `cd ~` as that will bring Linux and macOS users to their home directory. We could even add a tab to the gitbook code block and have separate commands for Linux/macOS and Windows. I tried it on GitBook to test it out. Let me know what you think :

> Open a terminal and navigate to the directory where we will create the application. Usually, this will be inside our user home directory but can be located wherever is practical. On most Linux distributions this will change into /home/<username> . On macOS it will be /Users/<username>. On Windows the user directories are located in C:\Users\<username>.

![Screen Shot 2021-06-02 at 2 25 54 PM](https://user-images.githubusercontent.com/2707197/120547511-75063900-c3ae-11eb-9e08-82d34f2b8d86.png)

2021-06-03 07:53 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +### **Let's understand this smart contract**
Yes, that's why I have used triple hash marks. Since it is part of the above section, it will be used as a sub-heading.

2021-06-03 07:54 UTC, rajranjan0608 commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
> +  }
Yes :sweat_smile:

2021-06-07 19:28 UTC, rajranjan0608 commented
@yash-sharma1, @guillaumegaluz and @pyr0gan, Please review my latest commit. I have updated the headings and other things as per the review. Thank you.

2021-06-07 21:02 UTC, pyr0gan reviewed
Just a few small touchups. Thanks for all your work on making this tutorial easy to follow, as it is quite code-heavy.

2021-06-07 21:02 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/advanced-evoting-avalanche-reactjs.md
>  `App.js` is the entry point of any React application. Therefore we need to update `App.js` regularly with the components which we want to show in our application. As we move further and build compone
> `App.js` is the entry point of our React application. Therefore, we will need to update `App.js` with the components which we want to show in our application. As we move ahead and build components, we will update `App.js` and import the components so that we can make use of their functionality.

2021-06-07 21:04 UTC, pyr0gan approved these changes

2021-06-09 17:05 UTC, pyr0gan approved these changes
👍🏻

2021-06-09 17:05 UTC, merged