NEAR: How to write and deploy smart contract in RUST
figment-networks/datahub-learn pull request #116
Opened 2021-05-26 15:50 UTC by nikbhintade

# Description*

Tutorial: How to write and deploy smart contracts in rust.

This tutorial for basic concepts of rust and near SDK. The tutorial covers the following: 
- setting up the development environment
- how to structure the smart contract
- using functions from near SDK
- testing of smart contract 
- deployment of the smart contract on the near testnet

Fixes # (issue)

## Type of change*

Important - Please delete options that are not relevant to your PR.
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## This PR created for* - 
- [x] Figment Learn Docs (Pathway, Existing Tutorials, New Tutorial etc.) changes/updates/fixes

# How Has This Been Tested? (If Applicable)

Yes

**Test Configuration*** (If Applicable):
* OS: unbuntu 20.04 LTS (WSL)
* Network/Protocol: Near
* SDK: near-sdk@3.1.0

# Checklist*:

- [x] I updated the `SUMMARY.md` file (FYI, It's needed only when you're creating a new file like submitting a new tutorial, pathway section)
- [x] I created one tutorial for this PR (one PR <=> one tutorial)
- [x] I checked and accept that my PR for a new tutorial follows the [**Tutorial Guidelines**](https://learn.figment.io/other/tutorial-guidelines) of this project
- [x] I checked and read the contribution guide before making this PR [**HERE**](https://learn.figment.io/figment-learn/contribute)  
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# Other Information (Optional)

2021-05-26 17:27 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Lastly, we will delete the key:
Great opportunity here to explain the workflow of creating, calling and then deleting a key from storage is useful and how it can be used to build into other concepts.

2021-05-26 17:36 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +This might look similar to you, we are importing packages that we need while writing a smart contract. These packages will use while writing a smart contract.
This wording is redundant and does not clarify the point being made. Please re-word these sentences to reflect the specific Rust syntax for using library or module code.

2021-05-26 17:39 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Lastly, `wee_alloc` is a way to optimize memory management. This is just a boilerplate code.
There is a specific reason that the near-sdk wee_alloc is used, which can be explained via a link to external documentation if you wish to empower readers to learn more. Also, please consider expanding on 'boilerplate code'. You might also take the opportunity to explain a little bit about Rust macros and how #[global_allocator] is going to expand into the boilerplate code at compilation time 😄

2021-05-26 17:43 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +we wrap our struct `KeyVaue` in `#[near_bindgen]` and it generates a smart contract compatible with NEAR blockchain. The second attribute helps to serialization and de-serialization of the data.
missing an l on 'KeyValue' 🦖

2021-05-26 17:52 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Now, let’s go step by step. First, we are creating a `Default` implementation for `KeyValue`. After that, we added the `default` method inside that implementation which returns `Self`. `Self` refers
If we're going step by step, what is 'b'? 😉 
I know the answer, but let's not do our readers a disservice by leaving out an important aspect of the syntax. I think it's a fair thing to assume that readers new to the Rust language will legitimately find themselves asking why 'b' is declared elsewhere in the code but never concretely explained, and thus .. why is it being referenced here, and having .to_vec() called on it?

2021-05-26 17:58 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +When creating methods, we have an implementation block that has the keyword `impl` followed by the same name as that of the struct. Here we are writing functions that will be available publicly for u
Consider a slight refinement such as "When creating methods, we must have an implementation block defined by the `impl` keyword followed by the name of the struct to be implemented. The `pub` keyword makes the methods publicly available, meaning they can be called by anyone with access to the protocol and a means of signing the transaction."

2021-05-27 08:00 UTC, yash-sharma1 requested changes

2021-05-27 08:00 UTC, yash-sharma1 commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +## Prerequisite
In Prerequisites only include any prior knowledge needed or existing tutorials that need to be completed first.


In Requirements only include any technology that needs to be installed prior to starting the tutorial and that the tutorial will not cover (like Metamask, node, truffle, etc). Do not list packages that will be installed in the tutorial (eg. dotenv).

So here what you mentioned in the Prerequisite should go into the Requirements section

2021-05-27 08:00 UTC, yash-sharma1 commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +If you want to learn more about rust by going [here](https://doc.rust-lang.org/book/).
Please chenge the langauage of this line.

Like - If you want to Learn more about Rust, check this guide HERE

2021-05-27 08:00 UTC, yash-sharma1 commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Thank you for following along with this tutorial, now take this knowledge and build amazing things on NEAR!
I request you to please review and follow our [sample tutorial structure](https://learn.figment.io/other/tutorial-guidelines/sample-tutorial-structure) which will help in making it consistent and follow the similar structure as other tutorial also at the end please include link to figment discord 
Like - If you had any difficulties following this tutorial or need any help you can [join our community today!](https://discord.gg/fszyM7K)

2021-05-27 08:35 UTC, yash-sharma1 commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +This will create a basic rust project for us. Now open `Cargo.toml` and copy the following:
Add clear instructions here "Now open `Cargo.toml` and copy the following:" after that ? do we need to paste this is in cargo.toml or what?

2021-05-27 09:28 UTC, yash-sharma1 requested changes

2021-05-27 13:50 UTC, nikbhintade commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Lastly, we will delete the key:
Can you give an example?

2021-05-27 13:51 UTC, nikbhintade commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Thank you for following along with this tutorial, now take this knowledge and build amazing things on NEAR!
Yeah, I'll restructure the article according to the sample tutorial.

2021-05-28 21:40 UTC, guillaumegaluz requested changes

2021-05-31 17:23 UTC, nikbhintade commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Let's check if we wrote code write or not. Run
I am just removing this piece. What I am trying to say was not coming out properly. This is additional info this is not related to the smart contract.

2021-05-31 17:24 UTC, nikbhintade commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +The above command just checks whether or not we have any errors in our code.
I am not sure what I should write here so maybe I'll leave this.

2021-06-01 19:38 UTC, guillaumegaluz commented
Hey @nikbhintade - i noticed that you resolved all the comments but didn't make the changes. So I will wait until you do to rereview this PR. Thanks

2021-06-02 15:37 UTC, nikbhintade commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Lastly, we will delete the key:
@pyr0gan I tried to add this section, I couldn't come up with a satisfactory example so I left it. And assuming learners who will follow this tutorial have some programming knowledge, we don't have to tell them how to use key-value storage.

2021-06-02 23:51 UTC, pyr0gan requested changes
Thank you for your effort and for quickly working towards a final draft. There are a number of issues to go over, please read my comments and resolve them when you can. Thanks @nikbhintade

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +After that, we are calling the method `insert` on `self.pairs`. This will create key-value pair if not present already otherwise it will update the value associated with the given key.
> After that, we are calling the method `insert` on `self.pairs`. This will create a key-value pair if one is not present already otherwise it will update the value associated with the given key.

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +The next two methods have the same working but instead of calling the `insert` method, we call `get` and `remove` methods on `self.pairs` to read and remove key-value pair respectively.
> The next two methods are quite similar but instead of calling the `insert` method, we call `get` and `remove` methods on `self.pairs` to read or remove the key-value pair.

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Our smart contract is now complete. Let's write some unit tests.
> The code for this our CRUD smart contract is now complete. One of the nice features of Rust is that it allows inline unit tests. This means we can write our unit tests in the same source file as our contract, `lib.rs`!.

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Why should we write unit tests for a smart contract? Writing unit tests is a common pratice in software development. While writing smart contract, units tests are more important. As smart contracts a
> Why should we write unit tests for a smart contract? Unit testing is a common practice in software development. While writing smart contracts, units tests are important because smart contracts are often immutable and sometimes responsible for managing sums of money. Writing good unit tests is a key component of secure and reliable smart contract development.

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Add following snippet below the comment `// 4. Tests`:
> Copy and paste the following code below the comment `// 4. Tests` in `lib.rs` :

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +    // test 1
```
// Test 1

// Test 2
```

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Here we are setting our testing environment with various parameters. You can read about how to setup your testing environment [here](https://docs.rs/near-sdk/3.1.0/near_sdk/struct.VMContext.html).
> This is where we set up our testing environment with various parameters and a mocked blockchain. Read more about the Virtual Machine context and testing environment [in the NEAR-SDK docs](https://docs.rs/near-sdk/3.1.0/near_sdk/struct.VMContext.html).

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Let's write our first test for `create_update` and `read` methods. Add following snippet below the comment `// test 1`:
> Let's write our first test for the `create_update` and `read` methods. Paste the following snippet below the comment `// Test 1` in `lib.rs`:

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +First, we are creating a `context` variable by calling `get_context` function and passing it to `testing_env` macro which creates a testing environment with given parameters. Now, we have to create a
> First, we are creating a `context` variable by calling the `get_context` function and passing it to the`testing_env!()` macro which creates a testing environment using the given parameters. Next, we have to create a mutable `contract` variable which will use the contract that we have just written. We can then use this `contract` variable to call our methods for testing.

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Now, let’s call the `create_update` method to set key-value pairs. The key will be `first_key` and the value will be `hello`. After creating pair, we want to check if the right values are stored in s
> Now, let’s call the `create_update` method to set key-value pairs. The key will be `first_key` and the value will be `hello`. After creating pair, we want to check if the right values are stored in storage. For checking, we will use the `assert_eq!()` macro. It takes 2 arguments; the expected value and the actual value.

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Let's assume that key is not present in storage then `None` should be returned when we read that key. In next test we are going to test our assumtion. Add following snippet below the comment `// test
> For our second test, we will assume that key is not present in storage. In this case, `None` should be returned when we attempt to read the key. Add the following code below the comment `// Test 2`:

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Just like the first test, we will create our testing environment and `contract` variable. But here contract variable is unmutable. As we are not going to change the `contract` variable. To check `Non
> Just like in the first test, we will create our testing environment and `contract` variable. In this test however, the contract variable is immutable, as we are not going to change the `contract` variable. To check that `None` is returned after accessing a nonexistent key using `contract.read("first_key".to_string())`, we'll use `assert_eq!()`.

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +```javascript
You can change this code block to `bash`, as it is terminal output and not Javascript 😄

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Now, let’s test our code. Run following command in terminal:
> Now, it is time to test our code. Run the following command in the terminall:

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Tests will pass only if contract is working properly. As our smart contract is working properly we will see the following as the output:
> The tests will pass only if the contract is working properly. As our smart contract is working properly, we will see the following output:

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +```javascript
You can change this code block to `bash`, as it is terminal output and not Javascript 😄

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +As we have written and tested the smart contract, we will compile it for deployment. Run following command in terminal:
Now that we have written and tested the Rust smart contract, we will compile it into WebAssembly for deployment on NEAR. Run the following command in the terminal (NOTE: Windows users will have to perform the two commands separately, `set` for the environment variables and then the `cargo build` command):

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +```javascript
You can change this code block to `bash`, as it is terminal output and not Javascript 😄

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +// for linux and mac users
> // Linux and macOS users can use these commands:

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +// for windows users
> // Windows users can use these commands:

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +You will see the following at the end of execution:
> The output from `cargo build` will be similar :

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +We have generated optimized WASM file which we can deploy on NEAR testnet.
> We have now generated an optimized WebAssembly file which we can deploy on NEAR, for this tutorial we will deploy it to the NEAR testnet.

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +This will redirect you to browser and then click on allow button. This will get your credentials in your machine.
Can you please expand on this process somewhat? Some screenshots would go a long way in helping learners to follow along 😉 
Also, can you explain where the credentials are stored?

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Let's deploy our smart contract. Run following command in terminal:
> Now we can deploy our Rust smart contract to NEAR. Run the following command in the terminal:

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +```javascript
Change code highlighting type to `bash` 😉

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +near deploy --wasmFile target/wasm32-unknown-unknown/release/key_value_storage.wasm --accountId YOUR_ACCOUNT_HERE
Because it comes up a few times further ahead in the tutorial, could you please add a sentence to explain to learners about replacing `YOUR_ACCOUNT_HERE` with their account name? It will save some confusion 😅

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +```javascript
Terminal output should use the `bash` highlighting type 😄

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +xqc@RecycleBin:~/key_value_storage$ near deploy --wasmFile target/wasm32-unknown-unknown/release/key_value_storage.wasm --accountId 0xnik.testnetStarting deployment. Account id: 0xnik.testnet, node:
Can you please remove the command prompt and the command itself from the terminal output?

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Create key-value pair:
> This command will create a key-value pair:

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Let's try to call smart contract from the terminal.
> Now that we have deployed our contract, we can interact with it using the NEAR CLI.

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +If you have to provide arguments to a function, then you have to add that argument as a JSON object.
> Function arguments must be provided inside of a JSON object: `create_update({"k": "first_key", "v" : "1"})` notice the `{ }` curled brackets inside of `create_update()`

2021-06-02 23:51 UTC, pyr0gan commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +In this tutorial, we have covered the following:
> In this tutorial, we have covered the basics of NEAR smart contract programming using Rust - including the structure of a Rust smart contract; the use of functions and macros offered by the NEAR SDK; how to use on-chain storage; unit testing of a Rust contract; compiling and deploying WebAssembly and finally interacting with deployed Rust contracts on the NEAR blockchain using the NEAR CLI.

2021-06-03 02:38 UTC, nikbhintade commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +```
I'll add the output of the command but the NEAR intro pathway doesn't have any mention of Rust. Maybe you are getting this output because another Rust [tutorial](https://learn.figment.io/network-documentation/near/tutorials/write-nft-contracts-in-rust) already explained this command. But As this is an introductory tutorial for Rust, I added that.

2021-06-03 06:37 UTC, nikbhintade commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +# How to write and deploy a smart contract in Rust
Yeah, It sounds better.

2021-06-07 11:22 UTC, yash-sharma1 commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Let's check if we wrote code write or not. Run
You should write it as "Let's check our code by running the following command, if we did everything correctly we'll see an output like this - _Add_Image_of_the_Output_
If can't see the expected output then make sure to check - _Add_Troubleshooting_ Steps Like what can cause this issue here at this point_

2021-06-07 15:05 UTC, nikbhintade commented on network-documentation/near/tutorials/how-to-write-and-deploy-smart-contract-in-rust.md
> +Let's check if we wrote code write or not. Run
Cargo check is used for checking if the code we have written have some errors without actually building the executable file. But code in the tutorial won't have an errors. Running this command will return nothing.

I wanted to add this as a bouns tip for readers but explaining this is unrelated to the tutorial.

2021-06-07 18:39 UTC, pyr0gan approved these changes
After reviewing the other commits, I'll save you the line by line recap of my comments and sum it up here:

Well done, thank you for your work on this tutorial @nikbhintade. Pending a second set of eyes from @yash-sharma1 I'd say this is OK to merge 😄 🚀

2021-06-08 04:22 UTC, yash-sharma1 commented
Appreciate your work @nikbhintade and your efforts in making small to small correction as per our feedback. It looks all good to me. 💯

2021-06-08 04:23 UTC, yash-sharma1 approved these changes

2021-06-08 17:33 UTC, merged

2021-06-09 00:27 UTC, guillaumegaluz commented
Nice one @nikbhintade! [The tutorial is now live on Figment Learn](https://learn.figment.io/network-documentation/near/tutorials/write-and-deploy-a-smart-contract-on-near.). We're going to post it on Discord and let the community know. Feel free to do the same!

Any other tutorial ideas you'd like to contribute to Learn?

2021-06-09 03:47 UTC, nikbhintade commented
@guillaumegaluz I am working on an article on Aurora (NEAR EVM). This was for the NEAR hackathon but couldn't finish it in time. so I'll submit it now. It will contain a basic intro to Aurora, and how to deploy the solidity contract on NEAR.