Distributed File Manager using Celo, IPFS and ReactJS
figment-networks/datahub-learn pull request #117
Opened 2021-05-26 18:14 UTC by rajranjan0608

# Description*

Nowadays everything is on the cloud, and keeping our files on the cloud is quite expensive. Therefore I have used the IPFS protocol, Celo's blockchain network to build a Distributed File Manager, and ReactJS for the client-side, in which you can store as many files as you want using your Celo wallet account. And the files are visible to you only, i.e. the one who uploaded the file. You may also share the link to the file with your friends if you want. 

![ ](https://imgur.com/a6on3z4.gif)

Fixes # (issue)

## Type of change*

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## This PR created for* - 

- [x] Figment Learn Docs (Pathway, Existing Tutorials, New Tutorial etc.) changes/updates/fixes

# Checklist*:

- [x] I updated the `SUMMARY.md` file (FYI, It's needed only when you're creating a new file like submitting a new tutorial, pathway section)
- [x] I created one tutorial for this PR (one PR <=> one tutorial)
- [x] I checked and accept that my PR for a new tutorial follows the [**Tutorial Guidelines**](https://learn.figment.io/other/tutorial-guidelines) of this project
- [x] I checked and read the contribution guide before making this PR [**HERE**](https://learn.figment.io/figment-learn/contribute)  
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Note - Above points marked with * are mandatory to fill :)

2021-05-28 15:07 UTC, yash-sharma1 requested changes

2021-05-28 15:07 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +## Congratulations!
As I mentioned previously this section have to be introduced as 'Conclusion' not Congratulations! and inside this you can add congratualtion and other description. Also here conclusion is completely similar to your previous tutorial, here try to explain what all user have learned and what's the final outcome fo doing this.

2021-05-31 14:21 UTC, yash-sharma1 requested changes
I appreciate your work, efforts and patience. You're really good listener and a contributor.
On general note - I noticed that you have used most of the text part and components from previous tutorials it's ok upto a level but if it's too much it looks exact copy of previous tutorial. So I encourage you to write differently so learners learn something new with you while going through the tutorial not just like similar steps one by one which they already did in previous tutorial. So try to write different language, words and make changes accordingly.

2021-05-31 14:21 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +For deploying smart contracts we need two things viz. A node connected to the **Celo** network and an account with few **CELO**. The good news is, **Celo** provides a remote node, which is already co
Wondering why we're not using DataHub here? We can deploy the contract using DataHub CELO RPC and we ca fund our account from CELO Faucet.

2021-05-31 14:21 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +MNEMONIC="<avalanche-wallet-mnemonic>"
In the CELO tutorial why we'll be using Avalanche Wallet MNEMONIC ;) I assume mistakenly you left it asit is so please change it

2021-05-31 14:21 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +      + Using an adequately funded account
I think you should change it with actual similar error seems this one exactly copied from the previous tutorial. so I prefer to run the tutorial without funds and then get the error & then addd that one here

2021-05-31 15:28 UTC, rajranjan0608 commented
> I appreciate your work, efforts and patience. You're really good listener and a contributor.
> On general note - I noticed that you have used most of the text part and components from previous tutorials it's ok upto a level but if it's too much it looks exact copy of previous tutorial. So I encourage you to write differently so learners learn something new with you while going through the tutorial not just like similar steps one by one which they already did in previous tutorial. So try to write different language, words and make changes accordingly.

Hi @yash-sharma1. Thanks for the review and I really appreciate it. I always try to make the readers learn something new in every tutorial. 
1. Basic e-voting - Readers learnt how to deploy a basic smart contract to deploy on the Avalanche network.
2. Advanced e-voting (jQuery) - Readers learnt how to deploy any number of smart contracts by directly making a contract call.
3. Advanced e-voting (React) - Same as above (2), but using ReactJS.
4. Distributed File Manager (React) - Readers learnt about IPFS protocol and how they can use it with the Celo network.

Most of the tutorial is the same because I tried to cover everything from the beginning, and my major concern was to set up a standard to make these projects. So, parts like `Setting up project`, `Deployment` and `Client-side files` are similar. 

But I could totally understand your concern, and so, I could add more explanations on IPFS protocol, about how to verify transactions on the Celo explorer etc. And therefore I request you to suggest more additions to this tutorial rather than changing the words of the tutorial to make it look different. Please let me know your thoughts on this. Thank you.

2021-05-31 15:30 UTC, yash-sharma1 commented
> > I appreciate your work, efforts and patience. You're really good listener and a contributor.
> > On general note - I noticed that you have used most of the text part and components from previous tutorials it's ok upto a level but if it's too much it looks exact copy of previous tutorial. So I encourage you to write differently so learners learn something new with you while going through the tutorial not just like similar steps one by one which they already did in previous tutorial. So try to write different language, words and make changes accordingly.
> 
> Hi @yash-sharma1. Thanks for the review and I really appreciate it. I always try to make the readers learn something new in every tutorial. 
> 1. Basic e-voting - Readers learnt how to deploy a basic smart contract to deploy on the Avalanche network.
> 2. Advanced e-voting (jQuery) - Readers learnt how to deploy any number of smart contracts by directly making a contract call.
> 3. Advanced e-voting (React) - Same as above (2), but using ReactJS.
> 4. Distributed File Manager (React) - Readers learnt about IPFS protocol and how they can use it with the Celo network.
> 
> Most of the tutorial is the same because I tried to cover everything from the beginning, and my major concern was to set up a standard to make these projects. So, parts like `Setting up project`, `Deployment` and `Client-side files` are similar. 
> 
> But I could totally understand your concern, and so, I could add more explanations on IPFS protocol, about how to verify transactions on the Celo explorer etc. And therefore I request you to suggest more additions to this tutorial rather than changing the words of the tutorial to make it look different. Please let me know your thoughts on this. Thank you.

Sure, that will work

2021-06-01 07:33 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +  networks: {
You missed a comma here after `'./src/build/contracts'` it should be `'./src/build/contracts',` otherwise it'll throw error

2021-06-01 08:10 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +// 1. Load web3
this is comments next to this are incorrect in serial numbers, it should be //2. Load Web3 as //1 was the previous comment

2021-06-01 09:43 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +      + Using an adequately funded account
Updated

2021-06-01 09:44 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +  networks: {
Thanks. I will update.

2021-06-01 10:59 UTC, yash-sharma1 requested changes
Update this tutorial to perform it using Celo RPC provided by DataHub

2021-06-01 10:59 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +We have built a Distributed File Manager with basic upload and view features. I want to encourage you to make a more scalable and sofisticated application by adding few more features like encrypting
If possible please add links or basic idea how encrytpion can be done, and tips for enhancing the UI

2021-06-01 10:59 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +npm install --save ipfs-http-client compressorjs rimble-ui
When we know we need to install this why don't we do it at the initial stage. So we can shift it from here to starting

2021-06-01 10:59 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +* **Upading `App.js`** - `App.js` is the entry point of any React application. Therefore we need to update `App.js` regularly with the components which we want to show in our application. As we move
It should be Updating App.js
wondering these are similar typos from previous tutorial :)

2021-06-02 00:12 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +Now go to your browser, and visit the URL - http://localhost:3000 If your followed the above steps, you would see the page as shown below. Background theme of the website is dark, so you have to look
I think it would be much easier to just change the text colour to something brighter. Then you can say :

> In a web browser, visit the URL [http://localhost:3000](http://localhost:3000). If `npm start` has not encountered any errors, we will see the text "Distributed File Manager" at the top of the page as shown in this image :

2021-06-02 00:15 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +## **Create `FileManager.sol` smart contract**
Perhaps we could go with the heading "Create the FileManager contract", instead?

2021-06-02 00:22 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +	function getFiles(address _account) public  view  returns (File[] memory) {
Just a couple of extra spaces around 'view' to clean up, here 👍🏻

2021-06-02 00:23 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +	function addFile(string[] memory _fileInfo, string  memory _cid) public {
There's an extra space after string 😉

2021-06-02 00:30 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +`FileManager` is a solidity smart contract which lets us store and view the meta details of file which we upload on the `IPFS` network. IPFS uses content addressing rather than location addressing. I
I suggest removing the backticks from IPFS, content identifier and cid. I know the temptation to use backticks for emphasis is strong, but it is best to keep preformatted text for when it is relevant; such as filenames; directory names; terminal commands; package names; hexadecimal addresses; code comments and function names. Not an exhaustive list, but hopefully you get the idea 😅

2021-06-02 00:37 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +For example, let us say, we upload an image file named `dark-forest.jpg` on IPFS. Now IPFS protocol would generate a unique hash, called as `cid` or `contend id` which will reference this file on the
`contend id` seems like a typo. You also just explained this exact point in different words, above. I think you could just alter what you've got to :

> Now IPFS generates a unique content identifier, the "cid" which can be used to reference this file on the network. cid's look similar to `QmVwyUH96NeQPwLN5jDkgNxM41xGCB1EVjnBYX7NoWWmKH`, a long string of upper- and lower-case letters and numbers. This is the hashed representation of the content. More information about IPFS content identifiers can be found on the [IPFS docs](https://docs.ipfs.io/concepts/content-addressing/#content-addressing-and-cids).

2021-06-02 00:39 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +```solidity
Please fix indentation and formatting on all code blocks 😄

2021-06-02 00:40 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +If you didn't create an account on the `CELO` you'll see this error:
> If you have not created an account on CELO, you would see this error :

2021-06-02 00:41 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +```javascript
Not Javascript, likely `bash`?

2021-06-02 00:42 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +```javascript
Please fix formatting and indentation of code blocks 😄

2021-06-02 00:44 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +* **Upading `App.js`** - `App.js` is the entry point of any React application. Therefore we need to update `App.js` regularly with the components which we want to show in our application. As we move
@yash-sharma1 @guillaumegaluz I agree, there are a lot of similarities and I am duplicating a lot of effort in reviewing this tutorial.

@rajranjan0608 Can you please fix all of the formatting issues we have discussed? I will continue my review when that is complete!

2021-06-05 14:28 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +```javascript
Done

2021-06-05 14:29 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +import  React  from  'react';
Indentations fixed for all code blocks :+1:

2021-06-05 14:30 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +For deploying smart contracts we need two things viz. A node connected to the **Celo** network and an account with few **CELO**. The good news is, **Celo** provides a remote node, which is already co
Made use of Datahub's Celo RPC url.

2021-06-05 14:32 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +npm install --save ipfs-http-client compressorjs rimble-ui
@yash-sharma1 As you know, Rimble UI has a peer-dependency conflict with React's latest version. So, I have installed this library along with others in order to explain this error.

2021-06-05 14:32 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +* **Upading `App.js`** - `App.js` is the entry point of any React application. Therefore we need to update `App.js` regularly with the components which we want to show in our application. As we move
Fixed :+1:

2021-06-05 16:53 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +	let account = ethers.Wallet.fromMnemonic(process.env.MNEMONIC, "m/44'/52752'/0'/0/0")
@pyr0gan Thanks for the suggestion :smile:. I have dug deep and learnt a lot about these HD wallets. Will soon add a brief explanation about it in this PR.

2021-06-06 08:57 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +	let account = ethers.Wallet.fromMnemonic(process.env.MNEMONIC, "m/44'/52752'/0'/0/0")
@pyr0gan I have added a detailed explanation on HD Wallets. Please refer to the commit 7b24604d829a25c618efb3cd53b0c27b769a176f. I hope this would not make the tutorial big. Thank you.

2021-06-07 09:45 UTC, yash-sharma1 requested changes

2021-06-07 09:45 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +CELOAPI=<your_datahub_api>
To make it clear and self explanatory please change it to `DATAHUB_API_URL`

2021-06-07 09:45 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +
In the requirements section you should mention that we need an account on DataHub and add link to it.

2021-06-07 09:45 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +![](https://i.imgur.com/3eFZpJn.png)
Don't you think we are using DataHub so we will be using Metamask with DataHub and credentials mentioned here will be changed. Like the way we did in Avalanche tutorial.

2021-06-07 10:43 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +![](https://i.imgur.com/3eFZpJn.png)
Done :+1:

2021-06-07 10:46 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +CELOAPI=<your_datahub_api>
Cool. I have also updated the CELOAPI to DATAHUB_CELO_API for adding more meaning to it.

2021-06-07 18:28 UTC, pyr0gan reviewed
Just a few changes left, have a look 😄

2021-06-07 18:28 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +
+1 for this @rajranjan0608 😄

2021-06-07 18:28 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +## Conclusion
Looks good, I believe it's only the headings which need fixing at this point.

2021-06-07 19:08 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +In the above file, the line where we are fetching the account address from the wallet's mnemonic needs to be explained.
Done!

2021-06-07 19:09 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +
Thanks :heart:

2021-06-07 19:10 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +## Conclusion
@pyr0gan and @yash-sharma1 I have updated the headings.

2021-06-07 19:30 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +
It's done.

2021-06-07 21:06 UTC, pyr0gan approved these changes
LGTM

2021-06-08 05:46 UTC, yash-sharma1 commented
Appreciate your work @rajranjan0608 and your efforts in making corrections as per our feedback. It looks all good to me 💯

2021-06-08 05:46 UTC, yash-sharma1 approved these changes

2021-06-08 07:18 UTC, yash-sharma1 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +## Conclusion
> @pyr0gan and @yash-sharma1 I have updated the headings.

Sorry for the again last iteration but I checked heading should be in `##` format instead of `#` as gitbook will render `#` for the title and `##` for the `H1` so you need only `##` for `H1` in the tutorial. 
You can check the markdown file of the sample tutorial structure here - https://github.com/figment-networks/datahub-learn/blob/master/other/tutorial-guidelines/sample-tutorial-structure.md

2021-06-08 17:24 UTC, pyr0gan requested changes
I have updated the Tutorial guidelines to reflect the appropriate heading levels, apologies for the confusion.  Section headings are H1, subheadings are H2 😄

2021-06-08 17:31 UTC, pyr0gan commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +## Conclusion
I have updated the sample tutorial to use H1 for section headings. The reason is because of the GitBook Table of Contents and how it renders. Please understand that this can be revisited it in the future when we are on Learn v2 - for now we are using this format to keep the GitBook documentation as readable as possible 😄

2021-06-08 17:37 UTC, rajranjan0608 commented on network-documentation/celo/tutorial/distributed-file-manager-using-ipfs-celo-reactjs.md
> +## Conclusion
I have updated the headings. Please have a look.

2021-06-09 06:34 UTC, yash-sharma1 commented
@pyr0gan in the new commit by @rajranjan0608 now all the heading are in `#`   markdown which is actually only applicable on Title whereas we discussed that heading should be in Heading1 or H1 format which is rendered in gitbook by `##` markdown so can you please review it here.

2021-06-09 17:34 UTC, pyr0gan approved these changes
Changes look good, I'll tweak it on the GitBook if need be. Thanks @rajranjan0608 and @yash-sharma1 for all your work on making the material the best it can be 😄

2021-06-09 17:34 UTC, merged