Polkadot: Create tutorial for Polkadot Blockchain Terms
figment-networks/datahub-learn pull request #118
Opened 2021-05-29 06:18 UTC by DannyS03

Name of tutorial subject to change. 

The tutorial focusses on the "essential blockchain concepts" from a general [Polkadot] standpoint both for an average user and a developer: differences of each and possible benefits, drawbacks - how they come together.

Any feedback for format, content and approach is highly encouraged.

--- 
- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [x] I've followed the [template structure](Structure).
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've ran a linter & prettifier to format my code blocks.
- [ ] I've thoroughlly explained the code, with inline code comments and text explanations.
- [ ] I've ran the tutorial and the code works.

2021-06-03 07:35 UTC, yash-sharma1 commented
Appreciate your quick take on the tutorial contribution, Danny. 
I walked through the content, it's good but I have some suggestions which we can make in this tutorial guide to make it more structured, consistent, well documented and learner/developers friendly. 
Firstly we should put the whole content in a structured tutorial form something like this **[Check Here](https://learn.figment.io/other/tutorial-guidelines/sample-tutorial-structure)**
The structure should be like this - 
# Introduction
Here you can explain Polkadot (major points only), why it's different and its benefits, and details of what we're going to cover in this guide further. The objective here is to make developers familiar with the Polkadot first before explaining them Parachains, Parathreads, Smart Contracts etc.
# Prerequisites
Definitely, it's not about tools and code but as you're well versed with Polkadot so you know well what kind of knowledge is necessary before reading about Parachains and other complex topics which we'll cover further in this guide. In this section, in bullet points, you can mention or add links to those 2-3 resources, articles, YouTube Video or something else for which learners/developers should have some knowledge. Like the Technical architecture of Polkadot, basic terminology in reference to Polkadot blockchain etc.
# Body of the Tutorial _(Give it a name as per your topic)_
Now we're ready to start explaining the things for which we're writing this tutorial i:e; Understanding the differences between parachains, DApps, solo threads, etc. and each approach's benefits and drawbacks.

I prefer you should explain specifically Parachains, Smart Contracts, DApps, and Solo Threads in separate sections along with their advantages & disadvantages and after that under the heading **Difference between Parachains, Smart Contracts and DApps** we should differentiate them in tabular form which you can create and add as an image I think. It'll look more structured. 

# Conclusion 
In this section, you can give a quick walkthrough of the whole tutorial, like what we covered, what we learned, why it was important. 

# What's next? 
In this section, you can add your advice/recommendation for learners/developers that after this guide what should be next for them, what should they read, develop and build. Like you give them links to some advanced concept videos, articles to read etc. which can enhance their existing knowledge. 

# About the Author
_It's Time to introduce the guy behind this awesome guide_  You can make it like -
This tutorial guide was created by **[Danny Salman](https://github.com/DannyS03)**. You can reach out to Danny on **[Figment Forum](Link to your Figment Forum profile)** & on **[GitHub](https://github.com/DannyS03)** for any help & questions pertaining to Polkadot and this guide. 

# Referneces
This section must be present if you have taken any help in writing this tutorial from other documents, GitHub repos and other tutorials.
Credit sources by adding their name and a link to the document when possible. If it is not a digital document, include an ISBN or other form of reference.

2021-06-03 07:38 UTC, yash-sharma1 commented
Also, I saw you didn't update the `SUMMARY.md` file with the link to your this tutorial guide so, once you have completed the documentation make sure you have added a new entry in the `SUMMARY.md` file.

2021-06-03 07:45 UTC, yash-sharma1 commented
Please consider these requested changes for another PR as well [Polkadot: Create guide for Parachain Lifecycle](https://github.com/figment-networks/datahub-learn/pull/119) we'll review it soon as you make changes. 
For any queries and help feel free to ping here or on Discord :)

2021-06-03 07:49 UTC, yash-sharma1 commented
@guillaumegaluz can share his views and ideas as well to make it the best one.

2021-06-03 23:10 UTC, DannyS03 commented
Hi @yash-sharma1, many thanks for the feedback. I had been wondering whether it was the right approach to follow the tutorial structure since the content is mainly "written" - just updated the file :) 

Regarding the `SUMMARY.md` - where would the tutorial (and the parachain lifecycle one) be under? I guess what I'm asking is where should it fall within the list of tutorials under Polkadot, and do you think the file name is okay?

2021-06-03 23:10 UTC, DannyS03 commented
> @guillaumegaluz can share his views and ideas as well to make it the best one.

@guillaumegaluz I updated the file and it can be reviewed.

2021-06-07 09:59 UTC, yash-sharma1 commented
> Hi @yash-sharma1, many thanks for the feedback. I had been wondering whether it was the right approach to follow the tutorial structure since the content is mainly "written" - just updated the file :)
> 
> Regarding the `SUMMARY.md` - where would the tutorial (and the parachain lifecycle one) be under? I guess what I'm asking is where should it fall within the list of tutorials under Polkadot, and do you think the file name is okay?

So to add the tutorial under the `SUMMARY.md`, it'll go under the Polkadot category like - 
Network Documentation > Polkadot > Tutorials > _Add_Your_Tutorial_At_End_
![Screenshot 2021-06-07 152817](https://user-images.githubusercontent.com/44340561/120997677-07d71700-c7a5-11eb-8a6b-cdb3d607bb48.png)

Note - Do the same for both the tutorial guides

2021-06-07 10:16 UTC, yash-sharma1 commented
The filename is okay but the title of the guide needs to change you can have "Introduction to advanced concepts of Polkadot" or something else which is self-explanatory to this guide.

2021-06-07 11:14 UTC, yash-sharma1 requested changes

2021-06-07 11:14 UTC, yash-sharma1 commented on network-documentation/polkadot/tutorials/polkadot-blockchain-terms.md
> +#### **Wasm vs EVM**
Explain major differences b/w Wasm and EVM and advantages of Wasm over EVM within the guide would be great instaed of directly referring to another article, we can add this as referance later

2021-06-07 11:14 UTC, yash-sharma1 commented on network-documentation/polkadot/tutorials/polkadot-blockchain-terms.md
> +This tutorial guide was created by Danny Salman. You can reach out to Danny on [Figment Forum](salman.danny@hotmail.com) & on GitHub for any help & questions pertaining to Polkadot and this guide.
You need to create an accout on Figment Forum and add the link to that here, instead of your email :)

2021-06-07 11:14 UTC, yash-sharma1 commented on network-documentation/polkadot/tutorials/polkadot-blockchain-terms.md
> +- [5] [Research at Web3 Foundation](https://research.web3.foundation/en/latest/polkadot/overview/1-polkadot-introduction.html?highlight=parachains)
Keep referances only in number list and remove bullet point format.

2021-06-07 11:14 UTC, yash-sharma1 commented on network-documentation/polkadot/tutorials/polkadot-blockchain-terms.md
> +This tutorial will outline key blockchain concepts through the eyes of Polkadot by creating distinctions and
Replace tutorial with guide -
Eg. - This guide will outline key blockchain concepts through the eyes of Polkadot by creating distinctions

2021-06-14 11:14 UTC, yash-sharma1 commented
Hey @DannyS03 can you please let me know is there any update on the required changes and if you're working on them.
Let me know if you have any queries and need any help.

2021-06-14 13:11 UTC, DannyS03 commented
> Hey @DannyS03 can you please let me know is there any update on the required changes and if you're working on them.
> Let me know if you have any queries and need any help.

Sorry, yes, will be updating files today.

2021-06-14 20:23 UTC, DannyS03 commented on network-documentation/polkadot/tutorials/polkadot-blockchain-terms.md
> +- [5] [Research at Web3 Foundation](https://research.web3.foundation/en/latest/polkadot/overview/1-polkadot-introduction.html?highlight=parachains)
addressed

2021-06-14 20:23 UTC, DannyS03 commented on network-documentation/polkadot/tutorials/polkadot-blockchain-terms.md
> +This tutorial will outline key blockchain concepts through the eyes of Polkadot by creating distinctions and
addressed

2021-06-14 20:24 UTC, DannyS03 commented on network-documentation/polkadot/tutorials/polkadot-blockchain-terms.md
> +  [Video](https://www.youtube.com/watch?v=_-k0xkooSlA) on the official Polkadot YouTube Channel.
addressed

2021-06-14 20:24 UTC, DannyS03 commented on network-documentation/polkadot/tutorials/polkadot-blockchain-terms.md
> +
addressed

2021-06-14 20:33 UTC, pyr0gan approved these changes
Guide looks good, I don't see any issues with merging it.

EDIT: Except you never did add a SUMMARY.md link so I will need to revert this until we can fix it.

2021-06-14 20:34 UTC, merged

2021-06-14 20:44 UTC, DannyS03 commented on network-documentation/polkadot/tutorials/polkadot-blockchain-terms.md
> +#### **Wasm vs EVM**
addressed: left it more at a high-level as the differences from a low-level perspective might be exhaustive for the purpose of the section (i.e. data structures, etc...)

2021-06-14 20:46 UTC, DannyS03 commented on network-documentation/polkadot/tutorials/polkadot-blockchain-terms.md
> +This tutorial guide was created by Danny Salman. You can reach out to Danny on [Figment Forum](salman.danny@hotmail.com) & on GitHub for any help & questions pertaining to Polkadot and this guide.
addressed

2021-06-14 20:47 UTC, DannyS03 commented on network-documentation/polkadot/tutorials/polkadot-blockchain-terms.md
> +  ## ![](../../../.gitbook/assets/polkadot-graphic.png)
> Guide looks good, I don't see any issues with merging it.
> 
> EDIT: Except you never did add a SUMMARY.md link so I will need to revert this until we can fix it.

Thanks for the review :) Are the images showing up for you? Going to just format them better

2021-06-14 20:53 UTC, DannyS03 commented
@pyr0gan there were just some changes added after I opened a PR: https://github.com/figment-networks/datahub-learn/pull/124

2021-06-14 21:19 UTC, pyr0gan commented
Can you please open a fresh PR from your branch that includes the fixes? It will be much simpler than having to fix the conflicting files across 2 PRs!