Secret nft deploy your own contract
figment-networks/datahub-learn pull request #120
Opened 2021-06-05 08:49 UTC by floAr

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines). If you don't follow those guidelines it might take longer for us to review.

- [x ] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [x ] I've followed the [template structure](Structure).
- [ x] I've proofread the tutorial for spelling and grammar mistakes.
- [ x] I've ran a linter & prettifier to format my code blocks.
- [ x] I've thoroughlly explained the code, with inline code comments and text explanations.
- [ x] I've ran the tutorial and the code works.

2021-06-07 09:50 UTC, yash-sharma1 commented
Hey @floAr 
Thanks for making this PR so quick before the workshop. 
Just before we move forward 
- can you please restructure the tutorial according to this **[Sample Tutorial](https://learn.figment.io/other/tutorial-guidelines/sample-tutorial-structure)**
- Also seems like you forget to mention the addition of this tutorial in the main `SUMMARY.md` file so please update the `SUMMARY.md` file accordingly.

2021-06-07 15:20 UTC, floAr commented
> Hey @floAr
> Thanks for making this PR so quick before the workshop.
> Just before we move forward
> 
> * can you please restructure the tutorial according to this **[Sample Tutorial](https://learn.figment.io/other/tutorial-guidelines/sample-tutorial-structure)**
> * Also seems like you forget to mention the addition of this tutorial in the main `SUMMARY.md` file so please update the `SUMMARY.md` file accordingly.

Yea @yash-sharma1 I added the entry to `SUMMARY.md` and also restructured a bit more to fit the template structure

2021-06-08 06:26 UTC, yash-sharma1 requested changes

2021-06-08 06:26 UTC, yash-sharma1 commented on network-documentation/secret/tutorials/deploy-your-own-secret-nft.md
> +* The latest version of NodeJS installed \(use of nvm, the node version manager, is _encouraged_ for web3 developers\)
It would be great if you can add links to the given required tools/software etc.
Also if we're going to install the secretjs package and dotenv later in the tutorial we can skip from including them here, nad if not then you can add instructions/commands to install them before we proceed further.

2021-06-08 06:26 UTC, yash-sharma1 commented on network-documentation/secret/tutorials/deploy-your-own-secret-nft.md
> +If it went well, you should see something like this;
What if it doesn't go well 🤔, can we add basic troubleshooting steps that can cause any error at this moment and how we can resolve it. Something like this - 
![image](https://user-images.githubusercontent.com/44340561/121133284-c8193980-c84f-11eb-94ce-95c9e8c0d6ed.png)

2021-06-08 06:26 UTC, yash-sharma1 commented on network-documentation/secret/tutorials/deploy-your-own-secret-nft.md
> +snip721 Reference Implementation: https://github.com/baedrik/snip721-reference-impl
At the end please add this -
If you had any difficulties following this tutorial or simply want to discuss anything technical with us you can [join our community](https://discord.gg/fszyM7K) today!

2021-06-08 06:40 UTC, floAr commented on network-documentation/secret/tutorials/deploy-your-own-secret-nft.md
> +## Wrap up
Quick question to this: Current structure is
# Deploy your very own secretNFT
## Introduction
## Prerequisites 
...
## Conclusion


Your suggest is that it is changed into:
# Deploy your very own secretNFT
# Introduction
# Prerequisites 
...
# Conclusion
?

Looking at the other tutorials they all follow the current approach (H1 for title and H2 for each section)

2021-06-08 06:58 UTC, yash-sharma1 commented on network-documentation/secret/tutorials/deploy-your-own-secret-nft.md
> +## Wrap up
Yeah, old tutorials have some formatting issues, but new ones should follow the Sample Tutorial Structure which has H1 for title and section headings and H2 for in-section subheadings

2021-06-08 17:19 UTC, yash-sharma1 approved these changes

2021-06-08 17:23 UTC, merged