Create, Mint and Transfer NFTs with the Avalanche Wallet
figment-networks/datahub-learn pull request #127
Opened 2021-06-15 07:16 UTC by Devilla

- [ ] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [ ] I've followed the [template structure](Structure).
- [ ] I've proofread the tutorial for spelling and grammar mistakes.
- [ ] I've ran a linter & prettifier to format my code blocks.
- [ ] I've thoroughlly explained the code, with inline code comments and text explanations.
- [ ] I've ran the tutorial and the code works.

2021-06-15 07:18 UTC, Devilla commented
@pyr0gan updated as per requirements. Thanks.

2021-06-15 18:00 UTC, pyr0gan requested changes
Thank you for resubmitting, I believe we can merge once you complete these changes.

2021-06-17 04:45 UTC, Devilla commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +## Prerequisites
okay

2021-06-17 05:30 UTC, Devilla commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +[Devendra Yadav](https://github.com/devilla)
Is it optional? @pyr0gan

2021-06-17 15:48 UTC, pyr0gan approved these changes
Thank you for fixing the image links!

2021-06-17 15:49 UTC, merged

2021-06-17 17:13 UTC, Devilla commented
> Thank you for fixing the image links!

pleasure!