Matic word replaced with Polygon (Matic) in DH Docs (Please review carefully)
figment-networks/datahub-learn pull request #131
Opened 2021-06-18 16:56 UTC by yash-sharma1

This PR contains changes in DH Docs where repetition of the word "Matic" replaced by "Polygon (Matic)" These changes majorly are in headings, sub-headings, sentences, still please review thoroughly to avoid replacement of words at an incorrect place like in code/library, etc.

2021-06-19 22:07 UTC, pyr0gan requested changes
Take a look, let me know what you think. At least from my perspective, reading Polygon (Matic) _every_ time is a bit much. I tried to make it sensible ⭐

2021-06-19 22:07 UTC, pyr0gan commented on network-documentation/matic/tutorials/untitled.md
> +This tutorial is a brief introduction on how to transfer tokens between Ethereum and Polygon (Matic) on PoS bridge using _**matic.js SDK and Metamask**_. Polygon (Matic)-Ethereum bridge provides a cr
> This tutorial is a brief introduction on how to transfer tokens between Ethereum and Polygon (formerly Matic Network) on PoS bridge using _**matic.js SDK and Metamask**_. The Polygon-Ethereum bridge provides a cross-chain channel through which users can transfer tokens from Ethereum to Polygon and vice-versa. More details on using the bridge can be found [here](https://docs.matic.network/docs/develop/ethereum-matic/pos/getting-started). **This tutorial mainly focuses on using the bridge from a front end perspective**. We will be using Metamask for this purpose.

2021-06-19 22:07 UTC, pyr0gan commented on network-documentation/matic/tutorials/untitled.md
> +The most important thing to be understood from this tutorial is the **proper usage of the web3 provider in the matic.js instance** we create. Whether using PoS or Plasma, certain actions need to be p
> The most important thing to be understood from this tutorial is the **proper usage of the web3 provider in the matic.js instance** we create. Whether using PoS or Plasma, certain actions need to be performed on Polygon and some on Ethereum. Due to this reason, **different providers are required in different scenarios. Hence correctly setting the providers is very necessary.**

2021-06-19 22:07 UTC, pyr0gan commented on network-documentation/matic/tutorials/untitled.md
> +Once deposited, the token can be transferred to any other account on the Polygon (Matic) chain.
Once deposited, the token can be transferred to any other account on the Polygon chain.

2021-06-19 22:07 UTC, pyr0gan commented on network-documentation/matic/tutorials/untitled.md
> +If you had any difficulties following this tutorial or simply want to discuss Polygon (Matic) and DataHub tech with us you can [join our community](https://discord.gg/Chhuv5zHy3) today!
> If you had any difficulties following this tutorial or simply want to discuss Polygon (formerly Matic Network) or DataHub tech with us, you can [join our community](https://discord.gg/Chhuv5zHy3) today!

2021-06-19 22:07 UTC, pyr0gan commented on network-documentation/network-guide.md
> +Polygon (Matic) Network is a sidechain-based scaling solution for public blockchains. It is based on an adapted implementation of Plasma framework. Polygon (Matic) provides scalability while ensuring
> Polygon (formerly Matic Network) is a sidechain-based scaling solution for public blockchains. It is based on an adapted implementation of Plasma framework. Polygon provides scalability while ensuring a superior user experience in a secured and decentralized manner. It has a working implementation for Ethereum. Polygon intends to support other blockchains in the future which will enable it to provide interoperability features alongside offering scalability to existing public blockchains.

2021-06-20 13:28 UTC, yash-sharma1 commented
@pyr0gan actually we just need to replace "Matic" exactly with "Polygon (Matic)" as per their team asked.

2021-06-21 16:15 UTC, merged