chore: How to Build a Decentralized Autonomous Organization (DAO) on …
figment-networks/datahub-learn pull request #141
Opened 2021-07-10 15:58 UTC by emmaodia

…Celo (#1)

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines). If you don't follow those guidelines it might take longer for us to review.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [x] I've followed the [template structure](Structure).
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've ran a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've ran the tutorial and the code works.

2021-07-12 17:13 UTC, pyr0gan commented
Good start, I would perhaps word the introduction a little differently - but you get the point across 😄 
Will you be filling in the rest of the material this week?

2021-07-13 18:51 UTC, pyr0gan reviewed
@emmaodia Please look over my review so far. I still have to cover parts 3 and 4. As this is quite a code-heavy tutorial, we will have to be careful how we present it.

2021-07-13 18:51 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/part-2.md
> +An external function that we can call in our dApp to add a new Proposal, it declares three parameters: `description`, `charityAddress` and `amount`.
Unfortunately referring to line numbers doesn't really work out the way we'd like in this context. I have rewritten it slightly, I think this still conveys the point. Thoughts?

> `createProposal` is a function that interacts with blockchain state, which we can call in our dApp to add a new Proposal, it accepts three parameters: `description`, `charityAddress` and `amount`.

> The function visibility is specified as external for economy of gas, which is also why the description will be contained in calldata. Memory allocation is expensive in terms of gas used, while reading from calldata is not. Also notice the `onlyStakeholder` modifier in use here, only accounts listed as Stakeholders can successfully call this function.

> First a new identifier is set - the `proposalId`, which will be the existing number of proposals incremented by one. Next, we declare a proposal variable of the CharityProposal type using the storage keyword to make sure the state variable is maintained, then assign its reference to one of the buckets in the `charityProposals` mapping. 
> The remainder of the function assigns the necessary values to their counterparts in the CharityProposal object. `payable()` helps us by [converting the address literal](https://docs.soliditylang.org/en/v0.8.6/080-breaking-changes.html?highlight=payable#new-restrictions) into a payable address. 

> Finally, the `NewCharityProposal` event is emitted.

2021-07-13 18:51 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/part-2.md
> +The `vote()` function is an external function that allows voting on proposals when called with the proposal’s id and a second true/false argument depending on whether the vote is in support or agains
> The `vote()` function is an external function that takes a proposalId and a second boolean (true/false) argument depending on whether the vote is in support or against the proposal.

2021-07-13 18:51 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/part-2.md
> +`votable()` is called in the `vote()` function. It is used to verify if a proposal can be voted on.
> `votable()` is called within the `vote()` function. It is used to verify if a proposal can be voted on.

2021-07-13 18:51 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/part-2.md
> +
Please remove the double linebreaks from all code blocks in the document.

2021-07-13 18:51 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/part-2.md
> +This function makes payment to a Charity after the voting period of the proposal has ended. It takes the proposal id as an argument and gets the proposal from the mapping. Line 95-101 checks if the c
> `payCharity` handles payment to the specified address after the voting period of the proposal has ended. It takes the proposalId as an argument and retreives that proposal from the mapping. We check whether the charity has already been paid or if the number of supporting votes is less than those against. If either of these conditions are true then the transaction will be reverted with an error message. If not, the paid property of the proposal is set true, the address of the stakeholder making the payment is set, and finally emit the PaymentTransfered event for logging purposes and transfer the payment to the charity address.

2021-07-13 18:51 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/part-2.md
> +function makeStakeholder(uint256 amount) external {
The indentation looks a little funky here. Did you run a linter on this?

2021-07-13 18:51 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/part-2.md
> +**Now that we have written the Smart Contract Code, the next step is to build the React Native App.**
A few sentences to recap what was covered so far would be great. I will review the other parts of this document today, we can get right to work on refining the content together 😄 

@emmaodia Good work so far, we can definitely have this polished up and ready to go fairly soon I would think. I am also available on Discord if you prefer to discuss some aspects of the tutorial synchronously. Tag me back in a comment once you've gone over my suggestions 😃

2021-07-15 03:31 UTC, emmaodia commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/part-2.md
> +**Now that we have written the Smart Contract Code, the next step is to build the React Native App.**
Thank you @pyr0gan ! 🙂
Your reviews and rewrites for some of the sections are apt and super helpful!
Yes, we want it ready to go so that we can get to contribute more knowledge resources. @segun-ogundipe
We have gone over the sections you highlighted and resolved about 98% of them.

2021-07-16 21:02 UTC, pyr0gan reviewed
See my review comments for suggested edits. I think part 4 is a little lacking, as it is mainly code with no explanation. See my comment there about making a project repo for this tutorial. 

🌞

2021-07-17 00:07 UTC, emmaodia commented
> See my review comments for suggested edits. I think part 4 is a little lacking, as it is mainly code with no explanation. See my comment there about making a project repo for this tutorial.
> 
> 🌞

Yes, we actually have a [repo](https://github.com/PhoenixTechAfrica/Tutorials) opened to curate all tutorials we submit to figment. @pyr0gan

2021-07-17 01:39 UTC, emmaodia commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/part-3.md
> +<img src="./images/create-proposal.jpeg" alt="drawing" width="300"/>
This syntax allows us to set the image size. @pyr0gan

2021-07-27 06:30 UTC, emmaodia commented
Hi, @pyr0gan I can finally say that this is complete. 😄
Thank you for your reviews. Do kindly take a look at Part 4 and let's know your thoughts.
Looking to close this out and then get to write new articles. Thank you.

2021-07-30 02:50 UTC, emmaodia commented
> I'll review it tonight, thanks! Got a little wild with the Polygon launch this week and didn't circle back to this, but I'll make sure we get this merged soon 💪
Oh... Yes, I read about the Polygon launch on Discord. Congratulations! 🎉 
Thank you. Looking forward to having it become a resource for users! 🚀

2021-08-03 00:21 UTC, pyr0gan reviewed
I'm not entirely sure about cutting down part 4 so drastically. I know that I said it was code-heavy, but now it feels .. incomplete, next to the other tutorials. I'm going to give it a review, hopefully I can clarify some of the things we'd like to see explained further!

2021-08-03 02:27 UTC, pyr0gan requested changes
Wrap up the outstanding issues and I think we have a final draft! @emmaodia

2021-08-03 02:27 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +**In this tutorial, you will learn how to build a functioning Charity DAO. The smart contract code is deployed on the Alfajores testnet. The contract allows its members to contribute to the DAO. Memb
I recommend shifting the emphasis of this paragraph and altering the wording:

> In this tutorial, you will learn how to construct a functioning Charity DAO. The smart contract code is deployed on the Alfajores testnet of the Celo network. The contract allows its members to contribute to the DAO. Members can initiate charity proposals which Stakeholders will have to vote on within a specified period of time. After that time has elapsed, the DAO contract will disburse the pooled funds.

2021-08-03 02:27 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +- The Alphajores Wallet, which will need to be funded using the [faucet](https://celo.org/developers/faucet)
Alfajores 😉

2021-08-03 02:27 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +We will cover the project in three parts::
Extra colon

As per my general review comment about naming the parts individually, instead of with numbers: I think these are also appropriate titles. If you would like to keep these, just refer to them by name throughout the documents instead of as "part 2", "part 3", "part 4" 😄 🚀

2021-08-03 02:27 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +## Features
I believe this can be at H1 👍

2021-08-03 02:27 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +The functionality of the app includes:
> The functionality of the dApp includes:

2021-08-03 02:27 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +* Users contribute Celo to become Contributors of the DAO
> - Users send Celo tokens to the DAO to become Contributors

2021-08-03 02:27 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +* Only a stakeholder of the DAO can vote on proposals.
> - Only a Stakeholder of the DAO can vote on proposals.

2021-08-03 02:27 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +* A newly created proposal has a date when voting on it closes.
> - A newly created proposal has an ending date, when voting will conclude.

2021-08-03 02:27 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +* Once the expiry date for voting on a Proposal closes, a stakeholder then pays out the requested amount to the Charity.
> - Once a Proposal's expiry date passes, a Stakeholder then pays out the requested amount to the specified Charity.

2021-08-03 02:27 UTC, pyr0gan commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +Writing the Smart Contract Code.
We can add links to each tutorial after it has been published on GitBook, however it may be easier (and nicer for the reader) if we just add a little more explanation here: 

> Writing the DAO Smart Contract in Solidity, where we go over the methods used.
> Building the React Native App, in which we show you how to quickly put together a mobile app interface.
> Connecting the React Native App to the Smart Contract using Redux, which brings it all together and allows our mobile dApp to utilize Celo efficiently.

I admit it's a tiny bit of editorializing, but try it out, see how it sounds to you 😄

2021-08-04 08:42 UTC, emmaodia commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/part-3.md
> +BBefore we move on to the Create Proposal screen, we can add data input and validation logic for the input fields on the form.
😂 It goes to show the depth of attention that you pay to details. Great work!

2021-08-04 08:54 UTC, emmaodia commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/part-4.md
> +The [first part](./introduction) of the tutorial serves as the foundation which explains what the rest of the project is about. It opened by explaining what is a Decentralized Autonomous Organization
OK. That is a good recommendation. Given that you have tried it out on Gitbooks, we will go ahead and make the changes to reflect your suggestions. Edits made.

2021-08-04 08:57 UTC, emmaodia commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +## What is a DAO?
Great! Also noted for future references.

2021-08-04 09:00 UTC, emmaodia commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +- The Alphajores Wallet, which will need to be funded using the [faucet](https://celo.org/developers/faucet)
An eye for the details! Nice! 👍

2021-08-04 09:09 UTC, emmaodia commented on network-documentation/celo/tutorial/celo-complete-dao-dapp/introduction.md
> +We will cover the project in three parts::
Updated and reverted to using the sentence titles as against parts naming.

2021-08-05 20:13 UTC, pyr0gan approved these changes
Thanks, and thank you for your hard work on this over the last month. Apologies for taking so long on this, but because it's a large topic and several tutorials I wanted to be sure we got it right!

I'll likely merge this tonight or tomorrow. If there are any formatting issues I will just fix them in realtime on the GitBook, once we publish.

Thanks again! 🙏 😄

2021-08-06 08:40 UTC, emmaodia commented
> Thanks, and thank you for your hard work on this over the last month. Apologies for taking so long on this, but because it's a large topic and several tutorials I wanted to be sure we got it right!
> 
> I'll likely merge this tonight or tomorrow. If there are any formatting issues I will just fix them in realtime on the GitBook, once we publish.
> 
> Thanks again! 🙏 😄

It is our pleasure @pyr0gan Thank you for taking the time to review and provide feedback on the article. It is truly a delight working with you! Cheers to more! 🥂

Cc: @Segun-Ogundipe

2021-08-12 14:06 UTC, merged