Create a token on Solana
figment-networks/datahub-learn pull request #143
Opened 2021-07-23 18:05 UTC by jacobmakarsky

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines). If you don't follow those guidelines it might take longer for us to review.

- [/] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [/] I've followed the [template structure](Structure).
- [/] I've proofread the tutorial for spelling and grammar mistakes.
- [/] I've ran a linter & prettifier to format my code blocks.
- [/] I've thoroughly explained the code, with inline code comments and text explanations.
- [/] I've ran the tutorial and the code works.

2021-07-28 16:13 UTC, pyr0gan reviewed
Hi @jacobmakarsky! 😄 I will be reviewing your pull request for a Solana token tutorial today and we can get it on track for publishing on Learn.

2021-07-29 22:56 UTC, pyr0gan requested changes
Hi @jacobmakarsky, have a look at my suggestions and commit your changes. We should be able to get this merged early next week if you're quick 😄 👍

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +	* You can enter a passphrase or just skip ahead and leave it empty.
It would be better to include a code block with the expected output of the command. Example:

```text
Generating a new keypair

For added security, enter a BIP39 passphrase

NOTE! This passphrase improves security of the recovery seed phrase NOT the
keypair file itself, which is stored as insecure plain text

BIP39 Passphrase (empty for none): 
```
_Then point out_ that they can leave it blank or provide a passphrase. Next, provide a _visual_ example as opposed to a concrete one (I have subtly edited the pubkey and mnemonic in this example to render them unuseable) :

```text
Wrote new keypair to /Users/username/.config/solana/id.json
================================================================================
pubkey: HGyaDBe8xb4zGDdZmxWpey5C6D8Esdp7kCs6Vc4bJ6z2
================================================================================
Save this seed phrase and your BIP39 passphrase to recover your new keypair:
still auto damp sphere silly remain first utility announce material luxury robe
================================================================================
```

This helps avoid confusion down the line 😄

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +We will now use the *pubkey* that was returned above to fund our wallet with SOL. The SOL is needed to pay for any changes we make to the blockchain, for example, the transaction that creates our tok
> We will now use that *public key* (pubkey) to fund our wallet with SOL. The SOL is needed to pay for transactions and any changes we make to the blockchain, for example, the transaction that creates our token.

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +* I will be sending 0.1 SOL to this wallet from a [Sollet](https://chrome.google.com/webstore/detail/sollet/fhmfendgdocmcbmfikdcogofphimnkno?hl=en) browser wallet, where I have SOL already. You can g
Not sure it is necessary to tell readers how you're doing it, we want to explain to them how they can do it. I suggest this :

> It is possible to get SOL through an exchange, such as [FTX](https://ftx.com/en), or by swapping tokens on [Serum](https://projectserum.com/#/).

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +solana balance pubKey
I would either provide the visual example from the terminal output as I suggested earlier, or make it clearer that pubKey needs to be replaced with a working public key. Readers will not make this distinction quickly, and would quite likely try to run the command `solana balance pubKey` and get an error.
Putting it in angled brackets `<pubKey>` makes it slightly more identifiable as a variable. I believe a visual example is best, such as :

```text
solana balance HGyaDBe8xb4zGDdZmxWpey5C6D8Esdp7kCs6Vc4bJ6z2
``` 

We want to get the point across to readers quickly, but we also need to be clear 👍

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +After running this command, congrats! You have created your own token on Solana. But we can't stop here; there is so much more we can do with this.
> After successfully running this command, you have created your own token on Solana. There is much more you can do with this.

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +spl-token create-token
It would be good to cover the terminal output for success as well as failure. I don't have any SOL to do it with..

```text
Creating token Dq9yptnkZrPf7fNpLoxfni6G84cUTfeWPuGc4HRK3KRQ
Fee payer, HGyaDBe8xb4zGDdZmxWpey5C6D8Esdp7kCs6Vc4bJ6z2, has insufficient balance: 0.0014716 required, 0 available
```

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +Your balance should be lower, indicating something happened. We paid for our token to be officially created 👍
> Your balance will decrease, indicating the transaction fees and deployment cost have been paid. The token is officially created 👍

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +## Introduction
All top level headings should be H1. A single \# instead of \## 👍

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +## Prerequisites
Top level heading @ H1 😄

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +## Requirements
Top level heading, please and thanks 👍

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +### **1) Create an SOL wallet**
This can be bumped up to H2 (\## instead of \###) 👍

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +spl-token create-account tokenAddress
As I mentioned in a previous comment, providing a visual example of commandline arguments is best to avoid confusion 😁

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +It's time to mint some tokens and send them around. For the mintAmount, I chose 1,000,000 for fun. This would be based off how big you expect your market cap to be.
> It's time to mint some tokens and practice transferring them around. For the mintAmount, you can specify any number. Why not try 1,000,000 just for fun? Normally this would be based on factors like how big you expect the tokens market cap to be and if you plan to airdrop any amount.

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +* Mint some tokens
I think this reads better as simply "Mint tokens".

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +spl-token mint tokenAddress mintAmount recipientAddress
Visual examples please and thanks! 😁

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +The recipientAddress would be the account you created to handle the tokens.
If you do provide an example, this sentence would become unnecessary.

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +Note: If you are lost on what any of these terms mean, refer to the note at the top of the page, which reminds it's always possible to use the **--help** command for more information.
> Remember, If you are lost on what any of these commands do or how to use them, it's always possible to use the **--help** flag with any of the Solana CLI tools to get more information.

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +Go ahead and check the wallet balance after this transaction if you'd like. Once your tokens have finished minting, it's time to think: What's stopping me from minting an infinite amount?
> Go ahead and check the wallet balance after this transaction if you'd like. Once the tokens have finished minting, it's time to think about security: What's stopping me from minting an infinite amount of these tokens?

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +It is crucial to prevent infinite minting of our token, once you have minted as much as needed.
> It is crucial to prevent infinite minting of our token, once enough has been created.

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +This will show the mint authority, which should match the pubkey of your wallet. The new mint authority should now be disabled.
This will show the mint authority, which should match the public key of your wallet. The new mint authority should now be disabled.

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +You should now see your token with the balance matching how much you minted. Check the wallet balance too if you'd like, which will show the difference after the transaction.
I think it's still preferable to show a visual example of terminal output.

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +I cloned the repository to my desktop.
Please provide a slightly more detailed explanation of where users can clone the code repository to on their local machine. Perhaps mention the users home directory?

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +* While still inside the token-list folder in the command line, set the url of your locally cloned token-list folder to the forked repository, for example:
I think we can take a couple more sentences to explain this better. It's a really sketchy explanation as it is. I'm happy to work with you on this, however I think we need to polish it up a little even if you're going for "quick 'n dirty" here.

2021-07-29 22:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +We have built our own token on the Solana blockchain. Feel free to continue experimenting by attempting to mint more of the token, sending the token around to other wallets, creating a market for it,
> In this tutorial, we built our own token on the Solana blockchain using Solana's command-line interface or "CLI". Feel free to continue experimenting by attempting to mint more of the token, sending the token around to other wallets, creating a market for it, making a [liquidity pool](https://raydium.io/liquidity/) on Raydium, etc. Check back in the future for a tutorial on how to make a [non-fungible token](https://www.blockchain-council.org/blockchain/a-quick-guide-to-fungible-vs-non-fungible-tokens/) on Solana as well.

2021-08-02 23:29 UTC, jacobmakarsky commented
Hello, I've made all the requested changes + added some better explanations based off your review. Thank you 👍

2021-08-03 02:28 UTC, pyr0gan commented
> Hello, I've made all the requested changes + added some better explanations based off your review. Thank you 👍

Thanks @jacobmakarsky I will re-review it now 😄

2021-08-03 03:16 UTC, pyr0gan requested changes
It's rare that typos sneak past me. Pretty sure we got 'em all this time!  
Just a few touchups and we should be good, thanks for making it an easy to follow tutorial 😄

2021-08-03 03:16 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +* While still inside your ```token-list``` folder in the command line, set the url of your local repository to your forked version on Github
FYI: You can get preformatted text with single backticks around text. \`keyword\` becomes `keyword`. Triple backticks are for multiline code highlighting. Save your fingers a few keystrokes 👍

2021-08-03 03:16 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +* While still inside your ```token-list``` folder in the command line, set the url of your local repository to your forked version on Github
Might be good to also point out here that the username in the URL has to match their GitHub username.

2021-08-03 03:16 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
>  * Go to the [pull requests page](https://github.com/solana-labs/token-list/pulls)
> * Go to the token list [pull requests page](https://github.com/solana-labs/token-list/pulls)

2021-08-03 03:16 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
>  * Select your forked repository from the **head repository** dropdown list
Screenshots would be great. I know most people can follow along just fine with the text, but some people are visual learners and would appreciate the examples so they know what to look for! 😄

2021-08-03 03:16 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
>  Woohoo! If you made it through all the steps, you have succesfully created your own token on the Solana blockchain. If you completed the bonus, you now have a tradeable token 👍
successfully and tradable 😉

2021-08-03 03:16 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +* Special thanks to [pyR0gan](https://github.com/pyr0gan) for thoroughly reviewing this tutorial before posting 🙏
Hey, I love a good credit where credit is due but this is probably unnecessary ❤️

2021-08-05 15:21 UTC, jacobmakarsky commented
Hello, I made all the necessary changes 👌

2021-08-05 19:56 UTC, pyr0gan reviewed
Quick final polish and we should be good to merge 👍

2021-08-05 19:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +**NOTE:** If you do not have any SOL in your wallet to pay for the transaction, you will receive an error:
General note: please remove the .DS_Store files, these are not needed for the tutorial. You can add them to your local .gitignore 😄

2021-08-05 19:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +The `mint address` is the `tokenAddress` we used before. Go ahead and name the file `logo.png` or `logo.svg`. It looks like they prefer be either of those file types.
> The `mint address` is the `tokenAddress` we used before. Name the file `logo.png` or `logo.svg`, depending on if your logo is in raster or vector format. Solana prefers these two filetypes for logos.

2021-08-05 19:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +![tokenCreationPhoto](../../.gitbook/assets/createSOLToken.png)
I don't believe there is any need to redact information in this image. Can you make another one which is not redacted, please? 😄

2021-08-05 19:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +![mintingTokensPhoto](../../.gitbook/assets/mintSOLToken.png)
Not sure why you redacted here, either. You can share information which is already going to be public because it exists on a blockchain, and I think it will confuse readers to be confronted by a heavily redacted screenshot. Similar to above, please make another screenshot of the process which isn't redacted. Thanks! 😄

2021-08-05 19:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +* Add your token to the list like so:
Just occurred to me.. Maybe let people know to copy and paste an existing token from the end of the list to make sure they get all the fields. Also need to make sure that the comma is in the right place at the end of the token's containing object parentheses. Typos or malformed JSON would lead to delays in the Solana team merging a pull request, I imagine!

2021-08-05 19:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +My example token will be a social token, so make sure to not copy that unless yours is one too.
> This example token will be a social token, as mentioned in the `name` property.

2021-08-05 19:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +The link for the token image must be that exact format; just change the token address to your token address, and the logo filename to your logo filename and type.
> The token image URL must keep the exact format; only change the token address to your token address, and the logo filename to your logo filename and type (logo.png or logo.svg).

2021-08-05 19:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +![solPullRequest](../../.gitbook/assets/solPullRequest.png)
This image appears to be broken.

2021-08-05 19:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +![solCompareForks](../../.gitbook/assets/solCompareForks.png)
For these next few screenshots: The figment-networks/datahub-learn repo has no relation to the Solana token list. Could you navigate to that repository and re-take the screenshots please? It can be fairly confusing otherwise 😄

2021-08-05 19:56 UTC, pyr0gan commented on network-documentation/solana/sol-mint-token.md
> +Congratulations! Your token is now on the way to being official. Only if we could actually trade the token though...
> Congratulations, your token is now on the way to being official. It is also possible to create a market for your token on Serum, requiring some extra work and cost. Time for a bonus activity!

2021-08-06 12:17 UTC, guillaumegaluz commented
Hey @jacobmakarsky! Super excited to have this token on Learn. A few more changes and then we can publish and announce  it! It will be one of our first tutorials for Solana, community learners will love it!

2021-08-12 17:19 UTC, pyr0gan approved these changes

2021-08-12 17:19 UTC, pyr0gan commented
@jacobmakarsky I am going to merge this tutorial and make the fixes on GitBook. Apologies for the lag on this, we are coming up with a more specific review process so that future tutorials can be merged more rapidly.
Thank you for your patience and understanding! 😄

2021-08-12 17:19 UTC, merged

2021-08-12 23:19 UTC, jacobmakarsky commented
Oh jeez, sorry about that. I’m on vacation right now. More than willing to make the changes asap if they are needed as soon as possible. I wasn’t sure of how fast it needed done