How to write unit tests for smart contracts in avalanche
figment-networks/datahub-learn pull request #144
Opened 2021-07-26 07:56 UTC by Segun-Ogundipe

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines). If you don't follow those guidelines it might take longer for us to review.

- [*] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [*] I've followed the [template structure](Structure).
- [*] I've proofread the tutorial for spelling and grammar mistakes.
- [*] I've ran a linter & prettifier to format my code blocks.
- [*] I've thoroughly explained the code, with inline code comments and text explanations.
- [*] I've ran the tutorial and the code works.

2021-07-26 08:30 UTC, Segun-Ogundipe commented
Hi @yash-sharma1 @guillaumegaluz, this is the PR for the article on unit testing avalanche smart contract. PTAL.

Regards.

2021-07-28 09:27 UTC, yash-sharma1 commented
Hey @Segun-Ogundipe 
Thanks for showing your interest in contributing to Learn.
I couldn't find your name in the tutorial contributors list. 
Just to confirm, have you filled this form - https://bit.ly/learntutorial before making the PR and had a chat with any member of our team? :)

2021-07-28 13:16 UTC, Segun-Ogundipe commented
Thanks for the reply @yash-sharma1, I haven't filled the form but I sent a mail about this couple of weeks back. Guillaume said I could create a PR when it's ready.

Should I go ahead and fill the form still?

2021-07-28 16:15 UTC, pyr0gan commented
> Thanks for the reply @yash-sharma1, I haven't filled the form but I sent a mail about this couple of weeks back. Guillaume said I could create a PR when it's ready.
> 
> Should I go ahead and fill the form still?

@Segun-Ogundipe yes please, it helps us to keep track of our contributors! 😄 🚀

2021-07-28 21:54 UTC, Segun-Ogundipe commented
Form filled and submitted @pyr0gan. 😄

2021-07-30 01:26 UTC, pyr0gan requested changes
Hi @Segun-Ogundipe! Check out my suggestions, see what you think. Please tag me in a comment when you've pushed up another commit!

2021-07-30 01:26 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +What we are testing here is whether the `vote()` function fails as necessary when an address is used to vote twice. To do that, we instantiate the contract, vote for a candidate twice. the second cal
> What we are testing here is whether the `vote()` function fails as necessary when an address is used to vote twice. To do that, we instantiate the contract and call `vote()` for the same candidate twice. The second call to must fail for this test to pass. 

> To test the exception, we first get access to the function selector with `bytes4 selector = election.vote.selector;`, encode the selector with `bytes memory data = abi.encodeWithSelector(selector, uint256(0));` then make an external call with the returned data from the second step with `(bool success, ) = address(election).call(data);`, lastly we validate that the transaction failed with `Assert.isFalse(success, "Should be false");`

2021-07-30 01:26 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +There you go, I believe congratulations are in order. You made it to the end of this short but interesting article on writing unit tests for smart contracts in Avalanche!.
> Congratulations! You've made it to the end of this short but informative tutorial on writing unit tests for smart contracts in Avalanche!

2021-07-30 01:26 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +Though this article does its best to outline the steps involved in writing unit tests for smart contracts, nothing solidifies your knowledge in this new world of testing more than picking up some con
> Though this tutorial covers the basics involved in writing unit tests for smart contracts, nothing solidifies your knowledge of testing more than reading some existing code & coming up with test cases. It is also recommended to head over to the project repository on [Github][4]. The repo contains Javascript test files in case you're interested in writing test cases in Javascript.

2021-07-30 11:30 UTC, Segun-Ogundipe commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +## Introduction
Done 👍🏾

2021-07-30 11:33 UTC, Segun-Ogundipe commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +Test cases in Solidity are Solidity functions with one or more assert statements. As the case mapping in the [Breaking It Down](#breaking-it-down) section suggested, We instantiate a new Election con
😄

2021-07-30 11:36 UTC, Segun-Ogundipe commented
Hi @pyr0gan, really appreciate your effort. I have included the changes you suggested in the tutorial.
PTAL.

2021-07-30 17:11 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +Congratulations! You've made it to the end of this short but informative tutorial on writing unit tests for smart contracts in Avalanche!
It may be time to point out that what you're doing in this tutorial is not specific to Avalanche, but more specific to Solidity. What else were you planning to include in this tutorial to tie it in to Avalanche? I get that this is based on the contracts from the Avalanche tutorial you linked, but for the sake of keeping the learning as broadly appealing as possible, maybe we consider renaming the tutorial? Thoughts @Segun-Ogundipe ?

2021-07-30 17:33 UTC, Segun-Ogundipe commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +Congratulations! You've made it to the end of this short but informative tutorial on writing unit tests for smart contracts in Avalanche!
I totally agree with you. I thought about this too myself, I was thinking of adding a section on how to run the test cases on the fuji test net. I think I'll go with renaming the tutorial. Is that okay @pyr0gan?

2021-08-03 03:17 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +Congratulations! You've made it to the end of this short but informative tutorial on writing unit tests for smart contracts in Avalanche!
Yeah, totally! What title are you thinking of? 😄

2021-08-03 14:58 UTC, Segun-Ogundipe commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +Congratulations! You've made it to the end of this short but informative tutorial on writing unit tests for smart contracts in Avalanche!
Does this work: "How to Develop and Write Unit Tests for Solidity Smart Contract" @pyr0gan?

2021-08-03 15:32 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +Congratulations! You've made it to the end of this short but informative tutorial on writing unit tests for smart contracts in Avalanche!
> Does this work: "How to Develop and Write Unit Tests for Solidity Smart Contract" @pyr0gan?

If we keep it short: "Unit Testing in Solidity", it lets readers know right away what the topic is. We can explain the "How to" in the document itself, keeping the title impactful 😄

2021-08-03 16:53 UTC, Segun-Ogundipe commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +Congratulations! You've made it to the end of this short but informative tutorial on writing unit tests for smart contracts in Avalanche!
Cool, that's just perfect.
Should I go ahead and make the change then?

2021-08-03 17:38 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +Congratulations! You've made it to the end of this short but informative tutorial on writing unit tests for smart contracts in Avalanche!
Sure thing!

2021-08-03 19:05 UTC, Segun-Ogundipe commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +Congratulations! You've made it to the end of this short but informative tutorial on writing unit tests for smart contracts in Avalanche!
Done!!! @pyr0gan

2021-08-03 21:15 UTC, pyr0gan commented on SUMMARY.md
> +    > > > > > > > change title
It looks like you left some conflict markers in here. You'll need to delete them and make the changes to the title of your tutorial directly. This won't be as much of an issue once we launch Learn v2, but for the time being we still need to keep the SUMMARY.md somewhat sane. There are a lot of links in it!

Follow this page for how to resolve the conflicts: https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

2021-08-03 22:18 UTC, Segun-Ogundipe commented on SUMMARY.md
> +    > > > > > > > change title
I thought I got them all.
Thanks for the link to the docs. 😄  Can't wait for v2!!!

2021-08-03 22:43 UTC, pyr0gan approved these changes

2021-08-03 23:26 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +This tutorial builds on a previously written tutorial on avalanche, so before we proceed any further make sure to complete - [Making an advanced e-Voting dApp on Avalanche Fuji network using Truffles
In light of the title change, let's just explain why we are using the voting dApp on Avalanche 😄 

> This tutorial builds on another tutorial written for Avalanche, so before we proceed any further make sure to complete - [Making an advanced e-Voting dApp on Avalanche Fuji network using Trufflesuite][1]. The Avalanche C-Chain is compatible with the Ethereum Virtual Machine, so we are using the same Solidity code as that tutorial. What we are illustrating here is how to go about unit testing some of that Solidity code, but this is not specific to Avalanche. This learning can be applied to any Solidity code!

2021-08-03 23:26 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/avax-testing-truffle.md
> +Congratulations! You've made it to the end of this short but informative tutorial on writing unit tests for smart contracts in Avalanche!
There is a suggestion I made above, not strictly required before we publish and I can easily make the alteration in GitBook. Other than that, I believe this stands ready to go live. Thanks for all your work on this and attention to detail, we appreciate having more resources to share with the community!

2021-08-03 23:27 UTC, merged