Build a Social Media DApp & Deploy it on Polygon
figment-networks/datahub-learn pull request #153
Opened 2021-08-13 15:58 UTC by AkhileshThite

Hey @yash-sharma1 @guillaumegaluz, I've completed the tutorial  "[Build a Social Media DApp & Deploy it on Polygon](https://github.com/AkhileshThite/datahub-learn/blob/main/network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md)". Please check and update.
Thank you :)

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines). If you don't follow those guidelines it might take longer for us to review.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [x] I've followed the [template structure](Structure).
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've ran a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've ran the tutorial and the code works.

2021-08-17 15:26 UTC, yash-sharma1 commented
Hey @AkhileshThite 
Thanks for this quick and making this PR ready.
Can you please resolve the Branch conflicts and make separate PR's for each tutorial it'll be easy to track and review. Thanks

2021-08-17 15:33 UTC, AkhileshThite commented
> Hey @AkhileshThite
> Thanks for this quick and making this PR ready.
> Can you please resolve the Branch conflicts and make separate PR's for each tutorial it'll be easy to track and review. Thanks

Okay, sure.

2021-08-17 22:09 UTC, pyr0gan requested changes
Please look over my suggestions and make changes. Once all issues have been addressed, I will re-review and then we can look at merging, OK? 😄 

🙏 Thank you for your hard work on this tutorial. I know it is a lot of ground to cover.

2021-08-17 22:09 UTC, pyr0gan commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Create `.gitignore` file in the root dir of your project, put `node_modules` and `.env` files inside `.gitignore` file.
> Create a `.gitignore` file in the root dir of your project, put `node_modules` and `.env` on separate lines inside the `.gitignore` file and remember to save the file to disk.

2021-08-18 06:22 UTC, AkhileshThite commented
> Please look over my suggestions and make changes. Once all issues have been addressed, I will re-review and then we can look at merging, OK? 😄
> 
> 🙏 Thank you for your hard work on this tutorial. I know it is a lot of ground to cover.

Hey! Thank you for reviewing. I'll make the changes ASAP :)

2021-08-18 10:13 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +In this tutorial, I'll show you how to build a Social Media DApp (Decentralized Application) like YouTube & how to Deploy it on Polygon (Matic) Mumbai Test Network.<br>
[Fix](https://github.com/AkhileshThite/datahub-learn/commit/873e8293061a0f08dc060fd8de2fb121ccb556f0)

2021-08-18 10:15 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +*About this project: DTube was created by me during the ETHOdyssey Virtual Hackathon in July-Aug 2021. All the resources I used to create this DApp are linked at the bottom in the "References" sectio
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/405201a43d767871a04831c580c12e3eca8c9559)

2021-08-18 10:16 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +* Deploy the smart contracts on polygon (Matic) Mumbai Test Network.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/cc07aec4d815f507c93ec850dd2f75e89b848333)

2021-08-18 10:18 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +* Use truffle & MetaMask effectively.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/0a57f35ca34fa9d4671f2d060651041612a0f40d)

2021-08-18 10:20 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +*  Host the DApp on IPFS using Fleek platform.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/9daa13e60a6a4a3b59e5d670a0237b31eb45a3da)

2021-08-18 10:24 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +## About the Author
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/0cd6b46ba24e088294a8f5d1579af0c8cdf0f607)

2021-08-18 10:26 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +We need the following things on your computer to build our DApp.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/69691b5aaa6894d10a27583c788429a4fa761b7e)

2021-08-18 10:27 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +To install MetaMask extension, click on this [link](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=en).<br>
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/f000f4c21dd1736eaf55f82c1937bc3f238e6d4d)

2021-08-18 11:47 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +<div align="center"><img src="../../../.gitbook/assets/dtube.png" /></div>
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/a8879bb222fa74c74fa2a06bd1170d70c9990aee)
Sorry, I didn't know that .gitbook automatically aligns images to the center with the normal image Markdown.
* Removed all HTML tags from the document.
* .DS_Store conflicts resolved.

2021-08-18 11:50 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +To deploy the smart contracts on Matic we first have to create a Matic network in MetaMask wallet. `Settings -> Networks -> Add network -> Save`<br>
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/ad41812ae202c0a9cbb3aa6b342e477adceb4f79)

2021-08-18 11:54 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +First, we'll setup our coding environment with the help of **Truffle**, after that we'll write **Smart Contracts** in **solidity**.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/0dc2c44aea285625e64bb8ebc4fc6e28ffa4c73f)

2021-08-18 12:01 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +To connect our Smart Contracts with front-end we'll use **Web3.js** and then we'll deploy our Smart Contracts on **Polygon (Matic) Mumbai Test Network**. In the final step, we'll host this DApp on IP
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/dc43ffd364de7855e62aebdf87103cb4ea0f5a14)

2021-08-18 12:03 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +What is **Web3.js?**<br>
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/7af581c4a6a93a4776594b66809e3cfc59e1aca5)

2021-08-18 12:04 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +In this section, I introduced you to the basics of technology that we're going to use and roadmap of our DApp, now the interesting part. Let's make our DApp!
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/d8fa710150922255ce91b2d2f1680c617a31864b)

2021-08-18 12:06 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +To build the DApp without dealing with any annoying version errors & instead of installing each dependency one-by-one, we'll start building our DApp by installing all the necessary dependencies by cl
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/cd06604e99ca990a2a0c18f486d80b2fd5d1202d)

2021-08-18 12:09 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Clone/download the GitHub repository from https://github.com/AkhileshThite/DTube.<br>
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/c4075362175823379ad82cac8f500607d291347e)

2021-08-18 12:10 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +`cd [repo_name]` this command will open that repo you just copied from GitHub.<br>
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/56e1b6d154176f4faff162bc588bb0636b59376c)

2021-08-18 12:11 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Now, open the folder with your favorite IDE, I'm using VS Code.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/71dccd1ee2c9cfc3a0422921b766388012307cf6)

2021-08-18 12:41 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Install all the dependencies by the following command:<br>
I've made the changes as per your suggestions for this one and it looks good, you can check the previous fix.
I think the audience will be able to follow the flow because I've included the image after `git clone` and `cd DTube` commands, so that audience can quickly connect by seeing how the repo will look like after opening it in their IDE.
Let me know your thoughts

2021-08-18 12:44 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +*I'll provide a **path** and GitHub **repo link** on top of each section of the tutorial, so you don't need to scroll.*
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/a47f8ea8db7c825cbfe2f8172895ff059a04da1c)

2021-08-18 12:48 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Let's define the version of solidity and create a contract called DTube. Initially, we're saying that the video count is zero. `uint` means unsigned integer (Positive number) data type. `string` mean
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/d1e1b1d117103080ff3bfcc77142a68f2fdec89f)

2021-08-18 12:51 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Let's create a `uploadVideo` function with two arguments `_videoHash` and `_title`, inside the function we're making sure the `video hash`, `video title`, `uploader address` exists by using some cond
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/b554fe7aad81a0e6e7a9c72e1681088864889058)

2021-08-18 12:53 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Finally, we'll add the video to the contract by including `videoCount`,`_videoHash`, `_title`, `msg.sender`(which is a global variable in solidity, it simply means the current user) variables. Then w
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/abb5ce7b78100dee1df327679e05b6b052a9ff5b)

2021-08-18 12:57 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +*(We'll understand and see `truffle-config.js` at the time of deployment of our Smart Contracts.)*
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/6fb6d09508b95fc0095089433c36de126bcf10c8)

2021-08-18 12:58 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +**Migrations are JavaScript files that help you deploy contracts to the Ethereum network. These files are responsible for staging your deployment tasks, and they're written under the assumption that
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/5c5177cc3d069e5027f6eaf68727bd68fb3bc153)

2021-08-18 13:25 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +React applications are broken into components like for example navigation bar, main page, footer of the webpage. React loads a single HTML page (`/public/index.html`) which is connected with all the
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/6efbd5351d1cd05914f9b05bfd4c5ace7b2b16fd)

2021-08-18 13:26 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +First, let's import all the components, Web3 and declare IPFS.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/a0956e811dd09e1e514d51ec1de955168bb8d2b5)

2021-08-18 13:36 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +After that we're going to paste the exact default code which MetaMask instructs us to load web3. It takes Ethereum provider from MetaMask and injects it to your DApp, if your browser does not have Me
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/c4bd15460d70b2238215b296f91ccf2d6b57af76)

2021-08-18 13:42 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Now we're going to prepare the file for upload to IPFS by `captureFile` function.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/87d25f390faef84dc1be4d926217e25b0ec1381f)

2021-08-18 13:44 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Let's upload the file to IPFS by `uploadVideo` function. While uploading a video file to IPFS it'll show a message in the console "Submitting file to IPFS...". Here, we're adding the file to IPFS wit
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/a7df07f1ad6f5ca919f4b1e1fc57b5e46f0074ea)

2021-08-18 13:45 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +The bind() is an inbuilt method in React that is used to pass the data as an argument to the function of a class based component.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/0b62c6eaaf81f0559415c8727324d842bb83df80)

2021-08-18 13:46 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +In Navbar, we're going to display the brand logo, brand name (DTube), user account address, and user profile (with identicon JavaScript library). First, let's import the identicon.js and brand logo.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/0afe70f996752ba0b96e4b44776ce3c4e2229559)

2021-08-18 13:48 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +We're displaying the user address in this component by `this.props.account` method. The following code snippet says that, If the user account address exists, then show the identicon user profile.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/1793ad0cf7bcbbeab88bdfcef915edf14e8d5352)

2021-08-18 13:51 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +To display the current uploaded video & title of the video we're going to use `this.props.currentHash` & `this.props.currentTitle` methods. Now, why we're using `https://ipfs.infura.io/ipfs/` here? W
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/4dd7bbce68d710af4ae0e57a8bb5624ed0afdb87)

2021-08-18 13:53 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Now, we're going to create a form in the video feed to choose the video file, input the title of the video, and upload the video. First, we're going to choose the video file, which will process to up
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/1d76993b2ea8cad3eb437afa4b7954cbe4d5651b)

2021-08-18 13:55 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Finally, to list out all the previously uploaded videos with their title in the video feed we'll create `video.hash` and `video.title` methods. Whenever we click on any listed/previous videos the `ch
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/ba3e7c0466c937242b992d1adf7d9f751675993d)

2021-08-18 13:58 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +truffle-config file is the main and the most important file of your DApp which interacts with everything. In this file, you can mention the path of your solidity file (smart contracts), ABI's, and de
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/4651d350d4522e43d598ed8b7d844682bfb67c04)

2021-08-18 13:59 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Make sure you create `.env` file in the root dir and paste mnemonics (12 secret words) of your MetaMask wallet with variable name MNEMONIC (give any name).
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/2440203c0246899195abee6886a50fe223d03f03)

2021-08-18 14:05 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Now, let's add `matic` network in our truffle-config file which will contain our environment variable MNEMONIC and RPC URL.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/f6151ca511740f80a220c43cddcffed1155cece6)

2021-08-18 14:09 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +You can set the gas price and gas limits for faster transactions by adding
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/b5bba8d20f5dafa22fd6f4b8ed4dda7766352598)

2021-08-18 14:10 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +```javascript
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/7407430e33c77d69329df2edb82d473733f101b1)

2021-08-18 14:12 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +**IMPORTANT:- If you are dealing with any errors while deploying the Smart Contracts to Polygon (Matic) then check out the "Dealing with different errors" section of [Deploying and Debugging the Smar
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/2880c7028c04066e36370ac1dddf0184979137b0)

2021-08-18 14:13 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +let's run the react app on http://localhost:3000/ by `npm start` command. First, you'll see a MetaMask pop up to `connect` your MetaMask wallet. Now you can upload and share videos on your DApp which
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/bb93c02102cd02e3c14e8c6e05c20aa732fff166)

2021-08-18 14:14 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Create `.gitignore` file in the root dir of your project, put `node_modules` and `.env` files inside `.gitignore` file.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/4f463747f2763150f208ac23101e19285c1ef974)

2021-08-18 16:29 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +```javascript
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/795950ef9410b5ad980708bff4952faddd922927)

2021-08-18 16:49 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +class App extends Component {
Sir, I'm not a pro in React. Extending a component allows us to pass props right?
I'm afraid to make any changes because everything is working perfectly fine on this code (DApp is working). If I make any changes here, then I've to change the same in the original repository of the DApp also.

2021-08-18 17:07 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +React components has a built-in state object. The state object is where you store property values that belongs to the component. When the state object changes, the component re-renders. We'll use `th
I'm not aware of any modern techniques, maybe because I learnt from old YouTube tutorials and docs, But I tried my best to explain this technique in a simple way.
In react docs they're showing, both ways are vlid here is the [link](https://reactjs.org/docs/components-and-props.html).

2021-08-18 17:18 UTC, AkhileshThite commented
Hey @pyr0gan, I've fixed all the issues. I replied to every review comment with commit links so that it'll be easy for you to review the changes.
Thank you!

2021-08-19 15:48 UTC, pyr0gan commented
> Hey @pyr0gan, I've fixed all the issues. I replied to every review comment with commit links so that it'll be easy for you to review the changes.
> Thank you!

Excellent, thank you! I will re-review today 😄

2021-08-20 18:33 UTC, pyr0gan approved these changes
Thank you for the quick changes and attention to detail! I will merge this later today 😄 🚀

2021-08-20 18:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +class App extends Component {
Not to worry, we can publish the tutorial with class components. 😄

2021-08-20 18:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +React components has a built-in state object. The state object is where you store property values that belongs to the component. When the state object changes, the component re-renders. We'll use `th
You're right, it's still valid. There isn't any issue with using class components for this tutorial. 👍

2021-08-20 20:14 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +## Introduction
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/eb3b6c6ded76a741b754f6b4ff6baea21eebac9d)

2021-08-20 20:15 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +## After this tutorial you will be able to:
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/a202fb92cfbf85607e9b0ccd5549414338373a36)

2021-08-20 20:16 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +To install truffle open your `windows cmd prompt` or `mac terminal` and paste the following command.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/c2603bb75d5acada5a3bfa06e189941df62e05cb)

2021-08-20 20:18 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Build-a-Social-Media-DApp-and-Deploy-it-on-Polygon.md
> +Ganache is a personal blockchain environment for DApp development. It provides us 10 ETH accounts, each of them is funded with 100 ETH so you don't have to worry about anything.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/cfbd398d74b0e2595d9d1ca17b3b144bd66cca3e)

2021-08-20 20:31 UTC, AkhileshThite commented
> Thank you for the quick changes and attention to detail! I will merge this later today 😄 🚀

Thank you @pyr0gan sir, 
Made the necessary changes, can't wait to see this tutorial live. 😊

2021-08-25 03:40 UTC, pyr0gan approved these changes
👍  Thank you for making the changes, merging now.

2021-08-25 03:40 UTC, merged