Added new tutorial Substrate Kitties Nft
figment-networks/datahub-learn pull request #154
Opened 2021-08-16 16:09 UTC by SHA888

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines). If you don't follow those guidelines it might take longer for us to review.

- [ ] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [X] I've followed the [template structure](Structure).
- [X] I've proofread the tutorial for spelling and grammar mistakes.
- [X] I've ran a linter & prettifier to format my code blocks.
- [X] I've thoroughly explained the code, with inline code comments and text explanations.
- [X] I've ran the tutorial and the code works.

2021-08-17 23:41 UTC, pyr0gan requested changes
A very well written and laid out set of tutorials, thank you!

Check my comments for fixes (few and far between). It looks like the last tutorial is incomplete in this commit, so I'll re-review once that is done. Just tag me in a comment so I can come back around to it ASAP! 🙏

2021-08-17 23:41 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/03-substrate-kitties-nft/3.-uniqueness-custom-types-and-storage-maps.md
> +**HINT**: Remember to include a getter function for each storage item &mdash; except those handling indices) .
Looks like a lonely dangling parens over there ;)

So far so good, my only feedback at this point is to standardize the indentation for your code blocks, it's a little unruly in spots. Also, as previously mentioned try blockquote for the hints, tips, and notes sections, instead of triple-colons 😄

2021-08-17 23:41 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/03-substrate-kitties-nft/4.-dispatchables-and-events.md
> +## Next steps
Well written, so far this is a pleasure to read and a breeze to review.

2021-08-17 23:41 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/03-substrate-kitties-nft/5.-interacting-with-your-kitties.md
> +## Next steps
After reading these, my brain feels both enriched and depleted (but that's only because I'm reading it on like 3 levels at once).

Dense. Not *too* dense, but on the verge. I'm really enjoying everything so far, and I hope the community likes these tutorials as much as I do.

I'd just like to tag in @zurgl to review the Rust code, as I'm still just intermediate. I can read and follow the Rust code, but it isn't as clear to me as I'd like.

2021-08-17 23:41 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/03-substrate-kitties-nft/6.-kitties-front-end.md
> +Make sure you think about the props your passign in. We've done it for you.
Oh no! This document looks incomplete. I'll gladly re-review once you've had a chance to finish it up! 😄 👍

2021-08-17 23:41 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/03-substrate-kitties-nft/README.md
> +# 💡 Substrate Kitties NFT
I don't think we need a README.md. We can make sure to add the page links to the right places once we merge the PR. I typically do this manually just to ensure it all looks and reads smoothly post-merge 🚀

2021-08-19 01:33 UTC, SHA888 commented on network-documentation/polkadot/tutorials/02-substrate-tutorials/README.md
> +# 💡 Substrate Tutorials
Okay, roger that. Thanks @pyr0gan

2021-08-20 18:37 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/03-substrate-kitties-nft/6.-kitties-front-end.md
> +Make sure you think about the props your passign in. We've done it for you.
@SHA888 Have you had a chance to finish this document? 😄 If not, don't worry! I am just trying to plan around our Learn v2 launch next week. It would help greatly if I had a timeline for this.

2021-08-20 23:45 UTC, SHA888 commented on network-documentation/polkadot/tutorials/03-substrate-kitties-nft/6.-kitties-front-end.md
> +Make sure you think about the props your passign in. We've done it for you.
@pyr0gan Sorry for the delay, I need like a few more days to finish it, because I got a new job and also working on some existing hackathon projects so there a lot of stuff spinning around lol

2021-08-25 04:30 UTC, SHA888 commented
@pyr0gan I just pushed a new fix on it. Apologize for the long delay.

2021-08-25 04:45 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/03-substrate-kitties-nft/6.-kitties-front-end.md
> +Make sure you think about the props your passign in. We've done it for you.
@SHA888 no worries! We're here to help you get the tutorial published, not hassle you about it 😉. Just tag me in a comment when you're ready and we'll re-review 👍

2021-08-25 04:45 UTC, pyr0gan commented
> @pyr0gan I just pushed a new fix on it. Apologize for the long delay.

I see this, I will review it in the morning! Thank you 🙏

2021-09-02 17:03 UTC, pyr0gan commented
@SHA888 I'll be happy to re-review and merge this week when you can make the suggested changes 😄 🙏

2021-09-02 23:55 UTC, SHA888 commented
@pyr0gan I'll try to finish it by the weekend. I run through some deadlines at my work today. Sorry to hang you up on this and really appreciate your patience :pray:

2021-09-04 01:06 UTC, pyr0gan commented
> @pyr0gan I'll try to finish it by the weekend. I run through some deadlines at my work today. Sorry to hang you up on this and really appreciate your patience 🙏

Not rushing you. I do my best to get tutorials published quickly, which often turns into it taking longer than I was planning. This isn't about me, though. It's your tutorial and it will be complete when it is complete. Live in the moment! Enjoy your weekend, and we can merge this next week when it is ready 😄

2021-09-08 12:27 UTC, pyr0gan approved these changes
Thank you for making the changes 🙏

2021-09-08 12:27 UTC, merged

2021-09-08 17:42 UTC, SHA888 commented
@pyr0gan thank you for your thorough guidance :pray: