Deploying & Debugging the Smart Contracts on Polygon
figment-networks/datahub-learn pull request #155
Opened 2021-08-17 16:48 UTC by AkhileshThite

I've completed the tutorial "[Deploying & Debugging the Smart Contracts on Polygon](https://github.com/AkhileshThite/datahub-learn/blob/master/network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md)". Please check and update.
Thank you :)

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines). If you don't follow those guidelines it might take longer for us to review.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [x] I've followed the [template structure](Structure).
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've ran a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've ran the tutorial and the code works.

2021-08-17 22:36 UTC, pyr0gan requested changes
Thanks for splitting this off of the main tutorial, however it needs a bit of cleanup. Look over my suggestions and edit accordingly 👍 🙏

2021-08-17 22:36 UTC, pyr0gan commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +In this tutorial, I'll show you how to deploy smart contracts of your DApp to the Polygon (Matic) Mumbai Test Network.
> In this tutorial, we will cover how to deploy smart contracts to the Polygon (Matic) Mumbai test network.

2021-08-17 22:36 UTC, pyr0gan commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +I'll cover all the possible errors which I faced during the deployment.
> We'll cover some of the possible errors which might occur during the deployment.

2021-08-17 22:36 UTC, pyr0gan commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +# Deploying & Debugging the Smart Contracts on Polygon
General comments:
- Please remove all HTML tags from the document, only use Markdown 👍

2021-08-17 22:36 UTC, pyr0gan commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +## About the Author
This section can be moved to the end of the document.

2021-08-17 22:36 UTC, pyr0gan commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +## truffle-config
This is repeated from the other tutorial. Is it necessary here?

2021-08-17 22:36 UTC, pyr0gan commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +## Dealing with different errors
Consider renaming this heading to "Deployment errors and solutions"

2021-08-17 22:36 UTC, pyr0gan commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +```javascript
Doesn't need to be JS syntax highlighting. Consider plaintext instead, or simply leave the syntax highlighting specifier out (just use backticks).

2021-08-17 22:36 UTC, pyr0gan commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +Change `https://rpc-mumbai.matic.today` by using [Infura custom RPC](https://infura.io)
> Change the RPC endpoint URL in Metamask from 'https://rpc-mumbai.matic.today' to an [Infura RPC endpoint](https://infura.io). This will require you to register for an Infura account and set up a Project, to get a Project ID. If you already have an Infura project ID, add it to the `.env` file => `PROJECT_ID=<your project ID>`

2021-08-17 22:36 UTC, pyr0gan commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +If still dealing with error, try this 2nd fix.
> If the error still occurs, try another alternate RPC endpoint from [MaticVigil](https://maticvigil.com).

2021-08-17 22:36 UTC, pyr0gan commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +```javascript
Use plaintext or remove the syntax highlighting for JS 👍

2021-08-18 06:23 UTC, AkhileshThite commented
> Thanks for splitting this off of the main tutorial, however it needs a bit of cleanup. Look over my suggestions and edit accordingly 👍 🙏

Thanks for reviewing. I'll make the changes ASAP :)

2021-08-18 14:48 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +In this tutorial, I'll show you how to deploy smart contracts of your DApp to the Polygon (Matic) Mumbai Test Network.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/a15613d6f2385c10bf1a479efa0f2e5d270f6352)

2021-08-18 14:49 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +I'll cover all the possible errors which I faced during the deployment.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/debee0d0af8bddc3ef9a075e8a029e37b8f1ceaa)

2021-08-18 14:54 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +# Deploying & Debugging the Smart Contracts on Polygon
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/3559221d9358756a1538841435927edcf746e772)

2021-08-18 14:55 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +## About the Author
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/d6ad295a942d2a345278833fb2e77378412a4bb9)

2021-08-18 14:56 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +## Dealing with different errors
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/25ce2880360dc526f9aa621af91145760d9ab1e5)

2021-08-18 14:58 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +```javascript
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/e85550b54ec97a536bb72150ded7197266093733)

2021-08-18 15:02 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +Change `https://rpc-mumbai.matic.today` by using [Infura custom RPC](https://infura.io)
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/3922ecd8369ca969a4d2d1ae3b1423f4857fc691)

2021-08-18 15:04 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +If still dealing with error, try this 2nd fix.
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/3440e1878a1d23028c7c9768729c570e867970e5)

2021-08-18 15:05 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +```javascript
[Fixed](https://github.com/AkhileshThite/datahub-learn/commit/10965dcafd373bf0465541b1ac0de37803b9b56d)

2021-08-18 15:15 UTC, AkhileshThite commented on network-documentation/matic/tutorials/Deploying-and-Debugging-the-Smart-Contracts-on-Polygon.md
> +## truffle-config
Yes. Because Social Media DApp tutorial also contains these two images, both tutorials are in different branch, this one is in `master` branch and Social Media DApp tutorial is in `main` branch, so just to show those two images in this tutorial also I kept them separate.

2021-08-18 17:20 UTC, AkhileshThite commented
Hey @pyr0gan, I've fixed all the issues. I replied to every review comment with commit links so that it'll be easy for you to review the changes.
Thank you!

2021-08-20 18:42 UTC, pyr0gan approved these changes
Thanks for making the changes, @AkhileshThite! Looks good to merge now. I'll take care of that today 😄 🚀

2021-08-20 20:33 UTC, AkhileshThite commented
> Thanks for making the changes, @AkhileshThite! Looks good to merge now. I'll take care of that today 😄 🚀

Thank you! 😊

2021-08-25 03:55 UTC, merged