Defi dapp
figment-networks/datahub-learn pull request #158
Opened 2021-08-19 21:33 UTC by Devilla

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines). If you don't follow those guidelines it might take longer for us to review.

- [ ] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [ ] I've followed the [template structure](Structure).
- [ ] I've proofread the tutorial for spelling and grammar mistakes.
- [ ] I've ran a linter & prettifier to format my code blocks.
- [ ] I've thoroughly explained the code, with inline code comments and text explanations.
- [ ] I've ran the tutorial and the code works.

2021-08-20 19:37 UTC, pyr0gan requested changes
Hi @Devilla! Thanks for this tutorial, it looks good except for a few small issues which I've pointed out. Tag me when you're done and I'll re-review! 🙏

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +Use `npm to install web3`, which is a library through which we can talk to the EVM:
> We'll be using the web3.js library to set up an HTTP provider so we can "talk" to the EVM. Install it as a dependency with the command:

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +We'll use web3 to set an HTTP Provider which is how web3 will speak to the EVM. Lastly, create a boilerplate truffle project:
> Then, create a boilerplate truffle project:

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +One of the files created when you ran `truffle init` is `truffle-config.js`. Add the following to `truffle-config.js`.
> `truffle-config.js` is the configuration file created when you run `truffle init`. Add the following to `truffle-config.js` to set up the web3.js connection to Avalanche:

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +```
Tidied up this code block.

```
pragma solidity 0.6.7;
import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import './DevToken.sol';
contract AvaSwap {
  string public name = "AvaSwap Network Exchange";
  DevToken public Token;
  uint public rate;
  AggregatorV3Interface internal priceFeed;

  event TokenPurchase(
    address account,
    address token,
    uint amount,
    uint rate
  );

  event TokenSold(
    address account,
    address token,
    uint amount,
    uint rate
  );

  constructor(DevToken _Token) public {
    Token = _Token;
    priceFeed = AggregatorV3Interface(0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541);
    rate = uint256(getLatestPrice());
  }

  // Returns the latest price
  function getLatestPrice() public view returns (int) {
    (
      uint80 roundID,
      int price,
      uint startedAt,
      uint timeStamp,
      uint80 answeredInRound
    ) = priceFeed.latestRoundData();
    // If the round is not complete yet, timestamp is 0
    require(timeStamp > 0, "Round not complete");
    return 1e18/price;
  }

  function buyTokens() public payable {
    // Calculate number of tokens to buy:
    // Avax Amount * Redemption rate 
    uint tokenAmount = msg.value * rate;
    Token.transfer(msg.sender, tokenAmount);
    // Emit an event
    emit TokenPurchase(msg.sender, address(Token), tokenAmount, rate);
  }

  function sellToken(uint _amount) public {
    // User can't sell more tokens than they have
    require(Token.balanceOf(msg.sender) >= _amount);
    // Calculate the amount of the avax to redeem
    uint avaxAmount =  _amount / rate;
    // Require that AvaSwap has enough avax
    require(address(this).balance >= avaxAmount);
    // Perform Sale
    Token.transferFrom(msg.sender, address(this), _amount);
    msg.sender.transfer(avaxAmount);
    // Emit an event
    emit TokenSold(msg.sender, address(Token), _amount, rate);
  }
}
```

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +```
```
const AvaSwap = artifacts.require("AvaSwap");
const DevToken = artifacts.require("DevToken");
module.exports = function (deployer) {
  // Deploy DevToken
  await deployer.deploy(DevToken, '5777');
  const devToken = await DevToken.deployed();
  // Deploy AvaSwap with DevToken
  await deployer.deploy(AvaSwap, devToken.address);
  avaSwap =  await AvaSwap.deployed();
  // Mint 0.001 DevToken to AvaSwap
  await devToken.transfer(avaSwap.address, '1000000000000000000000000');
};
```

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +Any time you make a change to `	AvaSwap.sol` you need to run `truffle` compile.
> Any time you make a change to `AvaSwap.sol` you must compile the contracts again.

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +When deploying smart contracts to the C-Chain, the truffle will default to the first available account provided by your C-Chain client as `the from` the address used during migrations.
> When deploying smart contracts to the C-Chain, Truffle will default to the first available account provided by your C-Chain client as the `from` address used during migrations.

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +Now everything is in place to run migrations and deploy the Storage contract:
> Now everything is in place to run the migrations and deploy the contract:

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +
Add \``` to this line 😄

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +If you didn't unlock the account, you'll see this error:
Add a new line after this one, with \```

This will fix the formatting! 👍

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +In this, we will be using `Main.js`, `BuyForm.js`, `SellForm.js` components. Here are the details of the components :
> To interact with the contract, we will be using `Main.js`, `BuyForm.js` & `SellForm.js` components. Here are the details of the components :

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +In this file import the `BuyForm` and `SellForm` components, then render the BuyForm and SellForm components.
> In this file, we must import the `BuyForm` and `SellForm` components, then render them.

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +In BuyForm.js file import the logos and ABIs of Avax, Dai, ChainLink Tokens
> In the BuyForm component, import the logos and ABIs of the AVAX, Dai & ChainLink tokens.

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +## Requirement
Should be plural, "Requirements"

2021-08-20 19:37 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +## Introduction
All top level headings should be H1, such as: \# Introduction
Subheadings, such as "Add AvaSwap.sol" can be H2, such as: \## Add AvaSwap.sol
😄

2021-08-20 20:25 UTC, Devilla commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +
It would be weird, it's the output.

2021-08-20 20:43 UTC, Devilla commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +If you didn't unlock the account, you'll see this error:
same as above.

2021-08-23 05:42 UTC, Devilla commented
@pyr0gan Thanks for the review. Kindly check and update. 😄

2021-08-25 04:20 UTC, pyr0gan approved these changes
👍 🚀

2021-08-25 04:20 UTC, merged