Create an Auction Bidding on Avalanche using ReactJS
figment-networks/datahub-learn pull request #171
Opened 2021-08-25 05:26 UTC by namannimmo10

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines). If you don't follow those guidelines it might take longer for us to review.

- [ ] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [ ] I've followed the [template structure](Structure).
- [ ] I've proofread the tutorial for spelling and grammar mistakes.
- [ ] I've ran a linter & prettifier to format my code blocks.
- [ ] I've thoroughly explained the code, with inline code comments and text explanations.
- [ ] I've ran the tutorial and the code works.

2021-08-31 03:40 UTC, namannimmo10 commented
This is ready for review!  Thanks for your suggestions, @pyr0gan.

2021-09-01 04:38 UTC, pyr0gan commented
> This is ready for review! Thanks for your suggestions, @pyr0gan.

Thanks @namannimmo10 I will review in the morning, when my eyes are fresh! 👀

2021-09-01 04:42 UTC, namannimmo10 commented
Looks like SUMMARY.md was deleted in upstream/master. Any reason for that?

2021-09-01 04:58 UTC, pyr0gan commented
> Looks like SUMMARY.md was deleted in upstream/master. Any reason for that?

It's actually not needed anymore since we decoupled the Learn site from GitBook! 😄

2021-09-02 17:04 UTC, pyr0gan requested changes

2021-09-02 17:45 UTC, namannimmo10 commented on network-documentation/avalanche/tutorials/create-an-auction-bidding-on-avalanche-using-reactjs.md
> +          providerOrUrl: RPCURL,
There's already a const `DATAHUB_RPC_URL` for https://avalanche--fuji--rpc.datahub.figment.io/apikey/${APIKEY}/ext/bc/C/rpc/. Renaming it to `RPC_URL`.

2021-09-02 17:51 UTC, namannimmo10 commented on network-documentation/avalanche/tutorials/create-an-auction-bidding-on-avalanche-using-reactjs.md
> +          providerOrUrl: RPCURL,
> There's already a const `DATAHUB_RPC_URL`

Realized it was redundant...

> You can change this to `DATAHUB_RPC_URL` and remove `RPCURL` entirely

Done!

2021-09-02 23:05 UTC, pyr0gan approved these changes
Just one last change and it will be good to merge! Thank you for making the fixes 🚀

2021-09-02 23:05 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-an-auction-bidding-on-avalanche-using-reactjs.md
> +const DATAHUB_RPC_URL = `https://api.avax-test.network/ext/bc/C/rpc`;
This is incorrect. I meant for you to keep the value of the DATAHUB_RPC_URL, not put the public RPC under this variable. Apologies if this was unclear from my comment.

It should be 
```text
DATAHUB_RPC_URL = `https://avalanche--fuji--rpc.datahub.figment.io/apikey/${process.env.APIKEY}/ext/bc/C/rpc`;
```

2021-09-03 01:25 UTC, namannimmo10 commented on network-documentation/avalanche/tutorials/create-an-auction-bidding-on-avalanche-using-reactjs.md
> +const DATAHUB_RPC_URL = `https://api.avax-test.network/ext/bc/C/rpc`;
```suggestion
const DATAHUB_RPC_URL = `https://avalanche--fuji--rpc.datahub.figment.io/apikey/${process.env.APIKEY}/ext/bc/C/rpc`;
```

2021-09-03 01:28 UTC, namannimmo10 commented
Thanks for the detailed review! I guess this can go in now.

2021-09-03 14:44 UTC, merged