Polkadot Tutorial: How to build Custom Pallets with Substrate
figment-networks/datahub-learn pull request #178
Opened 2021-08-30 09:09 UTC by prasad-kumkar

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines). If you don't follow those guidelines it might take longer for us to review.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines).

In particular:

- [x] I've followed the [template structure](Structure).
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've ran a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've ran the tutorial and the code works.

2021-09-01 01:35 UTC, pyr0gan requested changes
Hi @prasad-kumkar! Nice tutorial, thanks for writing this. Please have a look at my suggestions and make your edits. I highly recommend adding a Conclusion section and an About the Author section. Refer to our [sample tutorial structure](https://github.com/figment-networks/datahub-learn/blob/master/sample-tutorial-structure.md) for more info.

Tag me when you've made the changes and I will re-review before we publish the tutorial on Learn! 😄

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +```bash
\```text 

👍

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +Now you can clone the generated repository onto your local machine by running the following command in your terminal/command-line
> Now you can clone the generated repository onto your local machine by running the following command in your terminal:

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +## A look at template code
> ## Understanding the template code

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +First we are importing the rust macros from frame_support library, which are required to build our runtime module `decl_module`, storage `decl_storage`, events `decl_event`, errors `decl_error`, `dis
> First we are importing the rust macros from the `frame_support` library, which are required to build our runtime module: `decl_module`, storage: `decl_storage`, events: `decl_event`, errors: `decl_error`, `dispatch` for DispatchResult and the `Get` trait that is used by storage to convert types. We must also import `ensure_signed` from `frame_system` to check if transactions are signed.

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +### Configuration
Bump this up to H2: \## Configuration
👍

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +### Declaring Storage
Bump this up to H2: \## Declaring storage
👍

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +`Something` is a storage item, which can store an optional unsigned 32bit integer. This storage item can be accessed from the runtime module using the `something()` function. We can define more stora
> `Something` is a storage item, which can store an optional unsigned 32-bit integer. This storage item can be accessed from the runtime module using the `something()` function. We can define more storage items if we want.

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +[Heres more about Storage Items](https://substrate.dev/docs/en/knowledgebase/runtime/storage#declaring-storage-items)
> Read more about declaring [Storage Items](https://substrate.dev/docs/en/knowledgebase/runtime/storage#declaring-storage-items).

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +Runtime supports emitting specified events on method calls. We can pass in arguments with each event, here `SomethingStored` emit a unsigned 32bit integer and an AccountId
> Runtime supports emitting specified events on method calls. We can pass in arguments with each event, here `SomethingStored` emits an unsigned 32-bit integer and an AccountId

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +We can declare events here with this enum, which can be called from the module calls. This informs the user that something went wrong
> We can declare events with the Error enum, which can be called from the module calls. This informs the user that something went wrong.

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +### Runtime Module
You can bump this up to H2: \## Runtime module

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +Identity map: Identity => AccountId <br>
Remove HTML tags 👍

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +# Designing a Custom Pallet
From here to line 214, you might consider changing the subheadings to bold text. Otherwise this will crowd the Table of Contents for little benefit.

So change \## Storage Items to \*\*Storage Items\*\* for example.

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +[Link to code](https://github.com/prasad-kumkar/pallet-identity/blob/master/src/lib.rs)
> Have a look at this [example code](https://github.com/prasad-kumkar/pallet-identity/blob/master/src/lib.rs).

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +# Implementing Pallet
> # Implementing the pallet

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +For this we have create `Identity` mapping from Identity to AccountId. `Identity` here would be a string transformed into a vector of size u8.
> For storage, we have created an `Identity` mapping from Identity to AccountId. `Identity` here would be a string transformed into a vector of size u8.

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +Allows identity owner to add attribute key-value to their own identity. Should throw error when trying to add attribute to someone else's identity or if identity is not found
> Allows the identity owner to add attribute key-values to their own identity. This should throw an error when trying to add attributes to someone else's identity or if identity is not found

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +We have implemented two test case
> We have implemented two test cases:

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +[Link to code](https://github.com/prasad-kumkar/pallet-identity/blob/master/src/tests.rs)
> Check out the [example tests](https://github.com/prasad-kumkar/pallet-identity/blob/master/src/tests.rs).

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +		// should throw NotAuthrized error
> // Should throw NotAuthorized error

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +- Create Identity,
> - Create Identity
> - Add attribute
> - Remove attribute

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +- Create identity 'prasad' by account 1,
> - Account 1 creates identity 'prasad'
> - Throw `IdentityAlreadyClaimed` when Account 2 creates the same identity
> - Throw `NotAuthorized` while ... <- Please complete this sentence.

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +## Building and Testing
You can bump this up to H1: \# Building and Testing the pallet

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +### Build
I recommend removing the subheadings and rewriting it like so:

> To build the completed pallet with cargo, run `cargo build --release`.
>
> To run the tests against the compiled code, run `cargo test`.

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +## Releasing the pallet
You can bump this up to H1 👍

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +Before we release, we need to update the pallet details. Here you would need to update the pallet name to `pallet-identity` and repository
> Before releasing our pallet, we need to update the pallet details. Here you would need to update the pallet name to `pallet-identity` and change the repository link.

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +After that, you can publish the code using git
> After that, you can publish the code using git:

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +```bash
\```text

👍

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +```TOML
\```toml

👍

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +To add this pallet to your runtime, simply include the following to your runtime's `Cargo.toml` file:
> To add this pallet to your runtime, simply include the following section in your runtime's `Cargo.toml` file (remember to update the git link):

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +```TOML
\```toml

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +and update your runtime's `std` feature to include this pallet:
> Also update your runtime's `std` feature to include this pallet:

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +# References
Please also include a Conclusion heading, to recap the knowledge gained during the tutorial - and an About the Author section, with a sentence or two about yourself and a link to your GitHub profile 🚀

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +### Runtime `lib.rs`
You can bump this up to H2: \## Runtime `lib.rs`

2021-09-01 01:35 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +and include it in your `construct_runtime!` macro:
> Also include it in your `construct_runtime!` macro:

2021-09-01 10:10 UTC, prasad-kumkar commented
@pyr0gan I have made the requested changes. thank you

2021-09-01 16:25 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +We can start off using the Substrate pallet template, which provides provides the starter code using Frame v1
This definitely needs a fix, there's still an extra "provides" in the sentence.

2021-09-01 17:29 UTC, prasad-kumkar commented
@pyr0gan I have fixed all the mentioned points

2021-09-02 17:18 UTC, pyr0gan reviewed
I have tagged you on all the important changes, but please go through and resolve the conversations once you make the changes and commit 😄

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +```rust
This change still needs to be completed @prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +First we are importing the rust macros from frame_support library, which are required to build our runtime module `decl_module`, storage `decl_storage`, events `decl_event`, errors `decl_error`, `dis
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +`Something` is a storage item, which can store an optional unsigned 32bit integer. This storage item can be accessed from the runtime module using the `something()` function. We can define more stora
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +[Heres more about Storage Items](https://substrate.dev/docs/en/knowledgebase/runtime/storage#declaring-storage-items)
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +Runtime supports emitting specified events on method calls. We can pass in arguments with each event, here `SomethingStored` emit a unsigned 32bit integer and an AccountId
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +- Create identity 'prasad' by account 1,
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +		// should throw NotAuthrized error
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +## Building and Testing
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +### Build
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +## Releasing the pallet
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +After that, you can publish the code using git
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +FRAME is the framework to develop pallets, it comes with set of libraries and modules to get started. Following is the skeleton of a FRAME based pallet:
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +We can declare events here with this enum, which can be called from the module calls. This informs the user that something went wrong
😅 @prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +# Designing a Custom Pallet
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +Identity map: Identity => AccountId <br>
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +# Implementing Pallet
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +[Link to code](https://github.com/prasad-kumkar/pallet-identity/blob/master/src/lib.rs)
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +For this we have create `Identity` mapping from Identity to AccountId. `Identity` here would be a string transformed into a vector of size u8.
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +Allows identity owner to add attribute key-value to their own identity. Should throw error when trying to add attribute to someone else's identity or if identity is not found
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +[Link to code](https://github.com/prasad-kumkar/pallet-identity/blob/master/src/tests.rs)
@prasad-kumkar

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +We have implemented two test case
@prasad-kumkar please resolve any conversations when you make the changes, so I know they are complete.

2021-09-02 17:18 UTC, pyr0gan commented on network-documentation/polkadot/tutorials/custom-pallet.md
> +# References
@prasad-kumkar

2021-09-02 18:08 UTC, prasad-kumkar commented
@pyr0gan I made those changes in these commits https://github.com/figment-networks/datahub-learn/pull/178/commits/b285f57f6975634ad148973934b5004b18ef3ea3 and https://github.com/figment-networks/datahub-learn/pull/178/commits/dc5e58be6a472dcdd5d7d6b5aded12c4a00609a7, is it visible or should I create another pull request? sorry, I'm new to this 😅

2021-09-02 22:44 UTC, pyr0gan commented
> @pyr0gan I made those changes in these commits [b285f57](https://github.com/figment-networks/datahub-learn/commit/b285f57f6975634ad148973934b5004b18ef3ea3) and [dc5e58b](https://github.com/figment-networks/datahub-learn/commit/dc5e58be6a472dcdd5d7d6b5aded12c4a00609a7), is it visible or should I create another pull request? sorry, I'm new to this 😅

You may have made the changes but they're not part of the commits. You can see what the commits contain by going to the Commits tab. There were only 3 changes made >> https://github.com/figment-networks/datahub-learn/pull/178/commits/dc5e58be6a472dcdd5d7d6b5aded12c4a00609a7 Check your working copy on your local repo, you may just need to make another commit and include the changes 😄

2021-09-03 17:05 UTC, prasad-kumkar commented
@pyr0gan please check out my recent commit

2021-09-03 18:21 UTC, pyr0gan approved these changes
Thank you for tidying it up. I know that markdown editing is a separate skill from software development and tutorial writing, but since we base our site rendering on the raw markdown for simplicity - it pays to make good, clean markdown files to begin with 👍 

It appears you've made all the changes, so I will be able to merge this, although I will need to make a few minor changes once it is published to ensure it looks good on the Learn site. 😄 

Thank you for writing the tutorial 🙏 . We hope many new Web 3 developers will benefit from having a clear resource for starting to write their own custom Substrate pallets.

2021-09-04 00:53 UTC, merged