Fix broken links
figment-networks/datahub-learn pull request #181
Opened 2021-08-30 23:02 UTC by pyr0gan

- Fixed broken links as per Google Doc shared by @yash-sharma1 
- Fixed some remaining HTML tags
- Fixed some typos and formatting

2021-08-31 12:07 UTC, zurgl requested changes
@pyr0gan Almost perfect, but I found one link which is not working please review.

2021-08-31 19:22 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +You must have gone through this tutorial [Create a Local Test Network on Avalanche](https://learn.figment.io/tutorials/create-a-local-test-network) and have performed a cross-chain swap via the [Tran
Fixed!

2021-09-01 05:20 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/create-a-dex-with-avalanche.md
> +You must have gone through this tutorial [Create a Local Test Network on Avalanche](https://learn.figment.io/tutorials/create-a-local-test-network) and have performed a cross-chain swap via the [Tran
@pyr0gan At the second line, this [Transfer AVAX Between X-Chain and C-Chain] should be linked to this https://learn.figment.io/tutorials/transfer-avax-between-the-x-chain-and-c-chain

2021-09-01 05:53 UTC, yash-sharma1 commented on network-documentation/secret/tutorials/deploy-your-own-secret-nft.md
> +For a high level introduction to Non-Fungible-Tokens see the [first installment of this series](https://learn.figment.io/tutorials/create-your-first-secret-nft). In this tutorial we will download and
Link to [previous tutorial] also need to be updated to https://learn.figment.io/tutorials/create-your-first-secret-nft

2021-09-01 06:03 UTC, yash-sharma1 commented
@pyr0gan left some comments for links to fix other than that all good & great job!

2021-09-01 14:17 UTC, merged