Polygon donation dapp tutorial
figment-networks/datahub-learn pull request #188
Opened 2021-09-01 12:44 UTC by viral-sangani

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run the tutorial to test it and the code works.

2021-09-02 22:33 UTC, pyr0gan requested changes
Hey @viral-sangani 
Some hefty changes required here, but it should only take you a few hours to go through them and fix this up for publication 😄 

Please carefully review my comments, make the appropriate fixes, and remember to mark the conversations as resolved when you've completed your commit. When you've committed your changes, tag me in a comment and I will re-review before we merge the tutorial and publish it. 

Thanks for taking the time to write this tutorial 🙏

2021-09-02 22:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +- First, you have to connect your metamask wallet to Matic mumbai-testnet. You can follow [this](https://docs.matic.network/docs/develop/metamask/config-polygon-on-metamask/) instructions by polygon
> - First, you have to connect your Metamask wallet to the Matic Mumbai testnet. You can follow [these instructions](https://docs.matic.network/docs/develop/metamask/config-polygon-on-metamask/) to connect. Once you have connected Metamask to the Mumbai testnet, you will need to get the Secret Recovery Phrase from Metamask that you would have received when you created the Metamask account. If you are unsure how to do this, follow [these instructions](https://metamask.zendesk.com/hc/en-us/articles/360015290032-How-to-reveal-your-Secret-Recovery-Phrase) to get the Secret Recovery Phrase (also commonly referred to as a mnemonic).

2021-09-02 22:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +- Now create a file `.secret` at the root of your project directory and paste your `mnemonic` in that file. This is the `mnemonic` of the account that will have to pay gas fees for contract deploymen
> - Now create a file called `.secret` at the root of your project directory and paste your mnemonic in that file. This is the Secret Recovery Phrase of the account that will have to pay gas fees for contract deployment.

2021-09-02 22:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +- **NOTE - Since we are deploying to testnet we don't have to pay actual MATIC token, we can use [Matic Faucet](https://faucet.matic.network/) to receive 1 MATIC in your account in the mumbai-testnet
> **NOTE:** Since we are deploying to a testnet we don't have to pay actual MATIC tokens, we can use the [Matic Faucet](https://faucet.matic.network/) to receive 1 MATIC in your account on the Mumbai testnet.

2021-09-02 22:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +- **Make sure you have added .secret file in your .gitignore and never share your mnemonics with anyone.**
> - **Make sure you have added the `.secret` file in your `.gitignore` and never share your Secret Recovery Phrase (mnemonic) with anyone!**

2021-09-02 22:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +          providerOrUrl: `https://matic-mumbai.chainstacklabs.com`,
This is definitely a case of being able to use a DataHub RPC endpoint URL with a DataHub API key 😄 
I can see keeping it simple, but we'd definitely appreciate it if you could make this work with DataHub.

2021-09-02 22:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +Here, we are adding another network `matic`, and adding `providerOrUrl`, `chainId`, and `network_id` of Polygon mumbai-testnet. You can find this information on [Polygon docs](https://docs.matic.netw
> Here, we are adding another network `matic`, and adding `providerOrUrl`, `chainId`, and `network_id` of Polygon's Mumbai testnet. You can find this information on the [Polygon docs](https://docs.matic.network/docs/develop/network-details/network/).

2021-09-02 22:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +```bash
\```text

2021-09-02 22:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +```
\```text

2021-09-02 22:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +After running the above code, you should get output similar to this -
> Truffle will deploy the contract to Mumbai, you should see output similar to:

2021-09-02 22:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +
Do you think you could add to the tutorial a walkthrough of the UI? It's OK to use short sentences and images (even GIFs!), but I feel it would be good to cap the tutorial off with showing users what the finished product should look like in use.

2021-09-02 22:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +In this tutorial, we have seen how to create a smart contract in solidity, have to use IPFS to upload images, how to interact with smart contracts in frontend applications using web3js and how to pub
> Congratulations on finishing the tutorial! Thank you for taking the time to complete it. In this tutorial, you have learned how to create a smart contract in Solidity, how to use IPFS to upload images, how to interact with smart contracts in frontend applications using web3js and how to publish your smart contract to the Polygon testnet. This donation dApp is one of the endless possibilities of Web 3 development.

2021-09-02 22:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +I'm Viral Sangani, a tech enthusiast working on blockchain projects & love web3 community. Feel free to connect with me on [GitHub](https://github.com/viral-sangani) & [Twitter](https://twitter.com/v
> I'm Viral Sangani, a tech enthusiast who loves working on Web 3 & blockchain projects. Feel free to connect with me on [GitHub](https://github.com/viral-sangani).

Sorry, mate. We don't allow Twitter links in the bio. If you've got a Learn community forum profile you can include that as well.

2021-09-04 04:46 UTC, viral-sangani commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +```
I am sorry, this might have been because of the text editor I was using.

2021-09-04 05:44 UTC, viral-sangani commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +
I have added a GIF of the whole app at the top of the tutorial. 
https://github.com/viral-sangani/datahub-learn/blob/polygon-donation-dapp-tutorial/.gitbook/assets/dapp-demo.gif

2021-09-04 05:44 UTC, viral-sangani commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +
Should I add it at the end instead? @pyr0gan

2021-09-04 05:49 UTC, viral-sangani commented
@pyr0gan I really appreciate you taking time and giving such valuable feedback. Your comments and suggestions will surely help me to write better tutorials in the future. Thank you 😁.

2021-09-04 06:06 UTC, viral-sangani commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +
I have added a walkthrough GIF of the whole app at the end. Let me know your thoughts on it.

2021-09-08 16:25 UTC, pyr0gan reviewed
Just a few more changes to make 😄 

The major things to watch out for are proper use of backticks, sentence structure and correctness of the Requirements section.

Once you update, I'll have a look over it once more and we should be good to publish! 🚀

2021-09-09 04:28 UTC, viral-sangani commented
@pyr0gan I have made the requested changes.
Can you recommend any good text editor for markdown? I am currently using VSCode and it's not that good with markdown.

2021-09-09 15:57 UTC, pyr0gan commented
> @pyr0gan I have made the requested changes.
> Can you recommend any good text editor for markdown? I am currently using VSCode and it's not that good with markdown.

I use VSCode to edit markdown, but I use several extensions and it really comes down to personal preference. There are a few editors that will give you a better view of the markdown syntax, I will put together a guide today. Don't worry, I'll help you edit markdown like a pro in no time! 😄

2021-09-09 19:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +For contract calls, we will create a context and provide all the data and functions through it. Create a folder `contexts` in the root directory of your project and create a file called `DataContext.
> For contract calls, we will create a context and provide all the data and functions through it. Create a folder `context` in the root directory of your project and create a file called `DataContext.tsx` in that folder.

2021-09-09 19:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +      window.alert("Non-Eth browser detected. Please consider using MetaMask.");
The alert text is really up to you, but I recommend rewording it slightly. Try:

>```js
> window.alert("No compatible wallet detected. Please install the Metamask browser extension to continue.");
>```

2021-09-09 19:33 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +      await window.ethereum.enable();
The `enable` method is deprecated and will generate a warning in the browser console. This is legacy code and should not be relied upon in practice. The preferred method is to use 
```js
ethereum.request({ method: 'eth_requestAccounts', [] })
```

For reference: https://docs.metamask.io/guide/ethereum-provider.html#using-the-provider

2021-09-10 06:34 UTC, viral-sangani commented
@pyr0gan I have made the updates.

2021-09-10 17:14 UTC, pyr0gan approved these changes

2021-09-10 17:14 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-donation-dapp-on-polygon-to-award-your-favourite-content-creator.md
> +      ethereum.request({ method: 'eth_requestAccounts', [] })
This would actually need to be `window.ethereum.request`. I'll be able to run through and test it to make sure it works in a couple of hours. It's a minor change but an important one 😄

2021-09-11 15:12 UTC, viral-sangani commented
@pyr0gan Made the change you requested.

2021-09-13 22:03 UTC, pyr0gan approved these changes

2021-09-13 22:03 UTC, merged

2021-09-13 22:32 UTC, pyr0gan commented
> @pyr0gan Made the change you asked for.

Hey @viral-sangani 👋 Thanks for your work on this tutorial, I know the community appreciates more good tutorials. I've merged your donation dApp tutorial and it is live on the site at [https://learn.figment.io/tutorials/create-a-donation-dapp-on-polygon](https://learn.figment.io/tutorials/create-a-donation-dapp-on-polygon) 😄 

What's next? Do you have any other tutorials planned? Looking forward to more!

🙏