Polygon Chainlink VRF Tutorial
figment-networks/datahub-learn pull request #198
Opened 2021-09-07 04:42 UTC by ysongh

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run the tutorial to test it and the code works.

2021-09-08 17:40 UTC, pyr0gan requested changes
Hello You Song! 😄 

Thanks for taking the time to write this introduction to using Chainlink on Polygon!

Please review my suggestions carefully, making the changes as you go. Please remember to mark the conversations as resolved so that my next review goes quickly 🙏 
If you have any questions or concerns, just tag me and I'll be along to help as soon as I can 😄 🚀

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +You can go to this URL [https://mumbai.polygonscan.com/](https://mumbai.polygonscan.com/) to check your balances by entering your address on the search bar.
> You can view your current MATIC and LINK balances in Metamask or by going to [https://mumbai.polygonscan.com/](https://mumbai.polygonscan.com/) & entering your address in the search bar.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +To see `LINK` token on your Metamask:
> To see LINK tokens in your Metamask:

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +1) Click on `Add Token` button
> 1) Click on the Add Token button

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +2) Enter `0x326C977E6efc84E512bB9C30f76E30c160eD06FB` on `Token Contract Address` text field.  `Token Symbol` and `Token Decimal` text fields will be prefilled when you enter the Token Contract Addre
> 2) Enter `0x326C977E6efc84E512bB9C30f76E30c160eD06FB` in the Token Contract Address text field. Token Symbol and Token Decimal text fields will be pre-filled when you enter the Token Contract Address.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +3) Click on `Next` button
> 3) Click the Next button

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +4) Click on `Confirm` button to add `LINK` token to your Metamask
> 4) Click the Confirm button to add LINK tokens to your list of assets in Metamask

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +### 2. Using Remix IDE
Remove numbering and bump this up to H2: \## Using the Remix IDE

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +We will use the Remix IDE - an online IDE to develop smart contracts.
> We will use the Remix IDE - an online development environment for smart contracts, provided by the Ethereum Foundation.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +Head over to [https://remix.ethereum.org](https://remix.ethereum.org/). Click on the `File Icon` to create a file and named it `RandomNumber.sol`.
> Head over to [https://remix.ethereum.org](https://remix.ethereum.org/). Click on the File Icon to create a new file and name it `RandomNumber.sol`.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +### 3. Coding smart contract
Remove numbering and bump this up to H2: \## Creating the smart contract

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +On RandomNumber.sol, copy the entire smart contract code and paste it in the editor.
> In `RandomNumber.sol`, copy the entire smart contract code below and paste it into the Remix editor panel.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +This will inherit from VRFConsumerBase contract for randomness.  VRFConsumerBase takes it two parameters (VRF Coordinator, LINK Token).  We will use `0x8C7382F9D8f56b33781fE506E897a4F1e2d17255` for V
> This will inherit from the VRFConsumerBase contract.  The VRFConsumerBase constructor takes two parameters: An address for the VRF Coordinator and an address for the LINK Token.  We will use `0x8C7382F9D8f56b33781fE506E897a4F1e2d17255` for VRF Coordinator and `0x326C977E6efc84E512bB9C30f76E30c160eD06FB` for the LINK Token which will work on the Mumbai testnet.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +We will use `0x6e75b569a01ef56d18cab6a8e71e6600d6ce853834d4a5748b720d06f878b3a4` for specific chainlink oracle and set the fee to 0.0001 LINK to pay the that chainlink oracle for randomness.
> We will use the contract hash `0x6e75b569a01ef56d18cab6a8e71e6600d6ce853834d4a5748b720d06f878b3a4` to specify the Chainlink oracle to use and set the fee to 0.0001 LINK to pay the oracle for its verifiable random output.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +This will get a random number from the chainlink oracle.  `requestRandomness()` comes from `VRFConsumerBase` contract that we imported.
> This will get a random number from the chainlink oracle.  `requestRandomness()` comes from the `VRFConsumerBase` contract that we imported at the top of our smart contract.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +This is a callback function used by VRF Coordinator to determine if the number is really random
> This is a callback function used by the VRF Coordinator to determine if the number is actually random.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +### 4. Deploy the contract with Remix
Remove numbering and bump up to H2: \## Deploy the contract with Remix

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +On Remix, click on Solidity Compiler icon on the Sidebar
> In Remix, click on the Solidity Compiler icon on the sidebar:

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +Select `0.6.6+commit.6c089d02` as the compiler and click `Compile RandomNumber.sol` button to compile the smart contract. Once compiled, the smart contract is ready to be deployed onto the Polygon \(
> Select `0.6.6+commit.6c089d02` as the compiler and click the `Compile RandomNumber.sol` button to compile the contract. Once compiled, it is ready to be deployed onto the Mumbai testnet.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +Click on `Solidity Compiler` icon on the Sidebar.
Click the Solidity Compiler icon on the sidebar again:

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +Select `Injected Web3 as the environment` in the dropdown. It will connect to your Metamask and find the network ID and account address.  80001 is the network ID for Polygon \(Matic\) Mumbai Testnet.
> Select "Injected Web3" as the environment in the dropdown. It will connect to your Metamask and find the network ID and account address.  80001 is the network ID for the  Mumbai testnet.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +Select `RandomNumberConsumer - RandomNumber.sol` as the contract in the dropdown and click Deploy button.
> Now, select `RandomNumberConsumer - RandomNumber.sol` as the contract in the dropdown and click the Deploy button.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +Metamask should popup and click Confirm button to confirm the transaction.  This should deploy the contract to the
> Metamask should popup, allowing you to click the Confirm button to complete the transaction. This should deploy the contract to the Mumbai testnet.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +Polygon \(Matic\) Mumbai Testnet.
You can remove this line. See above comment.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +### 5. Fund your contract with Link
Remove numbering and bump this up to H2: \## Fund the contract with LINK

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +You will need to fund your contract with LINK token for random number to work.  Click on `Copy Icon` to copy your contract address.
> You will need to fund your contract with LINK tokens to pay the Chainlink oracle for VRF to work. Click on the Copy Icon to copy your contract address.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +1) Click on the `Link` token
> 1) Click on the LINK token

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +2) Click on `Send` button
> 2) Click the Send button

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +3) Paste your contract address on the search bar
> 3) Paste your contract address into the search bar

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +4) Set Amount to `1` Link
> 4) Set Amount to 1 LINK

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +5) Click on `Next` button
> 5) Click on the Next button

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +6) Click on `Confirm` button to confirm the transaction
> 6) Click the Confirm button to confirm the transaction

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +You can go to this URL [https://mumbai.polygonscan.com/](https://mumbai.polygonscan.com/) to check your contract balances by entering your contract address on the search bar.
> You can go to the Mumbai block explorer [https://mumbai.polygonscan.com/](https://mumbai.polygonscan.com/) to check your contract balances by entering your contract address in the search bar.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +### 6. Trying contract
Remove numbering and bump this up to H2: \## Using the contract

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +Click on this `Arrow Icon` to see your contract methods
> Click on the Arrow Icon to see your contract methods

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +Click on `getRandomNumber` button.  You should see a metamask popup.  Click on `Confirm` button to confirm the transaction.
> Click on the `getRandomNumber` button.  You should see a Metamask popup.  Click on Confirm to confirm the transaction.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +When the transaction is success, click on `randomResult` button and you should see a random number that is not zero.
> When the transaction is successful, click on the `randomResult` button and you should see a random number that is not zero!

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +## Common Error
Bump this up to H1: \# Possible errors & solutions

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +If you get this error, it mean that your contract does not have enough `LINK` token and you should send some `LINK` token to your contract.
> If you get this error, it means that your contract does not have enough LINK token to pay the oracle fee. To solve this, you should send some LINK token to your contract address.

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +To learn more about Chainlink VRF, visit [Chainklink Doc](https://docs.chain.link/docs/chainlink-vrf/).
> To learn more about Chainlink VRF, visit the [Chainlink docs](https://docs.chain.link/docs/chainlink-vrf/).

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +## About The Author
Bump this up to H1 👍

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +## References
Bump this up to H1 😄

2021-09-08 17:40 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +This tutorial was created by You Song Hou who is a full stack developer.
> This tutorial was created by [You Song Hou](https://github.com/ysongh) who is a full stack developer.

2021-09-09 18:29 UTC, ysongh commented
Hi Rogan, I finish making the changes, thank you for your suggestions.

2021-09-09 19:10 UTC, pyr0gan requested changes
Just a minor fix to the text and this looks good to me 😄 👍 

It would also be good to re-do the images so that the callouts are clearer and don't look like scribbles. If you would like help with this, just let me know. There are good annotation tools on macOS, but even most online image editors should have resizeableoval shapes you can use 😄

2021-09-09 19:10 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +Select` 0.6.6+commit.6c089d02` as the compiler and click the `Compile RandomNumber.sol` button to compile the contract. Once compiled, it is ready to be deployed onto the Mumbai testnet.
> Select `0.6.6+commit.6c089d02` as the compiler and click the "Compile RandomNumber.sol" button to compile the contract. Once compiled, it is ready to be deployed onto the Mumbai testnet.

2021-09-09 19:10 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +Select` 0.6.6+commit.6c089d02` as the compiler and click the `Compile RandomNumber.sol` button to compile the contract. Once compiled, it is ready to be deployed onto the Mumbai testnet.
Just need to fix an issue with the space at the beginning of the backticks, and remove the backticks from the name of the button ("double quotes" or **bold text** are OK). We generally only use backticks for preformatted text when it's a filename, file path, a function or something else to do with code or the command line 😄

2021-09-09 19:12 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +Click on the `getRandomNumber` button. You should see a Metamask popup. Click on Confirm to confirm the transaction.
I recommend using double quotes instead of backticks on "getRandomNumber"

2021-09-09 19:12 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-VRF-on-Polygon(Matic)-using-Remix IDE.md
> +When the transaction is successful, click on the `randomResult` button and you should see a random number that is not zero!
Similarly, I recommend double quotes on "randomResult" 😄

2021-09-10 05:38 UTC, ysongh commented
Hi Rogan, I made the changes and re-do some of the images.  Thanks

2021-09-10 18:49 UTC, pyr0gan commented
> Hi Rogan, I made the changes and re-do some of the images. Thanks

The tutorial looks good 😄 
I will make some images to show you what I mean. They're not a blocker, they could just use a little more polish. I will merge and get this tutorial on the site today 👍 
Thanks for your work on this tutorial, I am sure the community will make good use of it!

2021-09-10 18:52 UTC, pyr0gan approved these changes

2021-09-10 18:52 UTC, merged