erc20 and c to metamask tutorials edited
figment-networks/datahub-learn pull request #220
Opened 2021-09-09 17:46 UTC by avalanchemoon

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [v] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [v] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [v] I've proofread the tutorial for spelling and grammar mistakes.
- [v] I've run a linter & prettifier to format my code blocks.
- [v] I've thoroughly explained the code, with inline code comments and text explanations.
- [v] I've run the tutorial to test it and the code works.

2021-09-09 20:35 UTC, pyr0gan requested changes
Hi @avalanchemoon 👋 

Just some minor fixes to look after before we merge the update!

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/avax_c_chain_to_eth_address_transfer_tutorial.md
> +```bash
\```javascript

bash would not render the right kind of syntax highlighting 😄

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/avax_c_chain_to_eth_address_transfer_tutorial.md
> +To run the script `AVAX_C_chain_to_ETH_address.js`, type `node AVAX_C_chain_to_ETH_address.js` and run it in your terminal (`node` before the file name is for NodeJs runtime.environment).
> To run the script `AVAX_C_chain_to_ETH_address.js`, type `node AVAX_C_chain_to_ETH_address.js` and run it in your terminal (`node` before the file name is the way to invoke the NodeJS runtime environment).

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/avax_c_chain_to_eth_address_transfer_tutorial.md
> +This tutorial has taught you how to transfer AVAX native tokens from the C chain to an ETH wallet. Also, this has shown how Avalanche blockchain C chain is compatible with the usual web3 library. Thi
> This tutorial has taught you how to transfer AVAX native tokens from the C chain to an ETH wallet. Also, this has shown how Avalanche blockchain C chain is compatible with the popular web3.js library. This is a powerful aspect of the Avalanche blockchain, as it allows Ethereum developers to easily port their work over to Avalanche.

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +---
As in the previous file, the following lines can be removed:

```
---
description: Learn ow to Transfer ERC-20 tokens from C-chain to ETH address
---

# Transfer ERC-20 tokens from the C-chain of your AVAX wallet to an ETH address
```

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +Continuing the theme of transfers of tokens, in this tutorial, we are going to learn how to programmatically transfer ERC-20 tokens from the C-chain to a Metamask wallet
> Continuing with the theme of token transfers, in this tutorial we are going to learn how to programmatically transfer ERC-20 tokens from the Avalanche C-chain to a Metamask wallet.

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +We are going to create a new file called `ERC20_fromC_to_ETH_address.js` in the root directory of your project. Once you create a .js file under the specified name, we will type in the following bloc
It would be better to name the file something easier to read and type, such as `transfer-avax-to-eth.js`, but this is up to you 😄

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +First, we need to import `ethers` interact with the Avalanche C chain
> First, we need to import the `ethers` library to interact with the Avalanche C chain

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +```bash
\```javascript

👍

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +```bash
\```javascript

😄

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +```bash
\```javascript

or even simply \```js 

😄

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +```bash
\```javascript

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +```bash
\```javascript

😄

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +```bash
\```javascript

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +```bash
\```javascript

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +Click on `Add Token` below the coin list of the wallet and type in the AVAXDATAHUB contract address, then the rest of the information should automatically be loaded, as shown in the image below.
> Click on "Add Token" below the coin list of the wallet and type in the AVAXDATAHUB contract address, then the rest of the information should automatically be loaded, as shown in the image below.

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +After the swap, go back to Metamask, click on `Add Token` and type in the contract address as shown in the image below. Without manually adding the AVAXDATAHUB token, it will not show up on your Meta
> After the swap, go back to Metamask, click on "Add Token" and type in the contract address as shown in the image below. Without manually adding the AVAXDATAHUB token, it will not show up on your Metamask.

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +```bash
\```javascript

It's important to use the correct syntax highlighting type so that it renders on the Figment Learn website properly 👍

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +Now, we are going to define `sendToken` function, which will execute a transfer of 1 AVAXDATAHUB token from the C-chain of the Avalanche wallet to the ETH destination address.
> Now, we are going to define the `sendToken` function, which will execute a transfer of 1 AVAXDATAHUB token from the C-chain of the Avalanche wallet to the ETH destination address.

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +```bash
\```javascript

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +```bash
\```javascript

👍

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +  ```
Just a small bit of housekeeping here, un-indent the backticks (remove the leading spaces) 👍

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +```bash
\```javascript

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +To run the script `ERC20_fromC_to_ETH_address.js`, type `node ERC20_fromC_to_ETH_address.js` and run it in your terminal (`node` before the file name is for NodeJs runtime.environment).
> To run the script `ERC20_fromC_to_ETH_address.js`, type `node ERC20_fromC_to_ETH_address.js` and run it in your terminal (node before the file name is the way to invoke the NodeJS runtime environment).

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +As you can see in the image below, my metamask balance did change from 4.97 to 5.97.
> As you can see in the image below, the balance did change from 4.97 to 5.97.

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
>  # Conclusion
To make sure the heading renders properly,  please make sure it is at the beginning of the line with no extra spaces in front of the \# 👍

2021-09-09 20:35 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +# About the author
> \# About the Author

2021-09-09 21:43 UTC, avalanchemoon commented on network-documentation/avalanche/tutorials/avax_c_chain_to_eth_address_transfer_tutorial.md
>  ---
no particular reason. i think it was a mistake.   went from underscores to hyphens now.

2021-09-09 21:44 UTC, avalanchemoon commented
thank you for the suggestions/edits.  I have made changes accordingly.  let me know what you think. thanks for the patience (waiting a long while for me to get back to this etc)

2021-09-09 23:01 UTC, pyr0gan reviewed
One last thing to take care of. Thanks for making the changes to the tutorial, it should look much nicer on the new site! 😄

2021-09-09 23:17 UTC, avalanchemoon commented on network-documentation/avalanche/tutorials/avax-c-chain-to-eth-address-transfer-tutorial.md
> +Alternatively, the Datahub version would look as follows:
Thank you. I have added a link to the article and mentioned signing up to get an API key.

2021-09-10 19:05 UTC, pyr0gan approved these changes

2021-09-10 19:06 UTC, merged