Query Ethereum data with The Graph
figment-networks/datahub-learn pull request #230
Opened 2021-09-14 00:32 UTC by robin-thomas

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [ ] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [ ] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [ ] I've proofread the tutorial for spelling and grammar mistakes.
- [ ] I've run a linter & prettifier to format my code blocks.
- [ ] I've thoroughly explained the code, with inline code comments and text explanations.
- [ ] I've run the tutorial to test it and the code works.

2021-09-14 23:53 UTC, pyr0gan requested changes
Thank you @robin-thomas for writing this tutorial. Please look over my recommendations and make the necessary changes. Remember to mark the conversations as resolved so that my second review can proceed quickly.

Please don't hesitate to tag me if you have any questions or require assistance in making the changes!

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +First, headover to the Subgraph Studio at https://thegraph.com/studio/.
> First, you will want to head over to the Subgraph Studio at [https://thegraph.com/studio/](https://thegraph.com/studio/).

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +Next, you need to give your subgraph a name. Give the name as **vending**. Once that's done, you shall see the below screen.
> Next, you need to give your subgraph a name. Give the name as **vending**. Once that's done, you will see this screen:

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +On this screen, you can see details like your deploy key, subgraph slug and status.
> On this screen, you can see details about the subgraph like your deploy key, the subgraph slug and status.

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +- Run the below command to create the subgraph by downloading the contract abi from rinkeby testnet. A new directory called `vending` shall be created, and all node dependencies will be installed aut
> - Run the following command to create the subgraph by downloading the contract ABI from the Rinkeby testnet. A new directory called `vending` will be created, and all node dependencies will be installed automatically.

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +$ graph init --contract-name VendingMachine --index-events --studio --from-contract 0x4006c82FfB71933160948626dB3Ff8D8aaad6510 --network rinkeby vending
Remember to remove the `$` ! 😄

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +This will fetch the abi from rinkeby smart contract passed as an argument to `--from-contract`, and store it under `./vending/abis` directory. The Graph CLI will auto-generate the mappings from the s
> This will fetch the ABI from the Rinkeby smart contract passed as an argument to `--from-contract`, and store it in the `./vending/abis` directory. The Graph CLI will auto-generate the mappings from the smart contract ABI. You can view the mapping in `./vending/src/mapping.ts`.

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +> By passing in --index-events the CLI will automatically populate some code for us both in schema.graphql as well as src/mapping.ts based on the events emitted from the contract.
> By passing in `--index-events` the CLI will automatically populate some code for us in both `schema.graphql` as well as `src/mapping.ts` based on the events emitted from the contract.

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +- Run the below command to set the deploy key. Replace <DEPLOY_KEY> in the below command with the key you got from https://thegraph.com/studio/subgraph/vending/
> - Run the following command to set the deploy key. Replace <DEPLOY_KEY> with the key you got from [https://thegraph.com/studio/subgraph/vending/](https://thegraph.com/studio/subgraph/vending/)

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +$ graph auth --studio <DEPLOY_KEY>
Remove the `$` please 😄

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +- Run the below command to create the subgraph. Your new subgraph will be created in `subgraph.yaml` file.
> - To create the subgraph, run the following command. Your new subgraph will be created in a `subgraph.yaml` file.

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +$ cd vending
You guessed it, those `$` gotta go 😉

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +- Run the below command to deploy the subgraph to Subgraph Studio.
> - The following command will deploy the subgraph to Subgraph Studio:

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +$ graph deploy --studio vending
`$` 💀 👍 😄

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +Subgraph Studio might take few minutes to sync the graph from rinkeby testnet. Wait until the syncing process is complete.
> Subgraph Studio might take few minutes to sync the graph from the Rinkeby testnet. Wait until the syncing process is complete.

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +Once the sync is complete, you shall have access to the Playground to run your queries.
> Once the sync is complete, you can access the subgraph on the Playground to run your queries.

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +Head over to https://thegraph.com/studio/subgraph/vending/ to start querying data with the Playground.
> Head over to [https://thegraph.com/studio/subgraph/vending/](https://thegraph.com/studio/subgraph/vending/) to start querying data with the Playground.

You still need to add the Markdown link formatting: \[link text\]\(https://url.com) to links for them to work as links 😄

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +### Creating data and querying it
This can be a subheading, bump it up to H2: \## Creating data and querying it

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +Headover to https://rinkeby.etherscan.io/address/0x4006c82ffb71933160948626db3ff8d8aaad6510#writeContract to see the rinkeby smart contract.
> Go to [https://rinkeby.etherscan.io/address/0x4006c82ffb71933160948626db3ff8d8aaad6510#writeContract](https://rinkeby.etherscan.io/address/0x4006c82ffb71933160948626db3ff8d8aaad6510#writeContract) to see the Rinkeby smart contract.

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +Click on the **Connect to Web3** button. Choose **Metamask** from the wallet options. After authenticatng with Metamask, you shall see **Connected - Web3[address]** instead of the earlier button. Mak
> Click on the **Connect to Web3** button. Choose **Metamask** from the wallet options. After authenticatng with Metamask, you shall see **Connected - Web3[address]** instead of the earlier button. Make sure you are connected to the **Rinkeby** test network.

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +It will open up the metamask prompt. Make sure you are on the **Rinkeby** test network.
> It will open up the Metamask prompt. Make sure you are on the **Rinkeby** test network.

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +You shall get purchase you just created!
> You will see the information about the purchase you just created!

2021-09-14 23:53 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +Congratulations on finishing this tutorial! You have now learnt how to create and deploy your first subgraph, as well as query the subgraph using Subgraph Studio Playground.
> Congratulations on finishing this tutorial! You have learned how to create and deploy your first subgraph, as well as query the subgraph using the Subgraph Studio Playground.

2021-09-15 00:06 UTC, robin-thomas commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +- You will need Metamask installed in your browser. You can install it from https://metamask.io/
@pyr0gan How is it different from the already written line? Didnt understand.

2021-09-15 00:23 UTC, robin-thomas commented on network-documentation/thegraph/tutorials/query-ethereum-data-with-the-graph.md
> +Head over to https://thegraph.com/studio/subgraph/vending/ to start querying data with the Playground.
@pyr0gan Github handles that automatically. Or if you need the markdown to work elsewhere, then yeah, need to use the empty link text syntax.

2021-09-15 00:28 UTC, robin-thomas commented
Thanks for reviewing @pyr0gan! That was really helpful.

2021-09-15 18:52 UTC, pyr0gan approved these changes
Hi @robin-thomas, 

Thanks for the quick changes 🙏 😄. I will merge and get this published on the site, but just so you are aware it won't be promoted until we do our launch event for the Graph Protocol later in the month.

Do you have any more tutorials planned? What's next? 🚀

2021-09-16 16:58 UTC, merged