added NFT-Tutorial-Hardhat
figment-networks/datahub-learn pull request #235
Opened 2021-09-17 00:29 UTC by BhaskarDutta2209

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run the tutorial to test it and the code works.

2021-09-18 05:04 UTC, pyr0gan requested changes
Hi @BhaskarDutta2209 👋 Thanks for spending the time to write this helpful tutorial for the community! We appreciate your work 😄 

That was a surprising amount to cover. There are quite a few things to be fixed, so I think it's good to review my suggestions carefully 🧐  
Please remember to mark the conversations as resolved when you make the changes, so my next review can proceed quickly! 
If you have any questions or comments, please reply to the comment directly and tag me so I can find it easily.

2021-09-18 07:40 UTC, BhaskarDutta2209 commented on network-documentation/matic/tutorials/NFT-Tutorial-Using-hardhat.md
> +We start by importing the `@nomiclabs/hardhat-waffle` package which will give us access to the `hre` class. HRE is short for **Hardhat Runtime Environment** which is an object that contains all the f
Sorry but I didn't get what change I have to make in this section

2021-09-18 07:41 UTC, BhaskarDutta2209 commented on network-documentation/matic/tutorials/NFT-Tutorial-Using-hardhat.md
> +  solidity: "0.6.6",
Sorry, this was a stupid mistake.

2021-09-18 07:44 UTC, BhaskarDutta2209 commented on network-documentation/matic/tutorials/NFT-Tutorial-Using-hardhat.md
> +## Installing Openzeppelin library
In this section, I am adding a small detail about what smart contract we are going to write.

2021-09-18 07:58 UTC, BhaskarDutta2209 commented on network-documentation/matic/tutorials/NFT-Tutorial-Using-hardhat.md
> +```jsx
Sorry

2021-09-18 11:53 UTC, BhaskarDutta2209 commented on network-documentation/matic/tutorials/NFT-Tutorial-Using-hardhat.md
> +      url: "https://matic-testnet-archive-rpc.bwarelabs.com",
@pyr0gan It gives an error saying "only absolute URLs are supported"

2021-09-21 21:23 UTC, pyr0gan requested changes
Just a couple of small things to fix @BhaskarDutta2209 😄

2021-09-21 21:23 UTC, pyr0gan commented on network-documentation/matic/tutorials/NFT-Tutorial-Using-hardhat.md
> +- [OpenZeppelin Forun Page](https://forum.openzeppelin.com/t/function-settokenuri-in-erc721-is-gone-with-pragma-0-8-0/5978/3) about the setTokenURI change in Solidity 0.8.0.
> - [OpenZeppelin Forum Page](https://forum.openzeppelin.com/t/function-settokenuri-in-erc721-is-gone-with-pragma-0-8-0/5978/3) about the setTokenURI change in Solidity 0.8.0.

Remember to fix the typo in the link text: Forun -> Forum

2021-09-22 18:23 UTC, pyr0gan approved these changes

2021-09-22 19:29 UTC, merged