Deploy a Subgraph with Hardhat
figment-networks/datahub-learn pull request #237
Opened 2021-09-18 02:07 UTC by robin-thomas

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [ ] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [ ] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [ ] I've proofread the tutorial for spelling and grammar mistakes.
- [ ] I've run a linter & prettifier to format my code blocks.
- [ ] I've thoroughly explained the code, with inline code comments and text explanations.
- [ ] I've run the tutorial to test it and the code works.

2021-09-20 22:47 UTC, pyr0gan requested changes
Overall, I have a couple of concerns with this tutorial:

- It seems that you copied most of this tutorial from the previous Graph tutorial you submitted. This is problematic because you don't need to repeat the same information. Please give this tutorial another pass and see where it can be improved and made distinct from the other subgraph tutorial 😄 

- You forgot to get users to fund their Rinkeby accounts with testnet Ether. As is, this tutorial would leave users in a bind unless they already had a funded Rinkeby account. Please don't forget to add these instructions to the tutorial.

Besides this, please review my comments and mark the conversations as resolved when you make the necessary changes 🙏 😄

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +    modifier onlyOwner {
It would be a good idea to explain how the modifier works. You and I may understand this, but readers are unlikely to grasp the importance of this code without an explanation 😉

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +To compile the smart contract, run:
> To compile the smart contract via HardHat (which will still use the solc compiler), run:

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +You shall get the below output:
> Assuming there are no errors or warnings, this will output:

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +The smart contract has been compiled successfully.
> The `VendingMachine.sol` smart contract has now been compiled successfully.

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +To deploy to `Rinkeby` Ethereum testnet, you need to add a `network` entry to your `hardhat.config.js` file.
> To deploy to the Ethereum Rinkeby testnet with HardHat, you need to add a network entry to your `hardhat.config.js` file:

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +# Requirements
You seem to be missing a requirement for having a funded Rinkeby account. You'll need to add instructions for users to fund their testnet wallet via <https://faucet.rinkeby.io/> so that when they go to deploy later in the tutorial, they have the testnet Ether to do so.

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +You shall get the below output:
>  This will output:

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +# Creating the graph project in Subgraph Studio
You can rename the heading to: \# Creating the project in Subgraph Studio

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +Replace `<YOUR RINKEBY SMART CONTRACT ADDRESS>` with your deployed VendingMachine smart contract address from above.
> Replace <YOUR RINKEBY SMART CONTRACT ADDRESS> with your deployed VendingMachine smart contract address from above.

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +**Output:**
> This will output:

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +This will generate a build directory under `vending/build`.
> This will generate a build directory under `vending/build`. You should also see the following output:

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +**Output:**
You can remove this line 👍

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +You shall be prompted for a version label. You can choose `1.0.0`.
> You shall be prompted for a version label. You can choose `1.0.0`. You should see the following output:

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +**Output:**
You can remove this line 👍

2021-09-20 22:47 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +Congratulations on finishing this tutorial! You have learned how to deploy a smart contract using hardhat, as well as create and deploy its subgraph.
> Congratulations on finishing this tutorial! You have learned how to deploy a smart contract to the Rinkeby testnet using HardHat. You also learned how to create and deploy a subgraph for the smart contract on Subgraph Studio.

2021-09-20 23:17 UTC, robin-thomas commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +npm i -g yarn
@pyr0gan It's used by `@graphprotocol/graph-cli` when running the command: `graph init ...`. It uses `yarn` to install the dependencies.

2021-09-20 23:54 UTC, robin-thomas commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +npm i -g yarn
@pyr0gan  Anyway, I have replaced the `npm` commands with `yarn` to be consistent.

2021-09-21 23:22 UTC, pyr0gan approved these changes
Hey @robin-thomas, thanks for the quick changes. Just a couple of typos to fix and I believe we can publish the tutorial this week! 🚀

2021-09-21 23:22 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +        // verifying that the owner is same as the one who called the functioon.
>         // Verifying that the owner is same as the one who called the function.

2021-09-21 23:22 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +        // this is called the "nerge wildcard".
>         // This underscore character is called the "merge wildcard".

2021-09-21 23:22 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-with-hardhat.md
> +You have now deployed the subgraph to your Subgraph Studio account. It will now start the syncing process, where data is extracted from the historical blocks in Rinkeby Ethereum testnet by The Graph
> New blocks will be inspected by The Graph node as soon as they are mined.

2021-09-21 23:48 UTC, robin-thomas commented
Hi @pyr0gan, have fixed them all. Thanks for the quick review!

2021-09-22 18:24 UTC, pyr0gan approved these changes

2021-09-22 19:35 UTC, merged