First draft of tutorial on Flutter and Polygon
figment-networks/datahub-learn pull request #238
Opened 2021-09-19 06:56 UTC by viral-sangani

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run the tutorial to test it and the code works.

2021-09-21 04:30 UTC, pyr0gan requested changes
Hi @viral-sangani 👋 
Thanks for writing this tutorial!

The obvious issue here is that you said at the beginning that you'd be deploying to Polygon, but then only used a Ganache local development chain to deploy the contract. I'd appreciate it if you would fix that before I review it again 😄 

Most of the issues are straightforward grammar or formatting fixes. The code looks OK, except for the Solidity pragma issue I mentioned in a comment.

I know it's easy to use bullet lists when explaining code blocks, but I feel there may be a little but too much use of bullet lists in this document. Try to save them for when they're really needed 😄 

Other than that, have a look over my comments and make the needed changes 🙏 😄

2021-09-21 04:30 UTC, pyr0gan commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +- In the `getCredentials`function, first, we will create an instance of our smart contract using `_abiCode` and `_contractAddress`. Once we have a contract instance, we can create an instance of all
> - In the `getCredentials` function, we will create an instance of our smart contract using `_abiCode` and `_contractAddress`. Once we have a contract instance, we can create an instance of all the functions we have in the smart contract, as shown above in the code.

2021-09-21 04:30 UTC, pyr0gan commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +- `getTodos` function is used to fetch all the to-do items present in our smart contract. In `getTodos`, we shall call the `_taskCount` function, which gives us the total number of to-dos, and then w
> - In `getTodos`, we call the `_taskCount` function which gives us the total number of to-dos, and then we use a loop to fetch all to-do items and add them to a list. Once we have all the to-dos, we can set `isLoading` to false and call `notifyListeners` from the `Provider` package to update our UI.

2021-09-21 04:30 UTC, pyr0gan commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +- In `addTask`, we accept the task name as a parameter, set `isLoading` to `true`, and then call `_createTask` function using `_contract` object and passing `taskNameData` as parameter.
> - In `addTask`, we accept the task name as a parameter, set `isLoading` to true, and then call the `_createTask` function using `_contract` object and passing `taskNameData` as a parameter.

2021-09-21 04:30 UTC, pyr0gan commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +- In `updateTask`, we accept the `id` of the task and the updated `taskNameData` and make a transaction using our credentials to the smart contract. Notice that we are sending `id` as an instance of
> - In `updateTask`, we accept the `id` of the task and the updated `taskNameData` to make a transaction using our credentials to the smart contract. Notice that we are sending `id` as an instance of `BigInt` because the web3dart package requires all the numbers in `BigInt` format.

2021-09-21 04:30 UTC, pyr0gan commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +- `deleteTask` function will accept the `id` of the task to be deleted and call the `_deleteTask` function of our contract to delete that particular task from `todos` mapping in the smart contract.
> - The `deleteTask` function will accept the `id` of the task to be deleted and call the `_deleteTask` function of our contract to delete that particular task from the `todos` mapping in the smart contract.

2021-09-21 04:30 UTC, pyr0gan commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +- `toggleComplete` function will accept the `id` of a task, and it will toggle the value of the `isComplete` boolean value in our smart contract.
> - The `toggleComplete` function will accept the `id` of a task, and it will toggle the value of the `isComplete` boolean value in our smart contract.

2021-09-21 04:30 UTC, pyr0gan commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +Now that we are done with the logic part in Flutter let's move forward and create UI for our app.
> Now that we are done with the logic part in Flutter let's move forward and create the UI for our app.

2021-09-21 04:30 UTC, pyr0gan commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +- This is how our list of to-dos will look like -
> This is how our list of to-dos should look:

2021-09-21 04:30 UTC, pyr0gan commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +- This is how the bottom sheet will look like -
> This is how the bottom sheet should look:

2021-09-21 04:30 UTC, pyr0gan commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +You can find the source code of this project [here](https://github.com/viral-sangani/flutter-todo-dapp).
> You can find the complete source code of this project [on GitHub](https://github.com/viral-sangani/flutter-todo-dapp).

2021-09-21 04:30 UTC, pyr0gan commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +Congratulations on finishing the tutorial! Thank you for taking the time to complete it. In this tutorial, you have learned how to create a Flutter dapp from scratch using `web3dart`. Since Flutter i
> Congratulations on finishing the tutorial! Thank you for taking the time to complete it. In this tutorial, you have learned how to create a Flutter dApp from scratch using `web3dart`. Since Flutter is a multi-platform framework and the web3dart package supports all the platforms - Android, iOS, Linux, macOS, Web, and Windows you can use the same codebase to build multi-platform dApps very quickly.

2021-09-21 04:34 UTC, viral-sangani commented
@pyr0gan I am really sorry the deployment part just slipped out of my mind 😅. I'll add that and the changes right away.

2021-09-21 13:49 UTC, viral-sangani commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +- On top, we are importing all the required packages.
Yes, they were in the file. I will add it to the code.

2021-09-21 13:52 UTC, viral-sangani commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +- `Credentials _credentials` contains the `Credential` object of the logged-in player.
Actually I was taking reference from my other flutter dApp game that I created while writing this article. 😅

2021-09-21 15:27 UTC, pyr0gan commented
> @pyr0gan I have made the suggested changes.

Thanks @viral-sangani! I will review again today, if it looks good we can get this tutorial published this week 🚀

2021-09-21 23:32 UTC, pyr0gan approved these changes
Overall the changes are good, just refer to my comment about the DataHub endpoint URL. You'll need to add instructions to the Requirements section so that users have a DataHub account and a Polygon API key to be able to use that endpoint URL 👍

2021-09-21 23:32 UTC, pyr0gan commented on network-documentation/matic/tutorials/flutter-starter-for-polygon-dapp.md
> +          providerOrUrl: `https://matic-mumbai--rpc.datahub.figment.io/apikey/{DATAHUB_API_KEY}}/health`,
Ohh! Be careful with string interpolation. You missed the $ and you have one } too many! You also don't want to hit the health check endpoint for a provider URL 😉  Use this:

`https://matic-mumbai--rpc.datahub.figment.io/apikey/${DATAHUB_API_KEY}/`

Also, if you're using a DataHub endpoint you will need to add to the Requirements section, telling users to make a DataHub account and get a Polygon API key 😄

2021-09-22 16:20 UTC, viral-sangani commented
@pyr0gan I have added the DataHub section 👍

2021-09-22 18:28 UTC, pyr0gan approved these changes

2021-09-22 19:41 UTC, merged