Latest pairs added on Uniswap by Eloise
figment-networks/datahub-learn pull request #239
Opened 2021-09-20 10:29 UTC by Eloise1988

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run the tutorial to test it and the code works.

2021-09-23 07:01 UTC, zurgl requested changes
Hi @Eloise1988 

Thanks for writing this tutorial! It's pretty original, this is the first time I see something like that and I really appreciate it. Please review my comments.

2021-09-23 07:01 UTC, zurgl commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +<img width="1100" alt="potman_query" src="https://user-images.githubusercontent.com/53000607/133658202-670210a1-4509-4754-a164-1e22514d4594.png">
All images have to be part of the PR

2021-09-23 07:01 UTC, zurgl commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +<img width="977" alt="javascript_postman" src="https://user-images.githubusercontent.com/53000607/133802683-9462b554-06f8-4d52-9533-35491102f006.png">
All images have to be part of the PR

2021-09-23 14:53 UTC, Eloise1988 commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +[<img width="1381" alt="gif_uni" src="https://user-images.githubusercontent.com/53000607/133595220-6e918166-cfc9-4d9c-9b5b-5bc4395852ce.gif">](https://docs.google.com/spreadsheets/d/1tME9nMh79KzZP4Wm
I changed it to the following form :
![UNISWAP](https://github.com/Eloise1988/THEGRAPH/blob/main/IMAGES/UNISWAP.gif)

2021-09-23 14:53 UTC, Eloise1988 commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +### Prerequisites
Changed it to ##

2021-09-23 14:53 UTC, Eloise1988 commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +### First, what is Uniswap?
Changed it to ##

2021-09-23 14:53 UTC, Eloise1988 commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +[<img src=https://user-images.githubusercontent.com/53000607/132863640-4889463d-0e54-4a9e-b7ca-3a71017f8fc7.png width="450">](https://uniswap.exchange/swap)   <img src=https://user-images.githubuserc
I changed it to the following form :
![UNISWAPEXCHANGE](https://github.com/Eloise1988/THEGRAPH/blob/main/IMAGES/Uniswap_exchange.gif)

2021-09-23 14:53 UTC, Eloise1988 commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +[<img width="490" alt="thegraph" src="https://user-images.githubusercontent.com/53000607/133580577-56cecc0a-79c3-473d-83f9-6e9420ec6afd.png">](https://thegraph.com/legacy-explorer/) [<img width="510"
I changed the images in a gif
![UNISWAPv3SUBGRAPH](https://github.com/Eloise1988/THEGRAPH/blob/main/IMAGES/uniswapv3-subgraph.gif)

2021-09-23 14:53 UTC, Eloise1988 commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +[GraphQL](https://en.wikipedia.org/wiki/GraphQL) is an **open-source data query and manipulation language for APIs,** and a runtime for fulfilling queries with existing data. GraphQL was developed in
I changed to https://graphql.org/

2021-09-23 14:53 UTC, Eloise1988 commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +<img width="660" alt="std_graph_query" src="https://user-images.githubusercontent.com/53000607/133599485-8dd9fa85-f20c-4c29-9f04-cd843d593511.png"> <img width="340" alt="parameters_graph" src="https:
GIF
![PLAYGROUND](https://github.com/Eloise1988/THEGRAPH/blob/main/IMAGES/playground.gif)

2021-09-23 14:54 UTC, Eloise1988 commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +<img width="1437" alt="postmanclean" src="https://user-images.githubusercontent.com/53000607/133645104-1099b76f-41cd-4637-94e9-79b965dcce92.png">
IMAGE:
![PLAYGROUNDCONSTRAINTS](https://github.com/Eloise1988/THEGRAPH/blob/main/IMAGES/PLAYGROUNDCONSTRAINTS.png)
![POSTMANCLEAN](https://github.com/Eloise1988/THEGRAPH/blob/main/IMAGES/postmanempty.png)

2021-09-23 14:54 UTC, Eloise1988 commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +<img width="1100" alt="potman_query" src="https://user-images.githubusercontent.com/53000607/133658202-670210a1-4509-4754-a164-1e22514d4594.png">
IMAGE:
![POSTMANQUERY](https://github.com/Eloise1988/THEGRAPH/blob/main/IMAGES/postmanconstraints.png)

2021-09-23 14:54 UTC, Eloise1988 commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +<img width="330" alt="gs1" src="https://user-images.githubusercontent.com/53000607/133906614-c8cf356d-6fa2-4440-8e10-1b42b9e5f540.png"><img width="350" alt="gs2" src="https://user-images.githubuserco
GIF CREATED:
![GOOGLESHEETEDITOR](https://github.com/Eloise1988/THEGRAPH/blob/main/IMAGES/googlesheetmacro.gif)

2021-09-23 14:54 UTC, Eloise1988 commented on network-documentation/thegraph/tutorials/uniswap_latestpairs.md
> +[<img width="32%" alt="goog_auth_5" src="https://user-images.githubusercontent.com/53000607/132861811-0d7c4712-8f8c-4f4b-892c-2779a4035036.png"> <img width="32%" alt="goog_auth_4" src="https://user-i
I took out that part, it will be less confusing

2021-09-24 02:36 UTC, zurgl commented
@Eloise1988 Thanks for the quick feedback.
All the images should be part of the PR, currently I see only one file in the PR.

For example, for the first image you need to: 
* Copy `https://github.com/Eloise1988/THEGRAPH/blob/main/IMAGES/UNISWAP.gif` to `.gitbook/assets/UNISWAP.gif`
* Change ```![UNISWAP](https://github.com/Eloise1988/THEGRAPH/blob/main/IMAGES/UNISWAP.gif)``` to ```![UNISWAP](.gitbook/assets//UNISWAP.gif)``` in your markdown file

You need to do it for all the images.

Another requirement to publish you content is that we support only 2 levels for heading
 For example an accepted doc is like.
 ```text
 title 
 -------------------------------------------
 
 # Section 1
 
 lskjdlsjdlskj
 
 ## subSection 1
 
 sldksmldksmldks
 
 # Section 2
 
 sdklsmdk
 
 # Section 3
 
 ## subSection 3
 
 sdklsmdk
 
```
We cannot manage more than two level for headings.
I guess when theses two requirement I meet, i will be able to merge your work.

Thanks for your comprehensions.

2021-09-24 13:12 UTC, Eloise1988 commented
> @Eloise1988 Thanks for the quick feedback.
> All the images should be part of the PR, currently I see only one file in the PR.
> 
> For example, for the first image you need to:
> 
> * Copy `https://github.com/Eloise1988/THEGRAPH/blob/main/IMAGES/UNISWAP.gif` to `.gitbook/assets/UNISWAP.gif`
> * Change `![UNISWAP](https://github.com/Eloise1988/THEGRAPH/blob/main/IMAGES/UNISWAP.gif)` to `![UNISWAP](.gitbook/assets//UNISWAP.gif)` in your markdown file
> 
> You need to do it for all the images.
> 
> Another requirement to publish you content is that we support only 2 levels for heading
> For example an accepted doc is like.
> 
> ```
> title 
> -------------------------------------------
> 
> # Section 1
> 
> lskjdlsjdlskj
> 
> ## subSection 1
> 
> sldksmldksmldks
> 
> # Section 2
> 
> sdklsmdk
> 
> # Section 3
> 
> ## subSection 3
> 
> sdklsmdk
> ```
> 
> We cannot manage more than two level for headings.
> When theses two requirements are fulfilled, we will be able to merge your work.
> 
> Do not forget to mark the conversations as resolved when you've made the changes
> 
> Thanks for your comprehensions.

@zurgl Thank you for the feedback. I think this time I understood. I've downloaded all images in the subfolder .gitbook/assets/ and reference them in the tutorial with the corresponding path.

I also changed the headers so that there are on # an ##.
Regards,

2021-09-27 05:53 UTC, merged