new tutorial: sol-mint-nft, and also a spelling error edit to sol-mint-token
figment-networks/datahub-learn pull request #245
Opened 2021-09-27 17:32 UTC by jacobmakarsky

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [/] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [/] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [/] I've proofread the tutorial for spelling and grammar mistakes.
- [/] I've run a linter & prettifier to format my code blocks.
- [/] I've thoroughly explained the code, with inline code comments and text explanations.
- [/] I've run the tutorial to test it and the code works.

2021-09-27 19:39 UTC, pyr0gan requested changes
Hi @jacobmakarsky! Thanks for writing this tutorial 😄 

There are some changes to make to the section headings (and headings in general), have a look at my comments and remember to have a look at the sample tutorial as well. Tag me if you have any questions or concerns! I am here to assist you in making this a great resource for the community!

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +### **1) Fork the Metaplex repository to your Github**
This could be a top level heading as this is technically the beginning of the body of the tutorial:

> \# Fork the Metaplex repository

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +First, we are going to fork the metaplex repository to our Github so we can host it on Github pages.
> We are going to fork the Metaplex repository to our own Github account so that we can host it easily on Github pages.

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +* Fork the [Metaplex repository](https://github.com/metaplex-foundation/metaplex)
> * Fork the [Metaplex repository](https://github.com/metaplex-foundation/metaplex) and then follow the instructions for Installing: <https://github.com/metaplex-foundation/metaplex#installing>

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +```bash
\```text

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +```bash
\```text

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +### **3) Change the default addresses**
See previous comments about subheadings 👍

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +```bash
\```text

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +```bash
\```text

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +The command will take awhile to finish downloading everything. Once it's done, we will see a `Done` line at the end.
> The command will take a moment to finish downloading everything. When it is complete, it will output **Done** at the end.

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +```bash
\```text

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +* Run the `yarn bootstrap` command to check that all of the dependencies are working.
If you're using a code block to display the command, you can reword this sentence slightly:

> Run the following command to check that all the dependencies are in place and working as intended:

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +We can now locally test our new NFT marketplace before we upload it to the internet.
> We can now test our new NFT marketplace locally before we upload it to Github Pages.

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +```bash
\```text

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +* Run the `yarn build` command
If you're using a code block to show the command, you can rewrite this sentence slightly:

> Run the following command to build the project files:

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +After a bit of time, we should see a `Done` line, indicating the build has finished. We will now see a `build` folder inside the `js` folder.
> When it is complete, we should see it output **Done**, indicating the build has finished. We will now be able to  see the `build` folder that was created inside the `js` folder.

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +```bash
\```text

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +We should again see a `Done` line, indicating the deployment has finished. This command has deployed our marketplace to our Github repository, which means... our marketplace is live!
> Once complete, we should again see the output **Done**, indicating the deployment has finished. This command has deployed the marketplace site to our Github repository, which means... our marketplace is live! Now we can go check out the fresh new NFT marketplace operating on Solana, hosted on Github Pages.

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +Now, we can move on to creating our own NFT on Solana by using our marketplace.
> Now, we can move on to creating our own NFT on Solana by using the marketplace UI.

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +### **5) Mint an NFT on a marketplace**
See previous comments about headings.

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +Metaplex allows us to modify the royalties and amount to split of the intiial sale.
> Metaplex allows us to modify the royalties and amount to split of the initial sale.

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +### **6) BONUS: List the NFT for sale**
See previous comments on headings.

2021-09-27 19:39 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +* Go to [DigitalEyes](https://digitaleyes.market/)
As a general comment, it feels like you're overusing bullet points in this tutorial. It is preferable to use sentences without the bullet points, especially when you are explaining things visually with a series of images.

2021-09-28 17:17 UTC, jacobmakarsky commented
Hello, I have made the changes

2021-09-29 21:51 UTC, pyr0gan requested changes
Hi @jacobmakarsky, just a few more touchups and we should be good to publish 😄

2021-09-29 21:51 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +In this tutorial we will be creating a [non-fungible token](https://www.blockchain-council.org/blockchain/a-quick-guide-to-fungible-vs-non-fungible-tokens/#:~:text=Non%2DFungible%20are%20Non%2DInterc
> In this tutorial we will be creating a marketplace and a [non-fungible token](https://www.blockchain-council.org/blockchain/a-quick-guide-to-fungible-vs-non-fungible-tokens/), otherwise known as an NFT, using the **Solana** blockchain. Since NFTs can be made as single _or_ multiple editions, they can be used to represent real-world objects like music, art, in-game items and videos.

2021-09-29 21:51 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +* Around $2 USD of [SOL](https://coinmarketcap.com/currencies/solana/) accessible, which we will send to a browser wallet. You can get some SOL through an exchange, such as [FTX](https://ftx.com/#a=1
> * You will need around $2 USD of [SOL](https://coinmarketcap.com/currencies/solana/) accessible, which we will send to a browser wallet. You can get some SOL through an exchange, such as [FTX](https://ftx.com/#a=13426316).

2021-09-29 21:51 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +* [Github account](https://github.com/)
> * A [GitHub](https://github.com/) account

2021-09-29 21:51 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +* Fork the [Metaplex repository](https://github.com/metaplex-foundation/metaplex)
I highly recommend this change, otherwise readers might just fork the repo and carry on without understanding that they need to install its dependencies via `yarn install` in order to run the code.

2021-09-29 21:51 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +![cdMarketplaceSol](../../../.gitbook/assets/cdMarketplaceSol.png)
This image is not required, you can remove it 😄
Readers will grasp the concept well enough with your instructions 👍

2021-09-29 21:51 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +![cdJsSol](../../../.gitbook/assets/cdJsSol.png)
This image is not required, you can remove it 😄

2021-09-29 21:51 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +![yarnPackagesSol](../../../.gitbook/assets/yarnPackagesSol.png)
This image is not required, you can remove it 😄

Mainly for aesthetics on the page, but also because readers will see the terminal output for themselves - which will be pretty different than this image.

2021-09-29 21:51 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +* Run the `yarn bootstrap` command to check that all of the dependencies are working.
You can choose to show the command in a sentence, or in a code block. Both is too much 😄

2021-09-29 21:51 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +cd packages/web
Given the context of the image above, this is mildly confusing. Does the build command need to be run in the `packages/web` folder, because that's the impression I get from that image.

Possibly just remove the image?

2021-09-30 18:14 UTC, jacobmakarsky commented on network-documentation/solana/tutorials/sol-mint-nft.md
> +![cdMarketplaceSol](../../../.gitbook/assets/cdMarketplaceSol.png)
Hello, on line 89, I have them run `yarn`, which is the same as `yarn install`

2021-09-30 18:20 UTC, jacobmakarsky commented
Hello, I believe I made all of the requested edits

2021-09-30 21:04 UTC, pyr0gan approved these changes

2021-09-30 23:52 UTC, merged