add tutorial for near registry
figment-networks/datahub-learn pull request #246
Opened 2021-09-27 20:49 UTC by viraja1

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [ ] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [ ] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [ ] I've proofread the tutorial for spelling and grammar mistakes.
- [ ] I've run a linter & prettifier to format my code blocks.
- [ ] I've thoroughly explained the code, with inline code comments and text explanations.
- [ ] I've run the tutorial to test it and the code works.

2021-09-28 16:18 UTC, pyr0gan requested changes
Hi @viraja1!  Thanks for writing this tutorial 🙏 

There are a few things to fix before we can publish. In particular, please pay attention to the section headings. Be aware that the Table of Contents is generated automatically from these headings so to keep it well ordered, it is important to only use H1 and H2 headings (# and ## respectively).

If you have any questions or concerns, please tag me in a comment and we can discuss the issue!

2021-09-28 16:18 UTC, pyr0gan commented on network-documentation/near/tutorials/near-registry-dapp.md
> +Run the following commands from the near-registry folder
> To see the frontend as it will appear after deployment, we need to use the local development server. Run the following commands from the `near-registry` directory:

2021-09-28 16:18 UTC, pyr0gan commented on network-documentation/near/tutorials/near-registry-dapp.md
> +Then visit http://localhost:1234 from your browser to test the Near Registry
> Now you can visit <http://localhost:1234> in your browser to test the NEAR Registry frontend and smart contracts deployed on the NEAR testnet.

2021-09-28 16:18 UTC, pyr0gan commented on network-documentation/near/tutorials/near-registry-dapp.md
> +Run the following commands from the near-registry folder
When you are happy with the looks and functionality of the dApp, you can deploy to a remote server. Run the following commands from the `near-registry` folder:

2021-09-28 16:18 UTC, pyr0gan commented on network-documentation/near/tutorials/near-registry-dapp.md
> +```bash
\```text

2021-09-28 16:18 UTC, pyr0gan commented on network-documentation/near/tutorials/near-registry-dapp.md
> +Then follow the instructions given by the netlify cli and specify `./dist` as the publish directory
> You must follow the instructions given by the netlify CLI and specify `./dist` as the publish directory.

2021-09-28 16:18 UTC, pyr0gan commented on network-documentation/near/tutorials/near-registry-dapp.md
> +Congratulations! We have successfully deployed the NEAR Registry smart contract on the NEAR testnet. We have also tested the smart
> Congratulations! We have successfully deployed the NEAR Registry smart contract on the NEAR testnet. We have also tested the smart contracts by writing the test cases. We have then interacted with the smart contracts using the React frontend.

2021-09-28 18:29 UTC, viraja1 commented on network-documentation/near/tutorials/near-registry-dapp.md
> +In this tutorial we will be building a complete Dapp for the Near Registry. Near Registry will allow you to track popular
@pyr0gan Thanks for the review. Pushed all the changes

2021-09-28 18:29 UTC, viraja1 commented on network-documentation/near/tutorials/near-registry-dapp.md
> +In this tutorial we will be building a complete Dapp for the Near Registry. Near Registry will allow you to track popular
@pyr0gan Thanks for the review. Pushed all the changes

2021-09-28 19:03 UTC, viraja1 commented on network-documentation/near/tutorials/near-registry-dapp.md
> +**assembly/__tests__/registry.spec.ts**
pushed the change

2021-09-28 19:03 UTC, viraja1 commented on network-documentation/near/tutorials/near-registry-dapp.md
> +**assembly/__tests__/registry.spec.ts**
pushed the change

2021-09-29 20:56 UTC, pyr0gan approved these changes

2021-09-30 23:18 UTC, merged