Deploy a subgraph using Avalanche network
figment-networks/datahub-learn pull request #247
Opened 2021-09-28 01:23 UTC by robin-thomas

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [ ] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [ ] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [ ] I've proofread the tutorial for spelling and grammar mistakes.
- [ ] I've run a linter & prettifier to format my code blocks.
- [ ] I've thoroughly explained the code, with inline code comments and text explanations.
- [ ] I've run the tutorial to test it and the code works.

2021-09-28 21:40 UTC, pyr0gan requested changes
Hi @robin-thomas 👋 

Thanks for another succinct tutorial. There are a few fixes to be made before we can publish. Please review my comments and remember to mark the conversations as resolved as you make the changes 🙏

2021-09-28 21:40 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-using-avalanche.md
> +Add a `network` entry in your `hardhat.config.js` file:
> Add the constants `FUJI_PRIVATE_KEY` and `DATAHUB_API_KEY` as well as a **networks** entry in your `hardhat.config.js` file:

2021-09-28 21:40 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-using-avalanche.md
> +Click on `Avalanche`, and you shall see the below page at <https://datahub.figment.io/services/avalanche>. You can copy your api key by clicking on the `copy` button.
> Click on the `Avalanche` button to view the Avalanche Services Dashboard at <https://datahub.figment.io/services/avalanche>. You can copy your API key to the clipboard by clicking on the **copy** button.

2021-09-28 21:40 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-using-avalanche.md
> +You need to add FUJI testnet to your Metamask by following the instructions below:
> You need to add a connection to the Avalanche Fuji testnet to your Metamask by following the instructions below (remember to replace \<YOUR DATAHUB_API_KEY\> in the RPC URL with your actual DataHub API key):

2021-09-28 21:40 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-using-avalanche.md
> +Create a directory called `scripts`, and paste the below code into a new file `deploy.js` inside scripts directory.
> Create a subdirectory inside the HardHat project called `scripts`, and paste the following code into a new file `deploy.js` inside the `scripts` directory:

2021-09-28 21:40 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-using-avalanche.md
> +Finally, run:
> To deploy the smart contract to the Fuji testnet using HardHat, run the command:

2021-09-28 21:40 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-using-avalanche.md
> +Yay! You just deployed your smart contract successfully to Fuji testnet!
> Congratulations! You just deployed your smart contract successfully to Fuji testnet! We will need the contract address when creating the subgraph, so remember to copy it.

2021-09-28 21:40 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-using-avalanche.md
> +Replace with your deployed VendingMachine smart contract address from above.
> Replace \<YOUR FUJI SMART CONTRACT ADDRESS\> with your deployed VendingMachine smart contract address from above.

2021-09-28 21:40 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-using-avalanche.md
> +✖ Failed to fetch ABI from Etherscan: request to https://api-fuji.etherscan.io/api?module=contract&action=getabi&address=<YOUR FUJI SMART CONTRACT ADDRESS> failed, reason: getaddrinfo ENOTFOUND api-f
HardHat is constructing the URL to fetch the ABI incorrectly. Network values such as "rinkeby" or "ropsten" would work because those domains (<https://api-rinkeby.etherscan.io/>) exist. I think it would be best to remove this error entirely and just go with passing the path to the locally generated ABI with the `--abi` flag in the first place 😄

2021-09-28 21:40 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-using-avalanche.md
> +✔ Ethereum network · rinkeby
Shouldn't this be fuji ?

2021-09-28 22:31 UTC, robin-thomas commented
Thanks for the review @pyr0gan! Have fixed all the comments.

2021-09-29 02:31 UTC, pyr0gan commented on network-documentation/thegraph/tutorials/deploy-subgraph-using-avalanche.md
> +graph init \
Just need to be careful with multiline input. This will cause an issue for any Windows users who attempt to copy and paste this into their terminal. To cover this case, you can include a note for Windows users to replace the \ characters with ^ for multiline input.

2021-09-29 02:33 UTC, pyr0gan approved these changes
Thanks for the quick update @robin-thomas! Just add a note about the multiline input character for Windows users per my comment, and we should be able to get this tutorial published this week (it will be promoted next week during our launch of The Graph on Learn 🚀 😄 )!

2021-09-30 23:43 UTC, merged