Build a mail app on Solana
figment-networks/datahub-learn pull request #250
Opened 2021-09-29 18:04 UTC by Segun-Ogundipe

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run the tutorial to test it and the code works.

2021-09-30 21:01 UTC, pyr0gan requested changes
Hi @Segun-Ogundipe!

This is a fairly complex tutorial, and besides a handful of typos and some code indentation issues I think most of the changes relate to wording. My main concern is with the section headings and how that will effect the Table of Contents. Please have a look at my comments and make the appropriate changes. Don't forget to mark the conversations as resolved when you make the changes so my next review can proceed more quickly 👍 

What is your timeline on completing the UI portion of the tutorial? 😄

2021-10-01 02:37 UTC, Segun-Ogundipe commented on network-documentation/solana/tutorials/solana-mail.md
> +...
The explanation explains the code. I agree with you, it's not needed here

2021-10-01 02:43 UTC, Segun-Ogundipe commented on network-documentation/solana/tutorials/solana-mail.md
> +## processor part 1
What do you suggest, would it make more sense to make them headings or just remove them entirely?

2021-10-01 03:00 UTC, Segun-Ogundipe commented on network-documentation/solana/tutorials/solana-mail.md
> +We pass the reference to the slice holding the `instruction_data` from the `process_instruction()` function in the `entrypoint.rs` module to the `unpack()` method of `MailInstruction`. We then use `m
I'm going with you on this

2021-10-01 03:36 UTC, Segun-Ogundipe commented on network-documentation/solana/tutorials/solana-mail.md
> +You might notice the tricky `&mut &mut account.data.borrow_mut()[..]` expression. The `serialize()` method takes a reference to a mutable slice of u8 as an argument, the `borrow_mut()` method returns
I'm done with the Web project. I'm working on the tutorial now. Should be done by Saturday

2021-10-01 03:46 UTC, Segun-Ogundipe commented on network-documentation/solana/tutorials/solana-mail.md
> +Notice the `clone()` call on the mail reference?, `mail` is a reference to a `mail` instance, not an instance itself. The `push()` method takes a mail instance argument and not a refernce to one, and
The described process was described while adding code to the `error.rs` module. They just check the section and they should be able to add the error. Maybe I should make that obvious here?

2021-10-01 04:08 UTC, Segun-Ogundipe commented
Thank you for the clear review @pyr0gan, detailed as always 😃. 
I left some comments on some of the reviews.

The UI portion should be ready by Saturday

Thank you

2021-10-04 15:30 UTC, pyr0gan approved these changes

2021-10-04 15:30 UTC, pyr0gan commented on network-documentation/solana/tutorials/solana-mail.md
> +For ecample, say Alice creates an account on our program. What that means for us is to generate a [Program Derived Address (PDA)](https://docs.solana.com/developing/programming-model/calling-between-
> For example

2021-10-04 15:30 UTC, pyr0gan commented on network-documentation/solana/tutorials/solana-mail.md
> +The first `if statement` checks wether the account is writable and returns an error if it's not. `NotWritable` is a custom error and should be added to the `MailError` struct in the `error.rs` module
> checks whether

2021-10-05 18:42 UTC, pyr0gan commented
@Segun-Ogundipe Just two small changes to make and we can publish your tutorial 😄 🚀

2021-10-11 18:18 UTC, pyr0gan commented on network-documentation/solana/tutorials/solana-mail.md
> +There's still a lot of grounds to cover on this project. For instance, data store on Solana are not private, they can be accessed and read by the public. A consequence of this for this project is tha
> There's still a lot of ground to cover on this project. For instance, data stored on Solana is not private, it can be accessed and read by the public. A consequence of this for this project is that mails sent between users are visible to the public. It'll be nice to add end-to-end encryption to the mails sent between to parties, this way users can be sure that their messages are can only be read by them. This will make for a nice challenge!

2021-10-11 18:18 UTC, pyr0gan commented on network-documentation/solana/tutorials/solana-mail.md
> +# About the Authors
\# About the Author

2021-10-13 23:03 UTC, merged