Rx/staging
figment-networks/datahub-learn pull request #258
Opened 2021-10-03 15:38 UTC by pyr0gan

- Reviewed The Graph pathway steps 1, 2, 3

2021-10-03 15:50 UTC, zurgl requested changes
@pyr0gan Thanks, for your review. Just a minor change to do and it's ok for me.

2021-10-03 15:50 UTC, zurgl commented on figment-learn/new-pathways/the_graph/the-graph-01-run-a-graph-node.md
>  sudo ETHEREUM_RPC=mainnet:https://eth-mainnet.alchemyapi.io/v2/<API-KEY> docker-compose up
We should remove the `sudo` and replace docker-compose up by `docker compose up`

2021-10-03 16:50 UTC, pyr0gan commented on figment-learn/new-pathways/the_graph/the-graph-01-run-a-graph-node.md
>  sudo ETHEREUM_RPC=mainnet:https://eth-mainnet.alchemyapi.io/v2/<API-KEY> docker-compose up
👍 done!

2021-10-05 14:33 UTC, zurgl commented on figment-learn/new-pathways/the_graph/the-graph-setup.md
> -![](../../../.gitbook/assets/pathways/the-graph/graph-alchemy-setup.gif)
not sure it's a good idea

2021-10-05 14:33 UTC, merged