Blockchain Based Skill Verification System Tutorial
figment-networks/datahub-learn pull request #272
Opened 2021-10-11 19:17 UTC by Hardikag17

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run the tutorial to test it and the code works.

2021-10-13 22:27 UTC, pyr0gan commented
Hi @Hardikag17,

Thanks for submitting this tutorial! Before we can review it, there are some issues we would like you to address:

- Fix all headings, keeping in mind that they form the Table of Contents. Refer to the [sample tutorial structure](https://www.notion.so/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) for guidance on section headings.
- Make sure that all code blocks have a newline before and after, and that every code block has the proper syntax highlighting type.
- Please check the spelling, capitalization, punctuation and grammar of your tutorial thoroughly. I recommend signing up for a free [Grammarly](http://grammarly.com) account, it is a powerful tool to check your writing.

When you have addressed these issues, I will be able to proceed with a review of the tutorial.

2021-10-31 23:37 UTC, pyr0gan commented
> @pyr0gan we have made the required changes, please let me know what more changes are required.

hi @Hardikag17, I'll give this a final review tomorrow - Monday, November 1st.

2021-11-01 16:41 UTC, pyr0gan requested changes
Hi @Hardikag17, a couple of small issues to wrap up and we should be good to publish this week 🚀

2021-11-01 16:41 UTC, pyr0gan commented on network-documentation/matic/tutorials/Blockchain-Based-Skill-Verification-System.md
> +      host: '127.0.0.1', // locahost
Fix typo: locahost -> localhost

2021-11-01 16:41 UTC, pyr0gan commented on network-documentation/matic/tutorials/Blockchain-Based-Skill-Verification-System.md
> +// Deploys the smart contract "Decenraskill"
Fix typo: Decenraskill -> Decentraskill

2021-11-01 16:41 UTC, pyr0gan commented on network-documentation/matic/tutorials/Blockchain-Based-Skill-Verification-System.md
> +/*
Does this need to be a multiline comment?

2021-11-01 16:41 UTC, pyr0gan commented on network-documentation/matic/tutorials/Blockchain-Based-Skill-Verification-System.md
> +Now, Let say any employee does not work in a particular company so, to remove the employee from the company employee list we have two options either we shift the list after removing the employee from
Holy run-on sentence, Batman 😵 Let's fix this up, yeah? 

> Now let's say an employee no longer works at a particular company - to remove the employee from the company's employee list we have two options:
> - Shift the list after removing the employee from the particular position. This method will be costly as it will require paying more gas fees.
> - An alternative is to change the employee id value to store a dummy user id in place, which can later be reused to store a new employee in that list. For this, we made a dummy user profile in the constructor which can be reused after it has been initialized (remember the constructor is called once when a Solidity smart contract is deployed).

2021-11-01 16:41 UTC, pyr0gan commented on network-documentation/matic/tutorials/Blockchain-Based-Skill-Verification-System.md
> +To approve a manager, the function _approve_manager_ will take the employee id as input and verify that the account calling the function has a "company" account type. It will then make sure that this
> To approve a manager, the function `approve_manager` will take the employee id as input and verify that the account calling the function has a "company" account type. It will then make sure that this employee id is present in the company's "current employees" list. If these checks pass, it will give that employee a manager tag by setting its `is_manager` boolean to true.

2021-11-01 16:41 UTC, pyr0gan commented on network-documentation/matic/tutorials/Blockchain-Based-Skill-Verification-System.md
> +To add to skills a user will call a function that will push the input skill into the `skills` list.
> To add to their list of skills, a user will call the `add_skill` function to push the input skill into the `skills` list.

2021-11-01 16:41 UTC, pyr0gan commented on network-documentation/matic/tutorials/Blockchain-Based-Skill-Verification-System.md
> +      skillName,
You're passing `skillId` to the function and the `endorse_skill` function in the Solidity file takes a skillId so this is a little confusing. Are you sure this is correct? I think it should be `skillId` here, not `skillName`.

2021-11-01 16:41 UTC, pyr0gan commented on network-documentation/matic/tutorials/Blockchain-Based-Skill-Verification-System.md
> +Put both **URL** and **mnemonic** into a dotfile (.env) and add the filename to the .gitignore file so that you won't expose your secrets accidentally.
> Put both **URL** and **mnemonic** into a dotfile (`.env`) as the values of `REACT_APP_POLYGON_MUMBAI_RPC_URL` and `REACT_APP_MNEMONIC` respectively. Also remember to add the `.env` filename to your `.gitignore` file so that you won't expose your secrets accidentally.

2021-11-01 16:41 UTC, pyr0gan commented on network-documentation/matic/tutorials/Blockchain-Based-Skill-Verification-System.md
> +**URL:** The RPC URL for connecting to the network. Although you can use a public RPC URL, it is recommended that you use private RPCs (from DataHub or Infura).
It's also important to point out that the DataHub URL must include the users API key.

2021-11-01 19:28 UTC, Hardikag17 commented
@pyr0gan Thank you for giving time to review our work we are really greateful. We have made the required changes, please let me know what more changes are required.

2021-11-01 20:25 UTC, pyr0gan approved these changes

2021-11-01 22:52 UTC, merged