Create tezos-testing-tutorial.md
figment-networks/datahub-learn pull request #273
Opened 2021-10-12 07:25 UTC by Udit-Kapoor

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [.] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [.] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [.] I've proofread the tutorial for spelling and grammar mistakes.
- [.] I've run a linter & prettifier to format my code blocks.
- [.] I've thoroughly explained the code, with inline code comments and text explanations.
- [.] I've run the tutorial to test it and the code works.

2021-10-14 08:14 UTC, Udit-Kapoor commented
Hey @pyr0gan 
I have cleaned up the highlighted issues.
Do take it up for review and let me know further changes.

2021-10-23 01:52 UTC, pyr0gan commented
> Hey @pyr0gan I have cleaned up the highlighted issues. Do take it up for review and let me know further changes.

Thanks for taking care of the issues, I'll review this over the weekend.

2021-10-31 23:38 UTC, pyr0gan commented
> Hey @pyr0gan Thanks for reviewing the tutorial. I have resolved all the mentioned suggestions. Do take a look and let me know if there are any more changes required.

Hi @Udit-Kapoor, I'll give this a final review tomorrow - Monday, November 1st 😄

2021-11-01 16:48 UTC, pyr0gan requested changes
Hey @Udit-Kapoor,

Just a few small fixes to make and this should be good to publish this week 🚀 😄

2021-11-01 16:48 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-testing-tutorial.md
> +#addBalanceOwner Tests
The # style comments inside of code blocks break the ToC rendering on our site. In this case I think we can just remove the comment, it isn't really adding anything to the code block here.

2021-11-01 16:48 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-testing-tutorial.md
> +ob.addBalanceOwner().run(sender=udit , amount = sp.tez(25) , valid = False)
Just fix the spacing on lines 172 and 173 to match the rest of the code block 👍

2021-11-01 16:48 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-testing-tutorial.md
> +ob.addBalanceCounterparty().run(sender=bob , amount = sp.tez(5) , valid = False)
See comments above, same fixes -

- Remove # comment
- Fix spacing

2021-11-01 16:48 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-testing-tutorial.md
> +    #Test Scenario
Just remove the # comments from this code block, as they break the Table of Contents otherwise. Our Markdown renderer thinks they are headings.

2021-11-01 17:08 UTC, Udit-Kapoor commented
@pyr0gan 
I have made all the changes requested in the review.
Do let me know if there is an alternative to add comments to python code block or if it looks and reads fine with the changes

2021-11-01 17:26 UTC, pyr0gan approved these changes
Just fix the spacing and we're good 😄

2021-11-01 17:26 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-testing-tutorial.md
> +ob.addBalanceOwner().run(sender=udit , amount = sp.tez(25) , valid = False)
> `ob.addBalanceOwner().run(sender = udit , amount = sp.tez(25) , valid = False)`
> `ob.addBalanceOwner().run(sender = bob , amount = sp.tez(1) , valid = False)`

2021-11-01 17:26 UTC, pyr0gan commented on network-documentation/tezos/tutorials/tezos-testing-tutorial.md
> +ob.addBalanceCounterparty().run(sender=bob , amount = sp.tez(5) , valid = False)
> `ob.addBalanceCounterparty().run(sender = bob , amount = sp.tez(5) , valid = False)`
> `ob.addBalanceCounterparty().run(sender = udit , amount = sp.tez(25) , valid = False)`

2021-11-01 22:58 UTC, merged