Sol Blog Dapp tutorial
figment-networks/datahub-learn pull request #281
Opened 2021-10-18 03:30 UTC by kiran-bhalerao

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [ ] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [ ] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [ ] I've proofread the tutorial for spelling and grammar mistakes.
- [ ] I've run a linter & prettifier to format my code blocks.
- [ ] I've thoroughly explained the code, with inline code comments and text explanations.
- [ ] I've run the tutorial to test it and the code works.

2021-10-19 10:03 UTC, yash-sharma1 commented on network-documentation/solana/tutorials/sol-blog-dapp.md
> +## Deploying to Devnet
You created the Solana Blog program and also written down the tests for Blog prgram but you didn't mention about the front end of the Blog dApp, it necessary to have a front-end and connect front end with the deployed Solana prgram. Please add these steps too. It shoudl be a fully functonal dApp with front end. Once you have a front end make sure to include GIF of it in the tutorial.

2021-10-19 10:04 UTC, yash-sharma1 commented on network-documentation/solana/tutorials/sol-blog-dapp.md
> +## Conclusion
Conclusion should be more detailed. At least 5-6 lines explain what all we have learned in teh tutorial, what should be the next step after this. For ref. please other published tutorials on Learn.

2021-10-19 10:06 UTC, yash-sharma1 commented on network-documentation/solana/tutorials/sol-blog-dapp.md
> +This tutorial was created by [Kiran Bhalerao](https://github.com/kiran-bhalerao). If you have any suggestions/questions feel free to contact with author.
It should be -
This tutorial was created by [Kiran Bhalerao](https://github.com/kiran-bhalerao). For any suggestions/questions you can connect with author on Figment Forum (add link to your Figment Forum profile)

2021-10-21 15:21 UTC, yash-sharma1 commented
@kiran-bhalerao can you please make the required changes as suggested in the first review of the tutorial? As soon as you'll make these changes we'll give it a final review before merging it :)

2021-11-01 17:07 UTC, pyr0gan requested changes
Hey @kiran-bhalerao,

Some more fixes to make before we can publish, but nothing too difficult. Just have a look over my comments and make the necessary changes 👍

2021-11-01 17:07 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-blog-dapp.md
> +Now we complete remaining tests:
It is still unclear which file this code belongs in. Please provide the filename where users need to add this code.

2021-11-01 17:07 UTC, pyr0gan commented on network-documentation/solana/tutorials/sol-blog-dapp.md
> +folder structure of React spp
> The directory structure of a basic React app made with `create-react-app`:

2021-11-01 17:40 UTC, kiran-bhalerao commented
@pyr0gan made all the fixes. please review.

2021-11-01 17:57 UTC, pyr0gan approved these changes

2021-11-01 21:25 UTC, merged