Build a quadratic voting dapp on Polygon
figment-networks/datahub-learn pull request #286
Opened 2021-10-19 01:38 UTC by giraffekey

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request" make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).
If you do not follow these guidelines, it might take longer for us to review your tutorial and get it published on Learn.

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [x] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run the tutorial to test it and the code works.

2021-10-19 04:50 UTC, pyr0gan requested changes
Hi @giraffekey, 

Thanks for writing this tutorial! It was a pleasure to review. There are some small fixes to be made. Be sure to mark the conversations as resolved as you make changes so that my next review can proceed quickly 🙏 

The Chewbacca thing legitimately made me laugh pretty hard 🤣

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +```bash
\```text

See the [sample tutorial](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) for guidance on syntax highlighting.

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +> Default (Vue 3)
I'm actually not entirely sure how blockquotes would look inside a code block. Better to keep only the terminal commands you want readers to perform in the code block! Remove the \> and explain to readers how to proceed with CLI prompts outside of the code block 😄

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +As an example of how quadratic voting works, let's say this contract was for a ranked list of the most favored Star Wars characters. One person may suggest Han Solo while another may suggest Chewbacc
I like the Star Wars reference. Han shot first, though!

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +The `voteCost` constant is the price of a vote of weight 1 in terms of wei. One ether consists of 1,000,000,000,000,000,000 wei and one gwei consists of 1,000,000,000 wei. Therefore, `voteCost` is se
Might be worthwhile to raise the point that even though the Solidity will be referring to units in Ethereum denominations, if it is deployed on Polygon then MATIC will be used instead of ETH (although the decimals remain the same).

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +Users are not able to vote for their own items because this would allow them to claim what they spent and use it to vote again, essentially meaning they could infinitely vote on their own items. Ther
Technically, someone could just use a different wallet address to cycle their own MATIC through the dApp. It's a tricky topic, for sure. I don't think there's a need to go down that particular road in the tutorial but it isn't as cut and dry as preventing a single address from voting on their own items 🤷

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +Note that this will reward items whose total voting weight is more negative than positive, which essentially means that even the worst suggestions will still make a partial income from this mechanism
> ... To keep things simple, we will not dive into that topic in this tutorial.

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +We'll need to compile our contracts before we can use them. We can do this with the Truffle cli tool we installed earlier.
> ... We can do this with the Truffle CLI tool we installed earlier.

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +```bash
\```text

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +The Truffle cli will use this file later to deploy our `QuadraticVoting` contract.
> The Truffle CLI will use this file later to deploy our `QuadraticVoting` contract.

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +We'll need to create an account [here](https://rpc.maticvigil.com/) to have a quota for the RPC. Create an App and replace `{APP_ID}` in the config with the App Id.
DataHub would also be a great choice 😉

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +Make sure to install the HD wallet provider.
> Make sure to install the HD wallet provider class from Truffle, so we can supply a mnemonic to sign the deployment transaction.

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +In order to publish contracts to the blockchain we will need to pay the gas fees. Get testnet MATIC from the [Mumbai faucet](https://faucet.polygon.technology/) by inputting your wallet address.
I've noticed some issues with the Polygon faucet, where it gives an error the first several times you click to confirm the transaction. Just be careful about that. More explanation may be required here.

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +```bash
\```text

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +            "The ultimate furry.", // description
Letting the wookie win, are we? 😉

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +```bash
\```text

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +Now we'll be using Web3 to communicate with our smart contracts from JavaScript.
> Now we'll be using web3.js to communicate with our smart contracts from JavaScript.

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +```bash
\```text

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +;(async () => {
Is that semicolon intentional?

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +- `contract`: An instance of our QuadraticVoting contract which allows us to use its methods and events.
> - `contract`: An instance of our `QuadraticVoting` contract which allows us to use its methods and events.

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +```js
I recommend adding a sentence to let readers know this code is still being added to `src/lib/quadratic-voting.js`

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +```bash
\```text

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +Congratulations! After completing this tutorial, you should now know how to create a smart contract in Solidity, interact with smart contracts using Web3, deploy contracts to the Polygon testnet and
> ... You are now on your way to becoming a full stack dApp developer.

Let's not go _too_ wild, hey? 😉

2021-10-19 04:50 UTC, pyr0gan commented on network-documentation/matic/tutorials/build-a-quadratic-voting-ranked-list-dapp.md
> +```bash
\```text

2021-10-21 22:46 UTC, giraffekey commented
![image](https://user-images.githubusercontent.com/11844126/138366975-0a91a56f-b560-423a-89d1-4210e8d9081f.png)

I did push it to the fork. It shows up here and I see the changes in the diffs. The conversations also became labeled "Outdated" soon after the update. Was I supposed to push elsewhere?

2021-10-23 01:47 UTC, pyr0gan approved these changes

2021-10-31 03:09 UTC, giraffekey commented
@pyr0gan Wondering, when is pull?

2021-10-31 23:33 UTC, pyr0gan commented
> @pyr0gan Wondering, when is pull?

I have been away from home, and just got back today. I'll get this merged on Monday 👍

2021-11-04 15:57 UTC, merged