Betting game
figment-networks/datahub-learn pull request #300
Opened 2021-10-31 11:15 UTC by Devilla

Thanks for submitting this tutorial for Figment Learn!

Before you hit "Create Pull Request", make sure you have read the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8) and reviewed the [Sample Tutorial Structure](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d). 

Please confirm the following before submitting your tutorial for review - 

- [ ] My tutorial follows the [Tutorial Contribution Guidelines](https://www.notion.so/figmentnetworks/Figment-Learn-Contributor-Guidelines-b08691366e144d33a5636d9276a44ec8).

In particular:

- [ ] The title of the Pull Request matches the title of my tutorial.
- [ ] I've followed the [tutorial template](https://www.notion.so/figmentnetworks/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d) structure.
- [ ] I've [proofread the tutorial](https://grammarly.com) for spelling and grammar mistakes.
- [ ] I've run a linter & prettifier to format my code blocks.
- [ ] I've thoroughly explained the code, with inline code comments and text explanations.
- [ ] I've run the tutorial to test it and the code works.

**NOTE**: We cannot review your Pull Request if it does not meet the standard outlined above.

2021-11-05 00:28 UTC, pyr0gan requested changes
Hi @Devilla, this is an interesting tutorial 😄 

I think you could add a little more at the end, you need a Conclusion section at the very least.

Most fixes involve the syntax highlighting on code blocks, and there are some grammar fixes to make. Please read my comments and make the necessary changes. Remember to mark the conversations as resolved when you have made the changes so my next review can proceed quickly 🙏

2021-11-05 00:28 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-Betting-Game-on-Matic.md
> +
You need to include a Conclusion section. Please refer to the [sample tutorial](https://www.notion.so/Sample-Tutorial-Structure-667ac2aad36f4f94a3ebaca053180b2d).

2021-11-06 17:02 UTC, Devilla commented
@pyr0gan please check.

2021-11-08 20:55 UTC, pyr0gan commented
> @pyr0gan please check.

I'll review this today, Monday November 8th 👍

2021-11-08 23:25 UTC, pyr0gan requested changes
Hi @Devilla @deveshjain0 ,

Have a look at my comments. Just a few small fixes at this point 🙏

2021-11-08 23:25 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-Betting-Game-on-Matic.md
> +- Basic familiarity with [Setting up MetaMask for Matic](https://medium.com/stakingbits/setting-up-metamask-for-polygon-matic-network-838058f6d844#:~:text=Setup%20MetaMask%20to%20connect%20to,Network
There are tutorials on Figment Learn that cover using Metamask with Polygon (quite a few at this point!) - it would be preferable to link to them over a Medium article 😄

2021-11-08 23:25 UTC, pyr0gan commented on network-documentation/matic/tutorials/Chainlink-Betting-Game-on-Matic.md
> +
It also looks like you'e missing a References section that mentions github.com/dappuniversity and the Chainlink documentation.

2021-11-10 12:23 UTC, Devilla commented
@pyr0gan please check and update, thanks. 🚀

2021-11-10 23:39 UTC, pyr0gan approved these changes

2021-11-12 15:47 UTC, pyr0gan commented
On further review, this document _cannot be accepted by Learn_ as it is directly copying the dappuniversity smart contract without proper attribution. I was under the impression that you had written this smart contract yourselves. There is not enough original material here to warrant publication on Learn.

@Devilla @deveshjain0 - This PR will now be closed.

2021-11-12 15:47 UTC, closed without merging