introduction to dappkit
figment-networks/datahub-learn pull request #57
Opened 2021-04-15 05:18 UTC by nikbhintade

Hi,

This is a tutorial on how to use Dapp kit with expo and interact with celo mobile wallet.

In this tutorial, I want through a blank folder to create a mobile dapp that can interact with celo mobile wallet and performing basic actions like signing transactions, getting account details, etc.

2021-04-19 16:42 UTC, yash-sharma1 reviewed
It looks good to me, well explained 
@guillaumegaluz @pyr0gan can you please have a look at this :)

2021-04-20 23:17 UTC, pyr0gan requested changes
Please resolve all comments prior to final review.

2021-04-20 23:17 UTC, pyr0gan commented on network-documentation/celo/tutorial/introduction-to-dappkit.md
> +And just like that we have created our first ever mobile app.
Congratulations for completing this tutorial, Introduction to DappKit! We have now created a functioning mobile dapp on the Celo testnet. This same methodology can be applied to the Celo mainnet as well, to produce functioning distributed applications.

2021-04-20 23:17 UTC, pyr0gan commented on network-documentation/celo/tutorial/introduction-to-dappkit.md
> +In this tutorial we have covered some part of dapp kit, how it connects with celo mobile wallet, how we can connect our dapp with the mobile wallet and how to do some basic things like getting accoun
In this tutorial we have covered some parts of DappKit, how it connects with the Celo mobile wallet, how we can connect our dapp with the mobile wallet and how to do some basic things like getting account addresses, balance of accounts, phone number connected to Celo mobile wallet, and signing transactions.

Thank you for following along with this tutorial, now take this knowledge and build amazing things on Celo!

2021-04-21 06:30 UTC, nikbhintade commented on network-documentation/celo/tutorial/introduction-to-dappkit.md
> +xQc@RecycleBin MINGW64 ~/Documents/blockchain/celoDappCounter
This is not intentional. I just can't change it.

2021-04-21 06:47 UTC, nikbhintade commented on network-documentation/celo/tutorial/introduction-to-dappkit.md
> +`requestTxSig` methods takes three arguments:
Thanks for the clarification.

2021-04-21 07:02 UTC, nikbhintade commented on network-documentation/celo/tutorial/introduction-to-dappkit.md
> +<p align="center">
thanks for that! I changed that for one image but other images take too much space on the page so I didn't change it.

2021-04-21 07:28 UTC, nikbhintade reviewed
.

2021-04-21 07:28 UTC, nikbhintade reviewed
made all changes as suggested

2021-04-21 07:57 UTC, pyr0gan approved these changes

2021-04-21 07:59 UTC, merged

2021-04-21 08:40 UTC, yash-sharma1 commented
@nikbhintade my apologies I missed something in this, can you please add your bio in the "About the Author" section at the starting of the tutorial or you can send it to me on Discord/Mail