Added a short script on how to transfer AVAX tokens from the C chain to an ETH wallet
figment-networks/datahub-learn pull request #61
Opened 2021-04-15 19:33 UTC by blackwidoq

2021-04-16 20:52 UTC, pyr0gan reviewed
@yash-sharma1 need 👀 on this after the weekend, hopefully @blackwidoq will add more material and we can look at merging next week?

2021-04-16 20:52 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/AVAX_C_chain_to_ETH_address_transfer_tutorial.md
> +Since AVAX EVM directly borrows from web3.eth, eb3.eth.getBalance fetches the AVAX balance.
I don't think this reads the way you want it to. I would guess that your intent is to tell the reader that the web3 module is capable of acting upon the AVAX implementation of the EVM.

What is web3.eth? (you don't need to explain it to me, I know what it is and in this context, but please explain this to the reader).

'eb3.eth.getBalance' is a typo, I'm assuming.

2021-04-16 20:52 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/AVAX_C_chain_to_ETH_address_transfer_tutorial.md
> +          console.log(web3.utils.fromWei(result, "ether") + " ETH")
An explanation of the fromWei() method and why it is used here would be useful.

2021-04-16 20:52 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/AVAX_C_chain_to_ETH_address_transfer_tutorial.md
> +Type in your destination ETH address beween the quotation marks below
This actually made me chuckle. Who types in a hexadecimal address?! More likely it will be copied and pasted, so consider changing the wording a little bit.

2021-04-16 20:52 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/AVAX_C_chain_to_ETH_address_transfer_tutorial.md
> +Below, we need to input how many tokens are to be transferred out of your AVAX wallet off the C-chain. Currently the amount is set to 0.15 AVAX tokens  (0.15 tokens in the line below)
Is there a reason why this is set to 0.15 AVAX? If it is merely an example number, consider specifying that to the reader.

The end of this tutorial is rather abrupt. Please include a conclusion section to discuss what learning objective has been satisfied by following along. 

Overall, a good start but this article requires a little more work.

2021-04-18 00:16 UTC, blackwidoq commented
@pyr0gan  Thank you for the suggestions.  I tried making changes according to your suggestions. I'm a beginner so if I have misunderstood anything you said or if my wording is inaccurate/misleading, let me know.  Thanks for your patience!

2021-04-18 07:59 UTC, yash-sharma1 commented
> @yash-sharma1 need 👀 on this after the weekend, hopefully @blackwidoq will add more material and we can look at merging next week?

2021-04-18 08:01 UTC, yash-sharma1 commented
> > @yash-sharma1 need 👀 on this after the weekend, hopefully @blackwidoq will add more material and we can look at merging next week?

Yes, sure!! once Blockwidowq will update the new changes then we can review it again and will merge it in coming week

2021-04-18 13:48 UTC, blackwidoq commented
@yash-sharma1 @pyr0gan Thank you.  I've made the changes.  let me know if you want more added or something else addressed.  Thank you guys.

2021-04-19 08:24 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/AVAX_C_chain_to_ETH_address_transfer_tutorial.md
> +Since AVAX EVM directly borrows from web3.eth, eb3.eth.getBalance fetches the AVAX balance.
These changes are made by the author in the new commit.

2021-04-19 08:48 UTC, yash-sharma1 reviewed
@pyr0gan all the required changes are made and looks good to me, let's have one more look over it then we can merge.

2021-04-19 20:44 UTC, blackwidoq commented
> @pyr0gan all the required changes are made and looks good to me, let's have one more look over it then we can merge.

Thank you.  Are you waiting for one more moderator to review the pull request?

2021-04-20 15:24 UTC, pyr0gan requested changes
It is unnecessary to have (if accepted change to ..) in the document. Please fix these, and I will then be able to merge this tutorial.

2021-04-20 20:23 UTC, blackwidoq commented
@pyr0gan   Thank you.  I've made the change you requested.  Thanks

2021-04-21 07:54 UTC, pyr0gan approved these changes

2021-04-21 07:54 UTC, merged

2021-04-21 08:43 UTC, yash-sharma1 commented
@blackwidoq your tutorial is merged but can you please add your bio in the "About the Author" section at the starting of the tutorial or you can send it to me on Discord/Mail