add tutorial nft marketplace in assemblyscript
figment-networks/datahub-learn pull request #7
Opened 2021-01-13 03:11 UTC by hdriqi

NFT Marketplace based on NEP-4 AssemblyScript tutorial from NEAR.

2021-01-15 13:24 UTC, pacmessica reviewed
Good job so far!

Could you also add a PR here with the completed version of all the changed files from this tutorial? https://github.com/figment-networks/tutorials/tree/main/near

I'm about halfway through this PR, I'll continue the review and testing the code when I have a code example to refer to 😛 .

2021-01-15 13:24 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +
also need to update the import, so add something like this: 

```
First, let's import `PersistentUnorderedMap` from the `near-sdk-as`. Update the following line at the top of `main.ts`:

```typescript
import { PersistentMap, PersistentUnorderedMap, storage, context } from 'near-sdk-as'
```

2021-01-15 13:24 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +
I'm getting errors with u128. I'm not sure where to import it from, so also add instructions for that

2021-01-18 02:30 UTC, hdriqi commented
> Good job so far!
> 
> Could you also add a PR here with the completed version of all the changed files from this tutorial? https://github.com/figment-networks/tutorials/tree/main/near
> 
> I'm about halfway through this PR, I'll continue the review and testing the code when I have a code example to refer to 😛 .

Just created the PR for the full code here https://github.com/figment-networks/tutorials/pull/7

2021-01-18 02:33 UTC, hdriqi commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +We will be adding more features one by one to the basic NFT contract from NEP-4 and create unit test for every function that we create.
Will write 1-2 sentences about NEP-4, should be enough

2021-01-18 03:38 UTC, hdriqi commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +
Just update some parts in the tutorial like u128 and PersistentUnorderedMap on the [latest commit](https://github.com/figment-networks/datahub-learn/pull/7/commits/d8179bc3bd3fad401f16ab30e42ac2138878cb4f)

2021-01-18 14:44 UTC, pacmessica reviewed
Great tutorial!

mostly more grammar suggestions, and a few imports. I think on our end we need to figure out if figment wants to host their own fork (although I believe our preference is to use the official [near example](https://github.com/near-examples/NFT) rather than maintain a fork). If we use the original repo then we'd need to extend the tutorial to add the asconfig.json and as-pect.config.js files and also edit package.json so that the build doesn't fail. perhaps @sosedoff has some input about this (forks)?

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +If you saw at least 2 files with `[account_id].json` similar to the one that you've created on the browser, then we're good to go. Without further ado, let's try try some function that we already cre
```suggestion
If you see at least 2 files with `[account_id].json` similar to the one that you created in the browser, then we're good to go. Without further ado, let's try some functions that we created previously with these new accounts.
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +near call --accountId [ARTIST_ID] dev-1610108148519-8579413 mint_to '{"owner_id": "[ARTIST_ID]"}'
```suggestion
near call --accountId [ARTIST_ID] [DEV_ID] mint_to '{"owner_id": "[ARTIST_ID]"}'
```

Use `[DEV_ID]` for consistency and make it obvious that this needs to be changed too

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +Make sure to change `[ARTIST-ID]` to one of the accounts that you've created before. That command will return the tokenId of the newly minted NFT:
```suggestion
Make sure to change `[ARTIST-ID]` to one of the accounts that you created earlier in the browser, and `[DEV-ID]` with the account id we created when deploying our smart contract. Running the above command will return the tokenId of the newly minted NFT:
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +It should returns the price that we've just set previously using `add_to_market` which is 1 N.
```suggestion
It should return the price that we've just set previously using `add_to_market` which is 1 N.
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +It should returns the price that we've just set previously using `add_to_market` which is 1 N.
It didn't return a price. I got `true`:

```
Scheduling a call: dev-1610977564975-4620260.add_to_market({"token_id": "1", "price": "1000000000000000000000000"})
Transaction Id 72tJckrgu49U93Ra1RvzZArwugW86nzZroCbbb6MshpC
To see the transaction in the transaction explorer, please open this url in your browser
https://explorer.testnet.near.org/transactions/72tJckrgu49U93Ra1RvzZArwugW86nzZroCbbb6MshpC
true
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +We can add our newly minted NFT to the marketplace to see if there are collectors that are interested to add it into their collections. We can use the function `add_to_market` to do that which takes
```suggestion
We can add our newly minted NFT to the marketplace to see if there are collectors that are interested in adding it into their collections. We can use the function `add_to_market` to do this which takes `token_id` and `price` as parameters. The price must be in yoctoNEAR (10^24), in this case we sell our NFT for 1 N -> 1000000000000000000000000 yoctoNEAR. Make sure to change the parameters `[TOKEN_ID]` into any NFT ID that you own/mint.
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +This time, we'll be using another account beside the artist and let's call it the collector `COLLECTOR_ID`. Collector can buy the listed NFT by calling the function `buy` that require `[TOKEN_ID]` as
```suggestion
This time, we'll be using the other account you created, let's call this account the collector `COLLECTOR_ID`. The collector can buy the listed NFT by calling the function `buy` which requires `[TOKEN_ID]` as its parameter. This time we add `--amount` to buy the NFT it is usually called attachedDeposit and we attach 1 N as it is the listed price needed to buy the NFT.
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +This time, we'll be using another account beside the artist and let's call it the collector `COLLECTOR_ID`. Collector can buy the listed NFT by calling the function `buy` that require `[TOKEN_ID]` as
This is unclear to me "it is usually called attachedDeposit".  It sounds like instead of `--amount` it's usually `--attachedDeposit`? Can you make this sentence clearer?

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +Before we buy the NFT, let's just take a note at the current balance of the artist and collector using NEAR CLI command below:
```suggestion
Before we buy the NFT, let's just take note of the current balance of the artist and collector using the NEAR CLI command below:
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +You can replace the `[ACCOUNT_ID]` with `[ARTIST_ID]` or `[COLLECTOR_ID]` and it will returns something like this:
```suggestion
You can replace the `[ACCOUNT_ID]` with `[ARTIST_ID]` or `[COLLECTOR_ID]` and it will return something like this:
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +The `formattedAmount` is current balance of the account, so just keep that in mind and we'll compare with after buying process. We call the `buy` function with `[COLLECTOR_ID]`.
```suggestion
The `formattedAmount` is the current balance of the account, so just take note of this value so that you can compare it to the `formattedAmount` after the purchase is complete. We call the `buy` function with `[COLLECTOR_ID]`:
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +near call --accountId [COLLECTOR_ID] dev-1610108148519-8579413 buy '{"token_id": "[TOKEN_ID]"}' --amount 1
```suggestion
near call --accountId [COLLECTOR_ID] [DEV_ID] buy '{"token_id": "[TOKEN_ID]"}' --amount 1
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +near view --accountId [COLLECTOR_ID] dev-1610108148519-8579413 get_token_owner '{"token_id": "[TOKEN_ID]"}'
```suggestion
near view --accountId [COLLECTOR_ID] [DEV_ID] get_token_owner '{"token_id": "[TOKEN_ID]"}'
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +We can call `near state [ACCOUNT_ID]` to check if the payment is already received by the seller/artist and deducted from buyer balance.
```suggestion
We can call `near state [ACCOUNT_ID]` to check if the payment is already received by the seller/artist and deducted from the buyer balance.
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +Alright, so we have deployed the modified NFT smart contract with Marketplace functionality on the testnet. You can do more experiment by calling other function like `delete_from_market` and so on. Y
```suggestion
Alright, so we have deployed the modified NFT smart contract with Marketplace functionality on the testnet. You can experiment more by calling other functions such as `delete_from_market` and so on. You can also connect this contract with the javascript sdk `near-api-js` and create the frontend side for your marketplace.
```

2021-01-18 14:44 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +Please remember that this code is not intended for production, there are still few other things to consider if you wanted to deploy it on mainnet like disable the transfer method if the token is list
```suggestion
Please remember that this code is not intended for production: there are still a few other things to consider if you wanted to deploy this to mainnet such as disabling the transfer method if the token is listed on the market and so on.
```

2021-01-18 14:53 UTC, pacmessica reviewed
found one more thing

2021-01-18 14:53 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +	assert(owner == caller, ERROR_TOKEN_NOT_OWNED_BY_CALLER)
this is different from the final code in [tutorials](https://github.com/figment-networks/tutorials/pull/7/files)

```
	const owner = tokenToOwner.getSome(token_id)
	const escrow = escrowAccess.get(owner)
	assert(
		[owner, escrow].includes(caller),
		ERROR_CALLER_ID_DOES_NOT_MATCH_EXPECTATION
	)
```

can you change either this or the final code so that they're consistent?

2021-01-19 02:31 UTC, hdriqi commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +		expect(nonSpec.get_market(0, 5)).toHaveLength(1)
my bad! pasted the wrong test case

2021-01-19 02:32 UTC, hdriqi commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +	assert(owner == caller, ERROR_TOKEN_NOT_OWNED_BY_CALLER)
changed the code in this tutorial

2021-01-19 02:33 UTC, hdriqi commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +If you have made any errors, the compiler should give you a detailed explanation. Since you've copied and pasted everything from this tutorial, it's probably just typos.
just pushed the commit on the master branch

2021-01-19 02:39 UTC, hdriqi commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +It should returns the price that we've just set previously using `add_to_market` which is 1 N.
This one refers to the view function `get_market_price`. Here's the latest commit to make sure those call & view methods are having their own return detail https://github.com/figment-networks/datahub-learn/pull/7/commits/5d4e52d0cddb4ed8571321c0edfab61a71d83473

2021-01-19 02:39 UTC, hdriqi commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +This time, we'll be using another account beside the artist and let's call it the collector `COLLECTOR_ID`. Collector can buy the listed NFT by calling the function `buy` that require `[TOKEN_ID]` as
I think omitting the `attachedDeposit` should be fine

2021-01-20 05:19 UTC, sosedoff requested changes
Thanks for the contribution!
I gave this a pass (took a while). We'll definitely need changes !

See the comments below.

2021-01-20 05:19 UTC, sosedoff commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +near call --accountId [ARTIST_ID] dev-1610108148519-8579413 add_to_market '{"token_id": "[TOKEN_ID]", "price": "1000000000000000000000000"}'
```suggestion
near call --accountId [ARTIST_ID] [DEV_ID] add_to_market '{"token_id": "[TOKEN_ID]", "price": "1000000000000000000000000"}'
```

2021-01-20 05:19 UTC, sosedoff commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +near view --accountId [ARTIST-ID] dev-1610108148519-8579413 get_market_price '{"token_id": "[TOKEN_ID]"}'
```suggestion
near view --accountId [ARTIST-ID] [DEV_ID] get_market_price '{"token_id": "[TOKEN_ID]"}'
```

2021-01-20 05:19 UTC, sosedoff commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +```
```suggestion
```json
```

2021-01-20 05:19 UTC, sosedoff commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +## Conclusion
```suggestion
## Conclusion
```

2021-01-20 05:19 UTC, sosedoff commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +The complete code can be found on [Github](https://github.com/figment-networks/tutorials).
We should fix this link

2021-01-25 13:20 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +Again, we need to create unit test our function to make sure it works as expected.
```suggestion
Again, we need to create a unit test for our function to make sure it works as expected.
```

2021-01-25 13:22 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +We can now test our `buy` function using the unit test below by updating at the end of our `main.unit.spec.ts`:
```suggestion
We can now test our `buy` function using the unit test below by updating the end of our `main.unit.spec.ts`:
```

2021-01-25 13:23 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +You can also see the complete code for this tutorial on the following repo: [feat/marketplace](https://github.com/figment-networks/tutorials).
```suggestion
You can also see the complete code for this tutorial in the following repo: [feat/marketplace](https://github.com/figment-networks/tutorials).
```

2021-01-25 15:39 UTC, pacmessica reviewed
looks like there's still some unresolved comments from sosedoff, otherwise looks pretty good.

Flow has improved a lot, great work! Thanks for implementing all the changes. Have a few more to add 😬

2021-01-25 15:39 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +This is the main function for the marketplace where users can buy the listed NFTs on the marketplace. Buyers can attach some NEAR as payment and the contract will automatically send the payment to th
```suggestion
This is the main function for the marketplace where users can buy the listed NFTs on the marketplace. Buyers can attach some NEAR as payment and the contract will automatically send the payment to the seller and update the token ownership to the buyer. We'll also create a simple transaction fee or commission for the smart contract developer, in this example we'll take a 5% cut for every sale made via the smart contract.
```

2021-01-25 15:39 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +We will create function `get_market` that will return a list of `TokenDetail` that contains the `tokenId` and its `price`. For the implementation, we use `.entries` from `PersistentUnorderedMap` that
```suggestion
We will create the  function `get_market` that will return a list of `TokenDetail` that contains the `tokenId` and its `price`. For the implementation, we use `.entries` from `PersistentUnorderedMap` that takes the start and end indexes from our list (we can use this for pagination later when building the frontend application).
```

2021-01-25 15:39 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +The complete code can be found on [Github](https://github.com/figment-networks/tutorials).
```suggestion
The complete code can be found on [Github](https://github.com/figment-networks/tutorials/near/7_NFT_marketplace/).
```

2021-01-25 15:56 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +export function buy(token_id: TokenId): TokenId {
so currently you copy and paste the same function `buy` 3x. I think we can improve this flow. It would be a lot nicer to have code comments and to guide the user to add small sections into the function rather than the entire function each time.

Look at how it's done [here](https://learn.figment.io/network-documentation/secret/tutorials/3.-querying-the-secret-blockchain#query-blockchain-details). They use code comments, then tell the user to add a snippet under the comment.

2021-01-28 02:07 UTC, hdriqi commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +
Please check my latest commit, I put the test at the end of each section

2021-01-28 02:44 UTC, hdriqi commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +Now here's the main function that allows users to mint the NFT. The NFT itself is just a simple ID with owner. The metadata such as an image, video or audio is usually stored off-chain on [IPFS], [Si
https://github.com/figment-networks/datahub-learn/pull/7/commits/2b3913415e68293b281327dba6751f5da1aaf014#diff-af6c31285caafa258adac96da1df8183131b9c890840308176a0cc60b0a0501cR186

2021-01-28 02:48 UTC, hdriqi commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +export function buy(token_id: TokenId): TokenId {
Please check my latest commit https://github.com/figment-networks/datahub-learn/pull/7/commits/2b3913415e68293b281327dba6751f5da1aaf014#diff-af6c31285caafa258adac96da1df8183131b9c890840308176a0cc60b0a0501cR469

2021-01-28 02:59 UTC, hdriqi commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +Unlike Ethereum, you need to deploy a contract into a certain account. Using `dev-deploy` will create a test account and deploy the contract into that account at once. The test account looks somethin
changed it a little bit here https://github.com/figment-networks/datahub-learn/pull/7/commits/2b3913415e68293b281327dba6751f5da1aaf014#diff-af6c31285caafa258adac96da1df8183131b9c890840308176a0cc60b0a0501cR680

2021-01-28 12:35 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +export function buy(token_id: TokenId): TokenId {
looks great!

2021-01-28 12:38 UTC, pacmessica approved these changes
lgtm

we need to create a fork on our end, and update the line `git clone https://github.com/hdriqi/NFT`

2021-01-28 16:37 UTC, Y-Folla commented
@pacmessica or @sosedoff since we need to create the form ourselves, could you make the SUMMARY.md entry when it's done and let me know when it's ready to merge? I'd like to do it by tomorrow

2021-02-01 12:25 UTC, pacmessica commented
Added the fork here: https://github.com/figment-networks/NFT

I tried rerunning the code using the fork, and I ran into issues with u128. 

```
Module '"near-sdk-as"' has no exported member 'u128'.
```

If I import from as-bignum directly it works, `import { u128 } from 'as-bignum'`, but I see that `near-sdk-as` exports u128 from bignum  [here](https://github.com/near/near-sdk-as/blob/v2.2.3/sdk-core/assembly/index.ts)

so I'm confused if this issue is in near-sdk-as, or it's on my end (I use vs-code, maybe there's some kind of module caching? I tried going back to v2.2.2 and also had issues with u128). Can you check it out? I also saw you made PRs to `near-sdk-as`  regarding bigint, so maybe you're familiar with this issue. Thanks!

@hdriqi

2021-02-02 03:07 UTC, hdriqi commented
> Added the fork here: https://github.com/figment-networks/NFT
> 
> I tried rerunning the code using the fork, and I ran into issues with u128.
> 
> ```
> Module '"near-sdk-as"' has no exported member 'u128'.
> ```
> 
> If I import from as-bignum directly it works, `import { u128 } from 'as-bignum'`, but I see that `near-sdk-as` exports u128 from bignum [here](https://github.com/near/near-sdk-as/blob/v2.2.3/sdk-core/assembly/index.ts)
> 
> so I'm confused if this issue is in near-sdk-as, or it's on my end (I use vs-code, maybe there's some kind of module caching? I tried going back to v2.2.2 and also had issues with u128). Can you check it out? I also saw you made PRs to `near-sdk-as` regarding bigint, so maybe you're familiar with this issue. Thanks!
> 
> @hdriqi

It's from the SDK, I think we should just wait for the new release https://github.com/near/near-sdk-as/pull/381

2021-02-02 10:51 UTC, pacmessica commented
> @pacmessica or @sosedoff since we need to create the form ourselves, could you make the SUMMARY.md entry when it's done and let me know when it's ready to merge? I'd like to do it by tomorrow

Hey! sorry I missed this last week @Y-Folla. I can add it

So I created the fork yesterday, and there's a problem with the latest version of the sdk package which is breaking our tutorial. So looks like we should wait for that to get fixed :/

2021-03-03 17:52 UTC, pacmessica requested changes
u128 issue is fixed with latest version of NFT repo, so good to merge after changing line to use our fork

2021-03-03 17:52 UTC, pacmessica commented on network-documentation/near/tutorials/nft-marketplace-in-assemblyscript.md
> +git clone https://github.com/hdriqi/NFT
```suggestion
git clone https://github.com/figment-networks/NFT
```

2021-03-03 18:53 UTC, merged