c-chain to eth address transfer
figment-networks/datahub-learn pull request #70
Opened 2021-04-21 14:41 UTC by blackwidoq

2021-04-21 15:01 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/AVAX_C_chain_to_ETH_address_transfer_tutorial.md
> +This tutorial was created by [Seongwoo Oh](https://github.com/blackwidoq). He is a student and an Avalanche novice.
Movin' on up, hey? 😁

2021-04-21 15:01 UTC, pyr0gan approved these changes

2021-04-21 15:05 UTC, blackwidoq commented on network-documentation/avalanche/tutorials/AVAX_C_chain_to_ETH_address_transfer_tutorial.md
> +This tutorial was created by [Seongwoo Oh](https://github.com/blackwidoq). He is a student and an Avalanche novice.
thought i need to be more honest about where i am haha.  I am going to have to ask my friend to show me how to resolve complex conflicts. I will have this resolved later today. thank you

2021-04-21 15:08 UTC, pyr0gan requested changes
Please resolve all conflicts. It might be easier to continue using the existing branch you submitted the tutorial on. It appears from the changes that you had a few conflicts while trying to edit. How are you editing your markdown, if I may ask?

2021-04-21 17:23 UTC, blackwidoq commented
@pyr0gan   I dont actually really know how to view what's causing the conflict. I explored using `git mergetool` but havent been successful.  I will ask my friend who is very good with this stuff later today and get it resolved.  Thank you!

2021-04-22 00:33 UTC, pyr0gan approved these changes

2021-04-22 05:38 UTC, merged