Create celo-node-video-tutorial.md
figment-networks/datahub-learn pull request #76
Opened 2021-04-23 16:44 UTC by Aidandedecker

2021-04-23 17:50 UTC, pyr0gan requested changes
Thanks for putting all this together, we appreciate your work! 😄 

I am just curious, did you intend the documentation here to function as a transcript of the video? I have not watched the video yet, but I can say that the command heavy, unexplained nature of this submission is likely to confuse beginners.

Consider adding a Prerequisites section and discussing the points of knowledge or experience you would deem necessary for a reader to comprehend what this tutorial is accomplishing.

Also consider adding a Conclusion section where you discuss what was covered in the tutorial. Abrupt endings make it more difficult for readers to understand and then relay the concepts that have been covered by the material you are providing. 

From a readability standpoint, it will make sense to any competent Linux user, but is that your intended audience? There are a lot of commands being issued, and because none of this is Markdown formatted it can be much more difficult to follow. 

Consider using Markdown syntax to format the document so that it is clear when you are referring to CLI with backticks `\`` like `./start_celo.sh` vs. when you are referring to a part of speech, like "Start geth console".

For reference, this is what the document renders as, without any markdown :
![aid](https://user-images.githubusercontent.com/2707197/115910004-86f8d180-a429-11eb-8afa-561490bf566a.png)

I think the documentation for this PR just needs a little bit of work. I'm happy to help you get this formatted nicely if you are unsure about Markdown syntax. [There is a nice guide here](https://guides.github.com/features/mastering-markdown/) to get you started.

2021-04-23 18:30 UTC, Aidandedecker commented
thanks for the feedback! that's a series of commands I used from my doc. I'll edit it and add make it coherent. I just pasted that in quick, I wasn't sure I published this correctly.

2021-04-28 07:56 UTC, yash-sharma1 commented
@pyr0gan can you review it, if all good as per the requested changes then we can go ahead

2021-04-28 15:26 UTC, Aidandedecker commented
sorry @pyr0gan, @yash-sharma1 for doing this step so late.  This is my first hackathon.

2021-04-29 16:43 UTC, pyr0gan commented
> Apologies @pyr0gan, @yash-sharma1 for doing this step so late. I learned a lot from doing this hackathon.



> Apologies @pyr0gan, @yash-sharma1 for doing this step so late. I learned a lot from doing this hackathon.

Learning is great! To help people learn from this material, we just need to include a little more explanation. Right now it isn't reader-friendly. As I mentioned, an introduction in text and a conclusion section would go a long way. Even if the video exists, it would be nice to have a little accompanying documentation. A list of terminal commands does not really warrant its own page in the documentation when we could easily just link people to the video.

Please consider adding the sections I mentioned in my original comment 😄

2021-04-29 17:10 UTC, Aidandedecker commented
Thanks @pyr0gan. Your right I need more explanation and a conclusion in this document. Ill get working on that asap.

2021-04-29 21:37 UTC, Aidandedecker commented
@pyr0gan I made some major improvements to the PR! If you could please let me know what you think.

2021-05-03 16:58 UTC, Aidandedecker commented
@pyr0gan  please take a look at my latest commit. I think its ready.

2021-05-04 23:13 UTC, Aidandedecker commented
hey @yash-sharma1 is my submission approved, and could I be eligible for the 500CUSD

2021-05-05 05:31 UTC, yash-sharma1 commented
Hey @Aidandedecker, I again reviewed it and still, It's not reader/learner-friendly. Having a video is great but providing step-by-step instructions in the text format is the best way to deliver the knowledge content, which is missing here. For reference, you can check other tutorials available on Learn. For being eligible for the 500 cUSD - if your tutorial is accepted and it's as per the expectation then surely you'll be, for now, it needs a lot more improvement.

2021-05-05 14:48 UTC, Aidandedecker commented
Thanks, I'll take a look at the others for reference . Thanks for all the help, I'm ganna make this a great tutorial.

2021-05-08 02:36 UTC, Aidandedecker commented
@pyr0gan, @yash-sharma1 is this commit a step in the right direction?

2021-05-10 06:20 UTC, yash-sharma1 requested changes
@Aidandedecker a quick feedback on this - 

- Please follow the tutorial guide and the structure which looks like this 
> Title of the Tutorial
> Description
> Introduction
> Pre-requisites
> Embed the Video which you created for this
> Step by Step clear explanation
> Code should be well explained and commented
> Display the output of each code block after executing that (where it's needed)
> Display the final output
> Conclusion
> About the Author (Your Bio in 3-4 lines along with your social media handle)
- Use markdowns carefully and make it cleaner, easily readable and self-explanatory.

2021-05-13 00:54 UTC, Aidandedecker commented
@yash-sharma1 thanks for the structure, I have made improvements, and added the sections.

2021-05-13 10:13 UTC, yash-sharma1 commented
> @yash-sharma1 thanks for the structure, I have made improvements, and added the sections.

Thanks, @Aidandedecker for the update. Can you please check this guide and sample tutorial structure **[HERE](https://learn.figment.io/other/tutorial-guidelines)** It'll help you out in understanding the structure of the tutorial, which we're expecting. Let me know if you have any query & feel free to reach out to us on discord.

2021-05-15 00:13 UTC, Aidandedecker commented
thanks, @yash-sharma1 that tutorial structure was really helpful. I changed a lot, hopefully for the better. I did add a few pictures, I'm not sure if their too much though.

2021-05-17 11:55 UTC, yash-sharma1 commented
> thanks, @yash-sharma1 that tutorial structure was really helpful. I changed a lot, hopefully for the better. I did add quite a few pictures, I'm not sure if their too much though.

@Aidandedecker Thanks for the update. There are still a couple of things are missing from the tutorial as compare to the tutorial structure which I shared, please refer to the Sample Tutorial Structure available along with the tutorial guidelines. 

- Markdowns are not used carefully throughout the tutorial. 
- No consistency in headings, sub-headings and text in the tutorial.
- Pre-requisite and Requirement section is missing.
- About the Author section still need changes. 
- There's no conclusion. 
- Code comments and Code explanation is still missing from the tutorial. 
- Please, add common errors and steps to troubleshoot the errors.

If you're facing any problem this feel free to reach out to us Discord we'll discuss and then you can make changes.

2021-05-24 11:36 UTC, yash-sharma1 commented
@Aidandedecker I just review your latest commits, I found still there are issues with markdowns can you please review this and follow the structure of this sample tutorial it'll help you - https://learn.figment.io/other/tutorial-guidelines/sample-tutorial-structure
Please explain the code as much as you can

2021-05-26 18:48 UTC, pyr0gan reviewed
Please look over the feedback and keep refining the material. We are getting closer to a finished product, and I appreciate your time spent to make this a solid resource for learners.

2021-05-26 18:48 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +    # these sudo comands are only posible once in the sudo group
If we're going to explain `sudo` let's explain `sudo`. If we're not, there's not a lot of use in editorializing. Also in the heading, the spelling is 'dependencies' 😄

2021-05-26 18:48 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +    username@name:~$sudo apt install vim
Consider using `nano` perhaps? `vim` can be a lot to chew, at least in my experience `nano` is a lot easier for anyone familiar with Ctrl-key shortcuts from a desktop - for example saving a document is `Ctrl+O` and exiting is `Ctrl+X`. Just food for thought.

2021-05-26 18:48 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +    # this installs and uses the latest Node Version Manager
this installs Node.js version 10 if it isn't already, then sets it as the active Node.js version. The latest version of `nvm` is 0.38.0 : https://github.com/nvm-sh/nvm/releases/tag/v0.38.0

2021-05-26 18:48 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +    # this tells the terminal to interprate the following script in bash
#! is an interpreter directive, commonly called a "shebang". What follows is the absolute path to the interpreter we would like to use, in this case the bash command-line interpreter.

2021-05-26 18:48 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +    #  try inserting this curl scrip multiple times if it dosent work the first time
Possible causes of failure would be an interruption in network connection, but the thing which comes to mind is .. Why on earth are we requiring readers to fetch a .env file from a gist? Why not just include the contents of the .env in this tutorial and explain the contents?

2021-05-26 18:48 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +    # notice the name(celo full-node) this is the name of the node witch is important to remember
Where is the name celo full-node? Also, the contents of start_celo.sh and celo.env would be the same after this, as the link https://gist.github.com/alchemydc/e28945f5059acd70969b39a50fd0f80a is also to start_celo.sh

2021-05-26 18:48 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +  to learn more about these .env files check out this guide:https://learn.figment.io/network-documentation/extra-guides/dotenv-and-.env
Nice nod to the Figment extra guides! I would specify that "to learn more about .env files overall, check out this guide", and definitely consider just explicitly defining the needed environment variables instead of using curl to pull them from a gist. Clever, but perhaps a little too clever for two lines 😄

2021-05-26 18:48 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +    # mkdir makes a new directory
These comments around the terminal commands can be a little distracting, more cohesive sentences would be preferable.

2021-05-26 18:48 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +    username@name:~/ celo-data-dir$ celocli account:unlock $PUBLIC ADDRESS
Seems to be a missing underscore between PUBLIC and ADDRESS

2021-05-26 18:48 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> + ##  *Improving the resolution of the VM (Highly recommended)*
This would be a good thing to go over at the beginning of the tutorial rather than at the end, 
I think.

2021-06-05 04:22 UTC, Aidandedecker commented
@pyr0gan let me know if you think its ready!

2021-06-16 22:38 UTC, pyr0gan requested changes
@Aidandedecker After these changes are applied I will consider it a final draft and give it one last pass tomorrow before merging 👍🏻

2021-06-16 22:38 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` cd /media/cdrom ```
It seems like you're repeating the step from a minute ago? Is this just an editing mishap? You may want to review the document for how it flows with your updated videos.

2021-06-16 22:38 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` sudo sh VBoxLinuxAdditions.run ```
Above, you used `bash` for this command and here you're using `sh`? This is a little confusing! Can you please clarify if this is intentional?

2021-06-16 22:38 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` sudo usermod -aG docker $YOURNAME ```
See my earlier confusion over $YOURUSERNAME. Please keep it consistent 😄

2021-06-16 22:38 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +   #### The interpreter directive, "#!" is called a "shebang". The path, "/bin/bash" sets the terminal to interpret in bash.
Not watching in sync with the video, so I'm wondering why this is mentioned here. The line above this has a lone hashmark, but no header text. After the bullet point "Check for (docker)" I would expect to see some mention of Docker, but we jump straight to celo.env below.
Please clarify your section headers. For reference, this is how GitBook is rendering this (don't mind the red underlining, that's just my browser spellcheck struggling to live in the 21st Century):

<img width="768" alt="Screen Shot 2021-06-16 at 4 11 19 PM" src="https://user-images.githubusercontent.com/2707197/122301136-7f9bf480-cebd-11eb-8f27-dae3e53f3c05.png">

2021-06-16 22:38 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +  curl -o celo.env https://gist.githubusercontent.com/alchemydc/ce712f6f3caa7ec79f15f930ed5904ed/raw/385c65b1d3f760854258bfd6dd8cbd135710b78f/celo.env
Using `curl` is cool and all, but when the contents of the file is merely two lines, you definitely don't need to do it this way (though I applaud your ingenuity overall). 
Consider an alternative such as asking readers to create a new file `celo.env` & providing the lines to be cut and pasted from the text of the tutorial. Since copy/paste is needed here anyway for a reader to get this command into their terminal, save the bandwidth and cut out the extra step 😄 Best to keep it simple 👍🏻

2021-06-16 22:38 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` cd ```
`cd` by itself isn't going anywhere, you can remove this 😉

2021-06-16 22:38 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` mv ../celo.env . ```
So structurally, I see what you're doing here but there's a simpler way to do it (from the top) :
```bash
mkdir celo-data-dir && cd celo-data-dir
mv ../celo.env .
mv ../start_celo.sh .
source *
```

2021-06-16 22:38 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` cd celo-data-dir ```
We would still be in this directory, no? This could be removed.

2021-06-16 22:38 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +   - Copy the public address key that is provided with your new node account.
I know you're showing this on the video, but this might be a good place to show a screenshot of where that public address is displayed so that nobody is confused 😄

2021-06-16 23:18 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> + ``` usermod -aG sudo $YOURUSERNAME ```
I just clearly defined it, it was supposed to stand for the currently logged in user name.

2021-06-16 23:41 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +Watch the videos and follow along with the writen tutorial.
Spelling is hard.

2021-06-16 23:42 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +* Install the Valora app on ios/android:https://valoraapp.com/
ah yes that's better

2021-06-16 23:42 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +* Download debian 10 64bit:https://www.debian.org/
certainly will use this

2021-06-16 23:47 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +* Hit the Create New in oracle VM
lol that day is coming, my next tutorial can be fending of waves of virtual machines 2050.

2021-06-17 00:51 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +* Now the Virtual Machine is ready
I will be using all of these, thank you

2021-06-17 00:51 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> + #### (Code is entered into the VM terminal)
will do

2021-06-17 01:02 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> + ``` su -  ```
I changed all the single commands to 1 backtick

2021-06-17 01:08 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +   #### Vim is a tool used for editing files within the terminal. Here's a guide on Vim: https://www.linux.com/training-tutorials/vim-101-beginners-guide-vim/
I added that built in link

2021-06-17 01:09 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +   #### Vim is a tool used for editing files within the terminal. Here's a guide on Vim: https://www.linux.com/training-tutorials/vim-101-beginners-guide-vim/
its not so hard if you don't spam buttons and just take your time. I got used to it pretty quick, lets not forget the first time I was very frustrated.

2021-06-17 01:10 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +   #### Run an external program called VBoxLinuxAdditions, which enables bidirectional copy/paste.
will add

2021-06-17 01:10 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` cd /media/ ```
your right ill just use that path

2021-06-17 01:16 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` cd /media/cdrom ```
your right I can enable both copy/paste and screen resolution in one go. You know what im ganna pump out a new vid for my code tonight.

2021-06-17 01:17 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` cd /media/cdrom ```
So much has changed

2021-06-17 01:53 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` sudo sh VBoxLinuxAdditions.run ```
Im going to scrap this and just use it once with bash, they do the exact same thing.

2021-06-17 01:55 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +   #### The interpreter directive, "#!" is called a "shebang". The path, "/bin/bash" sets the terminal to interpret in bash.
I was just trying to break it up into smaller pieces but it didn't render as I hoped.

2021-06-17 02:07 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` cd celo-data-dir ```
yes ill remove it, thanks!

2021-06-17 02:09 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` mv ../celo.env . ```
yes I like that

2021-06-17 02:09 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` mv ../celo.env . ```
will do

2021-06-17 02:10 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +   - Copy the public address key that is provided with your new node account.
will do

2021-06-17 02:10 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +  ``` cd ```
removed it

2021-06-17 02:25 UTC, Aidandedecker commented on celo/tutorials/celo-node-video-tutorial.md
> +  curl -o celo.env https://gist.githubusercontent.com/alchemydc/ce712f6f3caa7ec79f15f930ed5904ed/raw/385c65b1d3f760854258bfd6dd8cbd135710b78f/celo.env
my reasoning was it is easier to curl in start_celo.sh so why not do them both that way. I'll provide the contents of celo.env, instead of the screen shot if they want to do it that way.

2021-06-17 14:30 UTC, pyr0gan commented on celo/tutorials/celo-node-video-tutorial.md
> +  curl -o celo.env https://gist.githubusercontent.com/alchemydc/ce712f6f3caa7ec79f15f930ed5904ed/raw/385c65b1d3f760854258bfd6dd8cbd135710b78f/celo.env
You're not wrong in the approach, it is perhaps a sign of my age and time spent in computing. I don't ever blindly trust long URLs as a general rule. They make the hairs on the back of my neck stand up. Perhaps I am sometimes _overly_ conscious of security.

Just for a second, imagine that the contents of that file were some malicious code and that you were asking users to download it and run it (I know it isn't and you're not, but I'm just trying to walk you through the OPSEC mindset).
Removing the `curl` step and being clear in what you want users to put on their system is just a response to that open question. Make of it what you will 😄

2021-06-17 17:03 UTC, merged

2021-06-21 13:58 UTC, pyr0gan commented
So what comes next @Aidandedecker ? Do you have a new tutorial in the works yet? 🚀

2021-06-21 22:59 UTC, Aidandedecker commented
Not yet @pyr0gan, but I'm thinking of some! Iyk when I find a good one.


On Mon, Jun 21, 2021 at 7:59 AM Rogan X ***@***.***> wrote:

> So what comes next @Aidandedecker <https://github.com/Aidandedecker> ? Do
> you have a new tutorial in the works yet? 🚀
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/figment-networks/datahub-learn/pull/76#issuecomment-865055351>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATHB325GDXAYWHSKRPPHZE3TT5ASZANCNFSM43O7FLRA>
> .
>

2021-06-22 18:30 UTC, Aidandedecker commented
@pyr0gan just heard about the, Agoric block chain! What do you think about
a Agoric full node tutorial!

On Mon, Jun 21, 2021, 4:59 PM aidan dedecker ***@***.***>
wrote:

> Not yet @pyr0gan, but I'm thinking of some! Iyk when I find a good one.
>
>
> On Mon, Jun 21, 2021 at 7:59 AM Rogan X ***@***.***> wrote:
>
>> So what comes next @Aidandedecker <https://github.com/Aidandedecker> ?
>> Do you have a new tutorial in the works yet? 🚀
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/figment-networks/datahub-learn/pull/76#issuecomment-865055351>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ATHB325GDXAYWHSKRPPHZE3TT5ASZANCNFSM43O7FLRA>
>> .
>>
>