Using truffle with C-chain and NFTs creation
figment-networks/datahub-learn pull request #77
Opened 2021-04-25 21:32 UTC by Devilla

## Tasks done: 📝

- [ ] Avash removed: running truffle with C-chain on Avalanche

- [ ] Create, mint and transfer NFT on Avalanche using Avalanche Wallet

2021-04-28 03:39 UTC, Devilla commented
@yash-sharma1 Can you review it, thanks. 😊

2021-04-28 08:24 UTC, yash-sharma1 requested changes
all looks good to me but I think you didn't edit the same in `SUMMARY.md` file. 
Please check this guide section 7 - Contribution and publishing process to make sure to publish it carefully and to avoid any conflicts - [Check Here](https://docs.google.com/document/d/13LWLrWzZ34M0ldWGeDANcWxw9nEWk3AX3VwXRBIOs1M/edit?usp=sharing)

2021-04-28 08:24 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +
Before the Introduction please add the "About The Author" section and put your bio in it along with your social media handle (if any)

2021-04-28 08:35 UTC, Devilla commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +
Okay, I'll update that. Thanks.

2021-05-02 17:29 UTC, Devilla commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +
@yash-sharma1 I have updated the files as per the requirements, please review and merge.

2021-05-02 17:33 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +
Thanks for the update @devilla We'll review the changes and will update you accordingly. Appreciate your work 💯

2021-05-02 18:12 UTC, Devilla commented
Done.

2021-05-03 10:31 UTC, yash-sharma1 reviewed
@Devilla Here in your new commit for this file - `network-documentation/avalanche/tutorials/using-truffle-with-the-avalanche-c-chain.md` you update the existing tutorial which is from Avalanche Official Docs and I didn't get what was the reason, as this specific tutorial is from official Avalanche Docs. Can you please explain it to us before we take it forward for review and merging it :)

2021-05-04 04:33 UTC, Devilla commented
> @Devilla Here in your new commit for this file - `network-documentation/avalanche/tutorials/using-truffle-with-the-avalanche-c-chain.md` you update the existing tutorial which is from Avalanche Official Docs and I didn't get what was the reason, as this specific tutorial is from official Avalanche Docs. Can you please explain it to us before we take it forward for review and merging it :)

I have worked on some of the documentation and implementation of the [```using-truffle-with-the-avalanche-c-chain``` ](https://github.com/ava-labs/avalanche-docs/commits?author=Devilla) with avalanche and I updated their docs based on features that I find very useful or unnecessary as a developer. I have also added an update regarding that on avalanche also. [Avash dependency]( https://github.com/ava-labs/avalanche-docs/pull/141), I'll remove this commit until it's updated on avalanche official docs. Thanks.

2021-05-04 11:26 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-truffle-with-the-avalanche-c-chain.md
@Devilla I think you need to remove commit on this file or revert these changes before we take it further

2021-05-04 16:29 UTC, Devilla commented on network-documentation/avalanche/tutorials/using-truffle-with-the-avalanche-c-chain.md
I've reverted the changes to the original. Thanks.

2021-05-05 17:56 UTC, Devilla commented
Too much conflicts here now will PR again with individual files.

2021-05-05 17:56 UTC, closed without merging