ERC20 transfer tutorial added, file name consistency implemented, README.md edited.
figment-networks/datahub-learn pull request #91
Opened 2021-05-01 06:01 UTC by blackwidoq

# Description*

Please include a summary of the changes and which issues are fixed. Please also include relevant details and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change*

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Typo fix

## This PR created for* - 
- [ ] Figment Learn Docs (Pathway, Tutorials, New Tutorials etc.) changes/updates/fixes

# How Has This Been Tested? (If Applicable)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration*** (If Applicable):
* Firmware version:
* OS:
* Network/Protocol:
* SDK:

# Checklist*:

- [ ] I updated the `SUMMARY.md` file (FYI, It's needed only when you're adding/creating a new file like submitting a new tutorial, pathway section)
- [ ] I checked and read the contribution guide before making this PR [**HERE**](https://docs.google.com/document/d/13LWLrWzZ34M0ldWGeDANcWxw9nEWk3AX3VwXRBIOs1M/edit)  
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Other Information (Optional)
*Please add any other information/details you would like to let us know related to your proposed changes and PR*

Note - Above ponits marked with * are mandatory to fill :)

2021-05-03 10:06 UTC, yash-sharma1 requested changes
@blackwidoq Appreciate it, very well written and this is a really improvised version of your work. 
- All things are good just one thing which needs to be added that is after every execution of the code make sure to add the sample output so user/learners can get an idea that what should be the output and if they run in any issue it'll help them in resolving that.
- Before the next commit make sure to edit the `SUMMARY.md` file and add your new tutorial in that. For more details refer to this guide (Last Step) [**HERE**](https://docs.google.com/document/d/13LWLrWzZ34M0ldWGeDANcWxw9nEWk3AX3VwXRBIOs1M/edit?usp=sharing)

2021-05-03 21:00 UTC, blackwidoq commented
@yash-sharma1  Hello, ive made the changes requested. I've added cropped images of the terminal outputs and added some comments. Also, SUMMARY.md has been changed.

2021-05-04 10:52 UTC, yash-sharma1 requested changes

2021-05-04 10:52 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/avax-c-chain-to-eth-address-transfer-tutorial.md
> +## About the author
"About the Author" will come after the title of the tutorial and new heading/topic will come as Introduction

2021-05-04 10:52 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/avax-c-chain-to-eth-address-transfer-tutorial.md
Mention Introduction here

2021-05-04 10:52 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/ERC20_token_transfer_to_ETH_address.md
> +
Mention "Introduction" here

2021-05-04 10:52 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/ERC20_token_transfer_to_ETH_address.md
> +## About the author
Put it after the heading of the tutorial

2021-05-04 14:29 UTC, blackwidoq commented
@yash-sharma1  Thank you for the suggestions. I made formatting changes to both scripts.

2021-05-05 07:01 UTC, yash-sharma1 approved these changes

2021-05-05 07:54 UTC, yash-sharma1 approved these changes

2021-05-05 07:58 UTC, merged