Add a validater
figment-networks/datahub-learn pull request #93
Opened 2021-05-02 17:43 UTC by Devilla

# Description*

Added documentation for successfully adding  a validator on Avalanche.

## Type of change*

Please delete options that are not relevant.

- [ ] New feature (added screenshots and more description).
- [ ] This documentation required an update.

## This PR created for* - 
- [ ] DataHub Official Docs (Network Documentation, API docs etc.) changes/updates/fixes
- [ ] Figment Learn Docs (Pathway, Tutorials, New Tutorials etc.) changes/updates/fixes

# Checklist*:

- [ ] I updated the `SUMMARY.md` file (FYI, It's needed only when you're adding/creating a new file like submitting a new tutorial, pathway section)
- [ ] I checked and read the contribution guide before making this PR [**HERE**](https://docs.google.com/document/d/13LWLrWzZ34M0ldWGeDANcWxw9nEWk3AX3VwXRBIOs1M/edit)  
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Note - Above points marked with * are mandatory to fill :)

2021-05-03 10:39 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/using-truffle-with-the-avalanche-c-chain.md
@Devilla I don't think this content needs to be removed or change as this tutorial is from the official Avalanche Docs so we will prefer to keep it the same way. Any reason to change this :)
Can you please revert these changes so we can merge your PR after review

2021-05-03 10:44 UTC, yash-sharma1 requested changes
@Devilla If I'm not wrong you're adding 2-3 tutorials at once and as I see you made changes and mentioned only one addition of tutorial in the `SUMMARY.md` file 
So if you're adding more than one tutorial you need to add all of them in the `SUMMARY.md` file also this filename `network-documentation/avalanche/tutorials/Create an ERC-20 Token.md` should be hyphenized like `network-documentation/avalanche/tutorials/Create-an-ERC-20-Token.md` and then add it to the `SUMMARY.md` file
If all these tutorial are in series make them altogether in the group.

2021-05-03 16:46 UTC, Devilla commented on network-documentation/avalanche/tutorials/using-truffle-with-the-avalanche-c-chain.md
Okay, sure will revert these and update when Avalanche updates it.

2021-05-05 17:58 UTC, Devilla commented
Too much conflicts here now will PR again with individual files. Thanks.

2021-05-05 17:58 UTC, closed without merging