Create mint transfer nft
figment-networks/datahub-learn pull request #96
Opened 2021-05-06 02:52 UTC by Devilla

# Description*

Creation, Minting, and Transfer of NFTs updated using some interesting example of pokemon coins. 🐱 

Fixes # (issue)

## Type of change*

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## This PR created for* - 
- [x] DataHub Official Docs (Network Documentation, API docs etc.) changes/updates/fixes
- [x] Figment Learn Docs (Pathway, Tutorials, New Tutorials etc.) changes/updates/fixes

# Checklist*:

- [x] I updated the `SUMMARY.md` file (FYI, It's needed only when you're creating a new file like submitting a new tutorial, pathway section)
- [ ] I created one tutorial for this PR (one PR <=> one tutorial)
- [ ] I checked and read the contribution guide before making this PR [**HERE**](https://docs.google.com/document/d/13LWLrWzZ34M0ldWGeDANcWxw9nEWk3AX3VwXRBIOs1M/edit)  
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Other Information (Optional)
*Please add any other information/details you would like to let us know related to your proposed changes and PR*

Note - Above points marked with * are mandatory to fill :)

2021-05-06 04:04 UTC, Devilla commented
@yash-sharma1 Completed.

2021-05-06 08:41 UTC, yash-sharma1 requested changes
@Devilla I love this tutorial and the way you explained everything with the help of graphics but I'm concerned that on merging the PR this tutorial will overwrite another tutorial which is available on Figment learn from official AvaLabs Docs, I would prefer to have this tutorial as a separate tutorial and we don't need to make any changes in the existing tutorial `Create NFTs with the Avalanche Walle` we can add your tutorial just below to this to have it in series. 
So please make changes and make this tutorial separate one.

2021-05-06 09:18 UTC, Devilla commented
Okay, sure @yash-sharma1.

2021-05-06 09:53 UTC, yash-sharma1 reviewed
@guillaumegaluz can you please have a look at it. 
This tutorial can be called an extended version of this existing tutorial from Ava Labs - [**HERE**](https://learn.figment.io/network-documentation/avalanche/tutorials/create-nfts-with-the-avalanche-wallet) 
CC - @Y-Folla

2021-05-12 02:37 UTC, Devilla commented
@pyr0gan Hi hope you're doing well. Can you review this I was waiting for it over a week, others might be busy. You seems quite active here. Thanks.

2021-05-12 06:14 UTC, yash-sharma1 commented
> @pyr0gan Hi hope you're doing well. Can you review this I was waiting for it over a week, others might be busy. You seems quite active here. Thanks.

Hey @Devilla
Actually, we were working on few things to make tutorials more consistent and well structured because of that PR is still under review. So moving further I request you please follow this guide **[HERE](https://learn.figment.io/other/tutorial-guidelines)** to make some required changes in your PR. Let us know if you have any queries.

2021-05-13 13:24 UTC, Devilla commented
> > @pyr0gan Hi hope you're doing well. Can you review this I was waiting for it over a week, others might be busy. You seems quite active here. Thanks.
> 
> Hey @Devilla
> Actually, we were working on few things to make tutorials more consistent and well structured because of that PR is still under review. So moving further I request you please follow this guide **[HERE](https://learn.figment.io/other/tutorial-guidelines)** to make some required changes in your PR. Let us know if you have any queries.

Ok.

2021-05-26 22:40 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +to learn more about the avalanche, please visit-(https://docs.avax.network/)
Consider rewording this to "In preparation for the tutorial, we will need to have some images on hand for testing the upload to Avalanche wallet. For more information on the Avalanche wallet, please refer to the documentation [here](https://docs.avax.network/)".

2021-05-26 22:49 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
>  NFT is an interesting term nowadays, I first interacted with this creature when I was playing around on Avalanche wallet. These are `Collectibles` that you can create and share with each other. In mo
While this certainly isn't the worst explanation of NFTs I have read this year, there are a couple of points to raise:
- Writing the introduction in the first person isn't optimal. The editorializing isn't bad, and I definitely see that you are trying to make the subject matter more accessible. It would be beneficial here to tighten up the language a little bit, and to be technically correct for the sake of the readers. 
- "In more technical terms" can be a great depending on the audience. If we aim to discuss the ERC721 token standard, it would be best to give some links to more information or just explain what an Ethereum Request for Comments #721 has to do with the term 'Non-Fungible Token'. This is a little bit of a minefield, and I can see what you are trying to say - I just believe it a potential source of confusion. Best to clarify!

Overall, this can be rewritten slightly to accommodate an explanation of token standards, and keeping the tone consistent with the rest of the tutorial 😄

2021-05-28 20:41 UTC, guillaumegaluz requested changes

2021-05-28 20:41 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +# Create NFTs with the Avalanche Wallet
you might need to add the new PR title here too

`Create, Mint and Transfer NFT with Avalanche Wallet`

I would also pluralize NFT to NFTs

2021-05-28 20:41 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +[Devendra Yadav](https://github.com/devilla)
move this at the end of the tutorial 

(https://app.gitbook.com/@figment-learn/s/learn-docs/other/tutorial-guidelines)

2021-05-28 20:41 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +The author of the original source and the original documentation can be found in the given link-
can you fix formatting?

This tutorial is based on the original one on the [Avalanche Documentation]

2021-05-28 20:41 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +[**The original tutorial can be found in the AVA Labs documentation here**](https://docs.avax.network/build/tutorials/smart-digital-assets/wallet-nft-studio).
you already said that above

2021-05-28 20:41 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +* Step 1- Go to [Avalanche wallet](wallet.avax.network) and click on create new wallet.
This is confusing. You're using **both** the headings `###` and the `Step X`. I think if you use the headings you don't need the `Step X` it's too much

You can also remove all the bullet points before `Step X`

2021-05-28 20:41 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +* Advanced
why write the list with bullet points and ALL the items here if the image above shows it? You can rmeove this, or just mention a few, inline

2021-05-28 20:41 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +To make experimenting with the creation and exchange of NFTs easier, we have built **NFT Studio** into the [Avalanche Wallet](https://wallet.avax.network/), where you can use it to create NFTs as ass
who's "we"? did you just copy and paste this?

2021-05-28 20:41 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +### Create NFT Family
Create a NFT Family

2021-05-28 20:41 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +Before Minting, Go to the Studio tab as shown below- you will see a heading " Collectibles", in which two sections are provided
no capital at `Minting`

2021-05-28 20:41 UTC, guillaumegaluz commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +Made with ❤️ in [India](https://en.wikipedia.org/wiki/India).
im fine with this, but add it at the end of "About the Author"

2021-06-01 19:09 UTC, guillaumegaluz commented
Hey @Devilla - let us know if you're still interesting in fixing the comments and publishing this! Thansk

2021-06-03 04:48 UTC, Devilla commented
> Hey @Devilla - let us know if you're still interesting in fixing the comments and publishing this! Thansk
Yes, just been busy with other projects. I will update thanks.

2021-06-03 17:45 UTC, Devilla commented
Done. @guillaumegaluz Thanks.

2021-06-14 16:51 UTC, pyr0gan requested changes
Please have a look at my comments and make the suggested changes. As this is an image-heavy tutorial, we just need to be cautious in the presentation 😉

2021-06-14 16:51 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +Step 8- You can use the TxID to look up the transaction in [the explorer](https://explorer.avax.network/)
> You can use the TxID to look up the transaction on the [Avalanche block explorer](https://explorer.avax.network/). Besides the name and the ticker, you will need to enter a **Number of Groups**, which is how many distinct collectibles the newly created family will hold. Choose carefully, because once created the parameters of the collectible family cannot be changed.

2021-06-14 16:51 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +Step 10- you need to create a new mint, by providing a name, a code, and a number of groups.
> To create a new mint, provide a name, a code, and a number of groups. Note that a fee of 0.1 AVAX will be deducted from your balance to mint. For testing, you can use the Fuji testnet. You will need to switch networks in the Avalanche wallet UI. Once you are on the Fuji testnet, it is possible to get AVAX for testing from the official faucet.

2021-06-14 16:51 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +Step 11- Go to Avax faucet:
> Go to the AVAX faucet at https://faucet.avax-test.network/ :

2021-06-14 16:51 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +Step 12- copy the address from your avalanche wallet and paste it in the address bar, you will receive 2 Avax coins.
> Paste the address of your wallet (which you can copy from the Avalanche wallet UI) into the textinput and pass the CAPTCHA to receive 2 AVAX tokens.

2021-06-14 16:51 UTC, pyr0gan commented on network-documentation/avalanche/tutorials/create-mint-transfer-nft.md
> +Step 15- That is an NFT that has a **Title**, **URL** for the image, and a **Description**. Enter the required data, as well as the **Quantity**, which will determine how many copies of the collectib
> That is an NFT that has a **Title**, **URL** for the image, and a **Description**. Enter the required data, as well as the **Quantity**, which will determine how many copies of the collectible will be created. As before, enter the data carefully - you won't be able to change anything once collectibles are minted. You will see a preview of the data where you can check how your collectible will look.

2021-06-14 19:05 UTC, pyr0gan approved these changes
Thanks for taking care of these fixes so quickly! 🚀 

One more bit of housekeeping, the References section should be at the bottom of the tutorial instead of the top. Also consider saying 

> This tutorial is based on the official [Avalanche Documentation](https://docs.avax.network/build/tutorials/smart-digital-assets/wallet-nft-studio).

👍🏻

2021-06-14 20:03 UTC, merged

2021-06-14 21:30 UTC, pyr0gan commented
Can you please make a fresh PR from your branch with the image links fixed, @Devilla ? It will be much simpler than trying to revert.