ERC20 transfer to ETH address documentation update/clarification added
figment-networks/datahub-learn pull request #99
Opened 2021-05-06 18:25 UTC by blackwidoq

# Description*

Please include a summary of the changes and which issues are fixed. Please also include relevant details and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change*

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Typo fix

## This PR created for* - 
- [ ] DataHub Official Docs (Network Documentation, API docs etc.) changes/updates/fixes
- [ ] Figment Learn Docs (Pathway, Tutorials, New Tutorials etc.) changes/updates/fixes

# How Has This Been Tested? (If Applicable)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration*** (If Applicable):
* Firmware version:
* OS:
* Network/Protocol:
* SDK:

# Checklist*:

- [ ] I updated the `SUMMARY.md` file (FYI, It's needed only when you're creating a new file like submitting a new tutorial, pathway section)
- [ ] I created one tutorial for this PR (one PR <=> one tutorial)
- [ ] I checked and read the contribution guide before making this PR [**HERE**](https://docs.google.com/document/d/13LWLrWzZ34M0ldWGeDANcWxw9nEWk3AX3VwXRBIOs1M/edit)  
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Other Information (Optional)
*Please add any other information/details you would like to let us know related to your proposed changes and PR*

Note - Above ponits marked with * are mandatory to fill :)

2021-05-08 15:35 UTC, blackwidoq commented
@yash-sharma1   Hello, I made changes to the previous tutorial (`avax-c-chain-to-eth-address-transfer-tutorial.md`), adding example outputs, instructions on creating `.js` file and how to run the script in the terminal, etc.

2021-05-11 04:44 UTC, yash-sharma1 requested changes

2021-05-11 04:44 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/erc20-token-transfer-to-eth-address.md
> +The finished script should look as follows:
The entire script file should be added above before the execution step so shift it above and after that the final execution step in both the tutorials

2021-05-11 04:44 UTC, yash-sharma1 commented on network-documentation/avalanche/tutorials/avax-c-chain-to-eth-address-transfer-tutorial.md
> +
The entire script file should be added above before the execution step so shift it above and after that the final execution step in both the tutorials

2021-05-12 03:20 UTC, blackwidoq commented
@guillaumegaluz  Ok. I thought of asking people to go on [Pangolin](https://pangolin.exchange/) and swap AVAX for PNG or some other ERC20 tokens. But, I think it's kind of scary when a tutorial involves real money. So, I thought of asking people to go on Pangolin on Fuji, instead of Mainnet, to get some ERC20 tokens. However, when I looked up the [PNG address](https://github.com/pangolin-community/tokenlists/blob/main/fuji.tokenlist.json) on Fuji, I realized the Pangolin dex pretty much ran out of the test PNG tokens. So, I think I am going to follow [the official AVA lab ERC20 mint tutorial](https://docs.avax.network/build/tutorials/smart-digital-assets/create-erc-20-token-on-avalanche-c-chain), mint a large quantity of ERC-20 token and make them available on Pangolin by creating a liquidity pool and walk people through 1. how to go on Pangolin dex, 2. How to find the token I minted and swap FUJI AVAX for the example ERC-20 tokens 3. How to transfer the newly acquired tokens from one's Metamask to the C-chain of one's AVAX wallet 4. How to have it show up on your AVAX wallet.  

I guess what I outlined above can be the starting point, as opposed to assuming that one already has ERC-20 tokens in one's wallet.   I might actually create a Faucet instead of having people go on Pangolin and swap Fuji AVAX for the ERC-20 tokens.

2021-05-12 06:18 UTC, yash-sharma1 commented
> @guillaumegaluz Ok. I thought of asking people to go on [Pangolin](https://pangolin.exchange/) and swap AVAX for PNG or some other ERC20 tokens. But, I think it's kind of scary when a tutorial involves real money. So, I thought of asking people to go on Pangolin on Fuji, instead of Mainnet, to get some ERC20 tokens. However, when I looked up the [PNG address](https://github.com/pangolin-community/tokenlists/blob/main/fuji.tokenlist.json) on Fuji, I realized the Pangolin dex pretty much ran out of the test PNG tokens. So, I think I am going to follow [the official AVA lab ERC20 mint tutorial](https://docs.avax.network/build/tutorials/smart-digital-assets/create-erc-20-token-on-avalanche-c-chain), mint a large quantity of ERC-20 token and make them available on Pangolin by creating a liquidity pool and walk people through 1. how to go on Pangolin dex, 2. How to find the token I minted and swap FUJI AVAX for the example ERC-20 tokens 3. How to transfer the newly acquired tokens from one's Metamask to the C-chain of one's AVAX wallet 4. How to have it show up on your AVAX wallet.
> 
> I guess what I outlined above can be the starting point, as opposed to assuming that one already has ERC-20 tokens in one's wallet. I might actually create a Faucet instead of having people go on Pangolin and swap Fuji AVAX for the ERC-20 tokens.

Hey @blackwidoq 
Actually, we were working on few things to make tutorials more consistent and well structured. So moving further I request you please follow this guide **[HERE](https://learn.figment.io/other/tutorial-guidelines)** to make some required changes in your PR.  Also, please add the extra info and explanation in the tutorial as per the requested changes. Let us know if you have any queries.

2021-05-16 03:04 UTC, blackwidoq commented
@yash-sharma1 @guillaumegaluz  Apparently, after one of the recent updates done by Avalanche, the old script for ERC-20 token transfer resulted in an error.  The same error was reported by multiple people. I think it has to do with the Berlin update being applied to the C-chain? Anyhow, I had to find a new way to do it. So, the tutorial is quite different from the old one but it achieves the same objective. Plus, now we do everything within one library (ethers), which is nice.  I outlined how to get a dummy ERC-20 token into one's Avalanche wallet C-chain as well.

2021-05-18 14:26 UTC, yash-sharma1 requested changes
Thanks for the quick fix @blackwidoq 

few points on this 
- About the Author section should be at the end of the tutorial. I request you to please give a thorough review to **[Sample Tutorial Structure](https://learn.figment.io/other/tutorial-guidelines/sample-tutorial-structure)** it'll help you in understanding the structure. 
- The introduction should be in 5-6 lines and it should contain what you're building/doing, what's the goal of the tutorial and for what purpose you're using these mentioned libraries etc.
- Make sure to take the error-driven approach
- At the end final script should be mentioned before showing the final output.
- Please follow the Sample Tutorial Structure and guidelines to make it consistent.

2021-05-26 22:16 UTC, pyr0gan commented
> Thanks for the quick fix @blackwidoq

@blackwidoq any movement on this? 😄 Just want to keep things from getting stale.

2021-06-14 17:04 UTC, pyr0gan commented
@blackwidoq We might need to close this PR. Can you confirm if you plan on completing it, please? 😄

2021-06-15 01:40 UTC, blackwidoq commented
@pyr0gan Hi, sorry for the delay. I do intend to finish it. I am actually writing my phd thesis at the moment and have my defense late August. would it be ok if I finish the work after my defense?

2021-06-15 18:10 UTC, pyr0gan commented
> @pyr0gan Hi, sorry for the delay. I do intend to finish it. I am actually writing my phd thesis at the moment and have my defense late August. would it be ok if I finish the work after my defense?

It will be here waiting when you get back. Best of luck defending your PhD thesis, that's some heavy work! 😅

2021-07-01 23:11 UTC, closed without merging